### ISSUE TITLE
[new ui] new transaction details screen

### ISSUE THREAD

**Issue by debris** [paritytech/parity-signer#101]
*Image moved to #106 view*

**Comment by bnvk** [comment]
@debris just to be clear, above you used the interface I was using for "signing" but the title of this issue implies "viewing" an transaction. I've clarified this with more interfaces now, as well as opened one specifically for signing #106

### View Transaction

<img src="https://user-images.githubusercontent.com/48677/39826659-a94ee48a-53b5-11e8-93bb-2b50101cfb3b.png" width="350">

### View Transaction Message

<img src="https://user-images.githubusercontent.com/48677/39826660-a96fe996-53b5-11e8-973e-b5e181b19f22.png" width="350">

**Comment by fckt** [comment]
A bit of fabrications:
1) show somehow in the AccountCard whether you have secret key for this account or not (is it your own account or not);
2 ) it would be useful to know also if it is a known account or it is an account which never been involved in any transactions signed using the app.
@bnvk

**Comment by bnvk** [comment]
> would be great show somehow in the AccountCard whether you have secret key for this account or not (is it your own account or not);

I do not understand. I thought *every* account on the Parity Signer meant the private key was inside the app. Is this incorrect?

> it would be useful to know also if it is a known account or it is an account which never been involved in any transactions signed using the app before. Also I think it could be a great scenario to make any account (own, known or new) clickable. A click on the account will lead to details. 

Unless I misunderstand you, I totally agree and was being handled in the `Account Details` view in #97 
I don't understand the rest of your points @fckt like  "own, known or new" accounts.

**Comment by fckt** [comment]
By "own, known or new" I the following:
"own" - it's an account you have private key for in the app
"known" - it's an account which was involved in transactions, signed using the current device. User can name for better remembering. But user does not have a private key from these accounts
"new" - these are accounts which wasn't being involved in any transactions before. It could be useful to know for user that the account he/she is sending a transaction to was never being involved in the past transactions

**Comment by fckt** [comment]
Of course it doesn't affect the Account List in any way. We list only accounts with private key in "Accounts" tab.
