### ISSUE TITLE
No focus when scanning a QR Code on iOS iPod Touch doesn't lead to refocus

### ISSUE THREAD

**Issue by lucasvo** [paritytech/parity-signer#1012]
I've noticed a very weird bug that has now happened at least three times on my signer:

The app doesn't focus when I click on scanner. Even when repeatedly locking and unlocking and navigating away from the scanner. When the app is stuck in this state, switching to the camera app while the signer is open and then switching back to signer fixes the autofocus and makes the signer correctly focus (and adjust focus as I move the camera).

I'm using v 5.0.0 on the most recent ipod touch with iOS 15.2

**Comment by Slesarew** [comment]
The auto-refocus was disabled as it slows down scanning long QR movies; camera refocuces once when the "scan" screen is selected. I didn't have time to add smooth tap handling to refocus yet, sorry, I'm aware of this and it is not intended behavior, but quite expected for now.

**Comment by Slesarew** [comment]
The fact that you do get tracking focus is really weird though. I suspect that camera controls are not as isolated across the apps as one might expect. This is sad.

**Comment by lucasvo** [comment]
it's been really really slow to get the camera to focus at all - are you sure it refocuses once the scan screen is detected? thanks for the details though makes sense.

**Comment by Slesarew** [comment]
It focuses once upon scan screen is initiated. There is some other elusive bug that fails to reset the scan screen related to #998
