### ISSUE TITLE
Add mini-help on certificates into network settings

### ISSUE THREAD

**Issue by varovainen** [paritytech/parity-signer#1023]
Show to user explicitly, which certificates would be suitable for the network specs and metadata updates.

For example, if a network is verified by the general verifier, show who the general verifier is.
If a network is verified by custom verifier, show who the custom verifier is and show that the custom verifier could potentially be overridden by the general verifier etc.

**Comment by krodak** [comment]
`Verifier Certificate` field along with Key value is present on updated v6.0 designs for Network Details screen to be found within settings, closing for now, let us know @varovainen if it would be better to extend it or update information set that can be found there
