### ISSUE TITLE
Use ERC-681

### ISSUE THREAD

**Issue by ligi** [paritytech/parity-signer#103]
Hi,

it would be great if the parity-signer could use ERC-681 in this screen:

![image](https://user-images.githubusercontent.com/111600/39117622-b2576f0a-46e7-11e8-98a2-b875039af8f1.png)

This would help interoperability. If you are really against using ERC-681 here - please at least consider prefixing with 0x. Currently there is no context at all - at least some context would be good ;-)

**Comment by ligi** [comment]
@maciejhirsz yes exactly - thanks. Making an ERC for the other QR-code would also be really great - but you are right 681 is not really made for this.

**Comment by fckt** [comment]
In the new version account QR code now yields address in the ERC-681 format.

**Comment by Nlbgsuite** [comment]
Nlb
