### ISSUE TITLE
Please publish checksum for latest v5.0.1 apk

### ISSUE THREAD

**Issue by mil99** [paritytech/parity-signer#1033]
1) Please publish checksum for latest v5.0.1 apk - for those who prefer to download apk from github.
2) I don't see beta in the new release. Is it still under beta?
3) Does this release support parachain crowdloans?

Thank you.

**Comment by Slesarew** [comment]
2. It still was not audited by 3rd party. Consider it beta indeed.
3. It does, mostly. Please report if something does not work there.
