### ISSUE TITLE
Better errors and alerts

### ISSUE THREAD

**Issue by montekki** [paritytech/parity-signer#1034]
Errors and their UI handling are extremely important for the security and the UX. Right now errors show just a text blob in red font which reminded me of the post [how to design better web3 error messages](https://medium.com/@JonCrabb/how-to-design-better-web3-error-messages-bd96e12fa582).

I would also say that the error types and traits inside backend need a closer look. So this issue includes:

- [ ] Error UX
- [ ] Backend changes

Probably it would be a good idea to go in this order: UI|UX requirements should be formed and then propagated into code.

**Comment by Slesarew** [comment]
It is important to note here, that the errors should retain their current dry and minimalistic format for development and cli application, but also get fancy UI-oriented and unified form with multiple fields.

I'm not sure about use of native alert elements (especially those in iOS), they seem to fall out from our design concept, have very limited capabilities and could not be made uniform across platforms. Although they do look pretty even when not designed well.

This also is related to discussion here https://github.com/paritytech/banana-recovery-rust/pull/2 - this crate will probably become part of the Signer soon.

**Comment by montekki** [comment]
Support for most common cases implemented.
