### ISSUE TITLE
Signer tutorial visibility

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#1036]
I tried to find a link to "add network" tutorial from anonymous smartphone today and failed. We need to make some clear path to docs appear in the first set of results of duckduckgo things like "parity signer manual" instead of blazingly fresh news like "parity signer 2.0 is released soon" things.

Parity Signer landing is indeed among the top results. Maybe we should just add a large button there.

**Comment by krodak** [comment]
Should be much improved with 6.0 release which included dedicated tutorial for adding network, if this is still not enough, let us know, we'll plan on extending / improving the flow 🙏🏻 Closing for now
