### ISSUE TITLE
How to add other network

### ISSUE THREAD

**Issue by wojiaopaidaxing** [paritytech/parity-signer#1039]
I used parity signer (version 5.0.1)
I cannot add other network from scan a metadata
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/9145559/168774932-cf74fa06-4028-4137-a5aa-862d24689acc.png">

**Comment by Slesarew** [comment]
https://paritytech.github.io/parity-signer/tutorials/Add-New-Network.html
