### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#104]
<img src="https://user-images.githubusercontent.com/2613714/38880154-52ae7700-4265-11e8-8d36-c12afe7ce6f7.png" width="350">

https://github.com/paritytech/parity-signer/issues/96
https://github.com/paritytech/parity-signer/issues/97
https://github.com/paritytech/parity-signer/issues/98
https://github.com/paritytech/parity-signer/issues/99
https://github.com/paritytech/parity-signer/issues/100
https://github.com/paritytech/parity-signer/issues/101
https://github.com/paritytech/parity-signer/issues/106
https://github.com/paritytech/parity-signer/issues/107
https://github.com/paritytech/parity-signer/issues/108

**Comment by fckt** [comment]
would be nice if we'll have a "back button" on some screens.. How do you think, @bnvk ?

**Comment by debris** [comment]
maybe parity logo and label should be displayed only on top-level screens and when you go deeper they are replaced with a back button?

**Comment by fckt** [comment]
I need a screen for "Signed transaction QR" also

**Comment by bnvk** [comment]
> would be nice if we'll have a "back button" on some screens.. How do you think, @bnvk ?

We could do that. My only hestitence (and why I left it just the logo) is that when you start cross compiling for both iOS and Android UI conventions are a bit tricky to feel "native" to both OS types.

If you would like me to re-do my designs with this taken into account, I will!

### Signing Tranactions

<img src="https://user-images.githubusercontent.com/48677/39825348-dec251a0-53b1-11e8-85ed-85646a4ded3b.png" width="350">

### Signing Messages

How does something like this look? Is the reality that it will be showing JSON or is actual readable text?

<img src="https://user-images.githubusercontent.com/48677/39825402-00d50724-53b2-11e8-91ba-83a32378afb2.png" width="350">

**Comment by fckt** [comment]
> We could do that. My only hestitence (and why I left it just the logo) is that when you start cross compiling for both iOS and Android UI conventions are a bit tricky to feel "native" to both OS types.

yeah, I think we could do the trick in iOS only and leave it for Android as it is.

**Comment by fckt** [comment]
> maybe parity logo and label should be displayed only on top-level screens and when you go deeper they are replaced with a back button?

that's how it looks for now

![image 2018-05-14 20 43 14](https://user-images.githubusercontent.com/547167/40013831-6cf91bc6-57b7-11e8-8454-decaf9bf06b9.jpg)

**Comment by fckt** [comment]
Should we buy [Manifold CF](https://creativemarket.com/connary/84642-Manifold-CF-hard-working-sans-serif)? :)

**Comment by bnvk** [comment]
> Should we buy Manifold CF? :)

I also say definitely. 

However, due to previous experience with including a font that claimed to be "100% free and open source", which it was, I was unable to include the font in my project because it was *open source* and the usually otherwise "free" font license did not allow for "redistribution". 

That said, purchasing a license, it *should* be possible to bundle this font in the app at build time so long as the font is not committed to the repo. I can investigate this more if you like!

**Comment by bnvk** [comment]
Alternatively, I can look for a font that feels as similar as possible that allows for open source re-distribution.
