### ISSUE TITLE
Android - Prevent screen from going off when scanning

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#1041]
Scanning Metadata takes a while, a lot longer than the automatic screen sleep timer (prob 30s to 1min depending on users).
Generally, I expect users to place their phone in front of their screen, and leave it there rather than holding it for several minutes.

Because of this, it would be great if we you had the ability to prevent the phone to turn into sleep mode, and in the same time, keep the QR reading on.

**Comment by Slesarew** [comment]
TODO: ios

**Comment by Tbaut** [comment]
I built an apk from master a couple days ago and this issue is not solved, tried on Android 7 and 12.

**Comment by montekki** [comment]
Cc @Dmitry-Borodin

**Comment by Dmitry-Borodin** [comment]
This was fixed in November 2022, forget to reference this issue
cc @Tbaut
