### ISSUE TITLE
Android - Force close - Can't sign anything with a derived account on Acala

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#1043]
How to reproduce:
- create a test account on Signer
- create a derived account (I used `//some/derivation`)
- add Acala network and metadata
- add Signer account to the pjs extension (somehow it's recognized as a polkadot account see next step)
- change the account to be linked either to Acala, or "for any chain"
- go to pjs/apps and connect to Acala network: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Facala-rpc-0.aca-api.network#/accounts
- try to sign a dummy TX such as a transfer of 0 ACA to anywhere
--> Signer crashes

I've tested the same on Westend without any issue.

Signing Acala extrinsics with a root account works well too, it only fails for derived accounts.

**Comment by varovainen** [comment]
Do you add Signer account to pjs via QR code?
If it recognizes it as polkadot, it likely means QR code contains polkadot genesis hash, which is weird. 
Can you check the network specs for Acala you have on Signer: what is the genesis hash there?

**Comment by Tbaut** [comment]
Thanks for your answer, you made me look deeper and actually find the issue, see below.

> Do you add Signer account to pjs via QR code?
yes.
> Can you check the network specs for Acala you have on Signer: what is the genesis hash there?
it's 0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c and again, signing things on Acala is fine with the root account.

I realized that derived accounts are actually mapped to a network, Polkadot being the default one. I selected Acala network under the root account (it created automatically a `//acala` that I'm not interrested in), and derived my account from here. Now it works.

So the problem is that Signer force closes when presented with an extrinsic for a derived account, for a network different than the one it's attached to.

**Comment by varovainen** [comment]
Cool. I want to try reproduce the crash itself. The Signer is supposed in this case to show an error that you don't have an account for which the transaction is made.
---
So, checked it myself. Few things:
1. polkadot-js really allows to add account for wrong network; I've added an account in acala into westend. That's clearly wrong, but not exactly related to the issue.
2. When trying to sign transaction by derived key (`//some/derivation` made in acala only) in the westend network, on iOS I get an error `Public key is on record, but not associated with the network used`, as expected. Same on Android (dev version, with no jsons - jsons are a usual suspect). Do you get an error or is it a real crash?

**Comment by Tbaut** [comment]
1. If I understand your point correctly, then your assumptions don't match with the real world need. We should forget about the fact that one account can only be used on one network. Here is an example where you need several networks for 1 account: When you participate in a crowdloans, it's on polkadot relay chain. When you claim the parachain tokens, with the same account, it's on a parachain. You MUST be able to use the same account. I added this feature very early on in Stylo because of this. It would be great if Signer was agnostic to the network, and would only use it for display purposes (to show the right address).

2. I have had this error displayed in the past. I am talking about a real crash, an android force close.

I'm using v0.5.1, I will build the dev version in the next days and let you know if I can reproduce.

**Comment by Slesarew** [comment]
There is clearly a bug in pjs that allows cross-chain import of accounts. It is negated by use of signer companion at least, but I suppose it still should be fixed.

We are never forbidding re-use of a key in several networks. Indeed, we only require users to express explicit intent to do so.

**Comment by Slesarew** [comment]
should be fixed in #999

**Comment by Tbaut** [comment]
I think I don't understand your point about the bug in pjs. What do you mean by "add an account with the wrong network"?
Note that I am talking about the extension, not apps.

**Comment by Slesarew** [comment]
aren't they using the same js component?

**Comment by Slesarew** [comment]
Confirmed, it reproduces on master and is fixed in ongoing work PR.

**Comment by Slesarew** [comment]
> Not sure if it's related or it's another issue but I can't sign anything on Sora (after adding it and it's metadata), app crashes upon scanning QR code. The difference with OP's issue is that I'm using root account.

This is clearly different issue. Investigating. Sora is an interesting network, always brings issues - and still uses old metadata version, which might be the root of problem.
