### ISSUE TITLE
[new ui] new sign transaction screens

### ISSUE THREAD

**Issue by bnvk** [paritytech/parity-signer#106]
Creating a separate issue to track these specific "Signing" views

### Signing Transactions

<img src="https://user-images.githubusercontent.com/48677/40313010-b3c16b96-5d14-11e8-98a3-9964d4049a7f.png" width="350">

### Signing Messages

How does something like this look? Is the reality that it will be showing JSON or is actual readable text?

<img src="https://user-images.githubusercontent.com/48677/39825402-00d50724-53b2-11e8-91ba-83a32378afb2.png" width="350">

**Comment by fckt** [comment]
@bnvk I like your decision to use the same card view for both "FROM ACCOUNT" and "RECEIVER". 👍

>  Is the reality that it will be showing JSON or is actual readable text?

I think we could add a "show raw" button to show the raw message.

**Comment by fckt** [comment]
Only one thing misses: the screen which is following after click on "Sing Transaction/Message". There should be a QR code of the signed message/transaction

**Comment by bnvk** [comment]
<img src="https://user-images.githubusercontent.com/48677/40309405-a669c426-5d09-11e8-9c18-5d0190c97870.png" width="350">

<img src="https://user-images.githubusercontent.com/48677/40309406-a68d4acc-5d09-11e8-9e57-ab2f4de10adc.png" width="350">

**Comment by bnvk** [comment]
Just to clarify, upon a user scanning the transaction on other device and clicking `Done Scanning` button, the user is directed to the corresponding `Transaction Detail` views seen in #101

**Comment by fckt** [comment]
> <img src="https://user-images.githubusercontent.com/48677/40312700-de3161fc-5d13-11e8-9600-cb39346a5673.png" width="350">

I'm not quite sure that such a small QR image will be easy to read for limited-dpi devices (screen or camera)..

**Comment by debris** [comment]
maybe zoom-in on press?

**Comment by fckt** [comment]
> maybe zoom-in on press?
that could work
