### ISSUE TITLE
Simplify `MSeedKeyCard`

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#1061]
`Address` should not have `multiselect` key. `MSeedKeyCard` should probably have fields `address` and `mode`.
enum Mode {
    Plain,
    Swiped(..),
    Multiselect(..),
}
`swiped` and `multiselect` exclude each other and if we go for proper types, those bools that were for json simplicity only are no longer needed. This can wait for later, as now the whole thing works properly.

_Originally posted by @varovainen in https://github.com/paritytech/parity-signer/pull/999#discussion_r884760469_

**Comment by prybalko** [comment]
Fixed in https://github.com/paritytech/parity-signer/pull/1363
