### ISSUE TITLE
[new ui] getting started screen

### ISSUE THREAD

**Issue by bnvk** [paritytech/parity-signer#108]
Upon loading the app for the first time, or clicking on the `Add Account` button seen in #96 a user should be taken to this screen which gives them the option for a `New Account` which goes to #98 or to the `Recover Account` in #107

<img src="https://user-images.githubusercontent.com/48677/39827381-0ee485e6-53b8-11e8-9e8f-0dcc31f2b5c6.png" width="350">

**Comment by fckt** [comment]
Where "About Accounts" lead to?

**Comment by bnvk** [comment]
This is a view that needs to be created. I was not planning to do a design screen for it, but it would be mostly text content and links. I can create what I was thinking and just commit it to the codebase once you make a view file for it.
