### ISSUE TITLE
chainID missing in QR code to sign 

### ISSUE THREAD

**Issue by ligi** [paritytech/parity-signer#109]
I am not 100% sure if this is a problem in the parity signer or mycrypto - but last time myCrypto send me here as they just use what you give them  - so this time I am directly opening this here.
In the QR-code with JSON to sign I am missing the chainID - this cannot be extracted from the unsigned transaction RLP. Really wonder how you do that currently - are you always signing with chainID=1 or don't you use EIP155? I am a bit puzzled about this..-)

**Comment by debris** [comment]
iirc, chainID is appended to the end of unsigned transaction rlp. After user confirms signing transaction, the whole rlp is being singed, including chainID. So it's not a problem with parity-signer ;)

**Comment by ligi** [comment]
Hm - usually the chainID is not part of the unsigned transaction RLP - it is only part of the signed transaction in the case of replay protected EIP-155 signing (https://eips.ethereum.org/EIPS/eip-155) - can you please check?

**Comment by debris** [comment]
It is in parity. 

We prepare unsigned transaciton rlp in parity here:

https://github.com/paritytech/parity/blob/28c731881f2da0ceca4752dbcc1a8f9ad041f988/ethcore/transaction/src/transaction.rs#L119-L133

Then mobile signer hashes it:

https://github.com/paritytech/parity-signer/blob/b3893a71f6f185e5e777647d46f4b24de6293e9d/src/actions/scanner.js#L97-L104

And signes it:

https://github.com/paritytech/parity-signer/blob/ff9294b724a3b0ceebf51ba600493a99e620dba9/rust/signer/src/lib.rs#L101-L106

**Comment by ligi** [comment]
so you are not doing EIP155?

**Comment by maciejhirsz** [comment]
It is following EIP155 afaik. On MyCrypto side it's doing exactly what EIP155 prescribes (setting chainID as `v`, zeroing `r` and `s`):

https://github.com/MyCryptoHQ/MyCrypto/blob/1e9fe1b394356a040b11b927818cbc719ae90bce/common/utils/helpers.ts#L47-L50

**Comment by ligi** [comment]
Ah thanks - also this was the part of EIP155 I was searchign for there: https://github.com/MyCryptoHQ/MyCrypto/blob/1e9fe1b394356a040b11b927818cbc719ae90bce/common/utils/helpers.ts#L69
