### ISSUE TITLE
Add Bitcoin support

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#111]
The idea which is in the air, I guess..

**Comment by maciejhirsz** [comment]
I suppose we can do it, the curve is the same. Two UX challenges coming to mind immediately:

- Need support for BIP39 phrases on top of Parity phrases.
- Will need separate QR codes for ETH and BTC addresses when displaying the account.

**Comment by fckt** [comment]
yeah, these challenges are purely technical, doable. The hardest problem would be achieve support from the Bitcoin ecosystem, I guess..

**Comment by bnvk** [comment]
As one who uses BTC more than ETH, I would very much like to see this. Bitcoin was one of the initial features/goals when I was first asked to do design on the app that was planned. 

> The hardest problem would be achieve support from the Bitcoin ecosystem, I guess..

I have connections to some BTC projects and I'm happy to push for integration + support of Parity Signer should Bitcoin be added.

**Comment by ianpurton** [comment]
There is a technical hurdle to Bitocin adoption. Bitcoin transactions can be very large. A bitcoin transaction can have many inputs that all need to be signed. Typically this is one or 2, but there are sometimes users who are trying to spend over 200 inputs.

So this will most likely no be doable via QR code.

There are some research projects around data transfer using qr codes. i.e. line of sight wireless. https://seiferteric.com/?p=356

To give you an idea I've been trying to solve the same issue for multi signature signing. https://github.com/carbonwallet/CarbonKey

I'd be happy to collaborate on getting Parity signer to sign for Bitcoin and can also supply resources.

**Comment by Tbaut** [comment]
Closing as we will not realistically do this in the mid term.
