### ISSUE TITLE
Derive key from previously derived key

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#1117]
This feature was implemented in early prototype of 5.0.0 and users want it back; It's still available in backend so I really need UI design for it.

How it should work: on keys manager screen, user does something to one of keys and ends up on derivation screen with derivation field pre-filled with the path of that chosen key

**Comment by krodak** [comment]
I think we consciously removed this feature from roadmap, correct me if I'm wrong @tetekinandrey.

Closing for now until we put it on the roadmap or get users feedback that this is needed with new UI for v6.0 builds
