### ISSUE TITLE
undefined is not an object(evaluating '_NativeModules.EthkeyBridge.randomPhrase')

### ISSUE THREAD

**Issue by a186r** [paritytech/parity-signer#115]
when i click Add ,got an error `undefined is not an object(evaluating '_NativeModules.EthkeyBridge.randomPhrase')`

**Comment by Tbaut** [comment]
Thanks for the report, more background on what happened before/after would be great.
The app is currently being redesigned. This problem will most likely get fixed.

**Comment by fckt** [comment]
Android or iOS?
If Android `yarn run build-rust-android"` must be run first

**Comment by a186r** [comment]
@Tbaut @fckt thanks for your support,i will try again and wait new design
