### ISSUE TITLE
Make sure plain private key is erased in memory on locking

### ISSUE THREAD

**Issue by chain-police** [paritytech/parity-signer#116]
Because JS has a garbage collector which manages memory we have no control whether/when GC will erase plain private key after unlock.
The solution could be couple the decryption of `encryptedSeed` with the native `sign` function (which called `brainWalletSign` now and takes the plain seed) and make sure to override used private key (seed) with zeroes.

cc @debris

**Comment by maciejhirsz** [comment]
Yeah, I want to make sure all secrets are wrapped in [`Protected`](https://github.com/tomusdrw/ethsign/blob/master/src/protected.rs), and only handled in the bindings through reference.

**Comment by hanwencheng** [comment]
Implemented, now Rust runtime box the private key, in JS runtime only store the pointer, each time the account get locked, the private key in memory is erased.
