### ISSUE TITLE
Add metadata for parachains

### ISSUE THREAD

**Issue by keeganquigley** [paritytech/parity-signer#1177]
Hi all, are there any plans to add more parachains in which the metadata is officially signed by Parity?

Support has some users asking if various parachains are supported. I have given them the necessary [instructions](https://paritytech.github.io/parity-signer/tutorials/Add-New-Network.html) for adding a network, but adding chain specs that are signed by a different source than the one currently in Signer (Parity) cause everything on Signer to be deleted. Wondering if more officially signed chains can be added in the future.

**Comment by pgolovkin** [comment]
You can find Parachains metadata in the [Novasama technologies metadata portal](https://nova-wallet.github.io/metadata-portal/#/acala)
