### ISSUE TITLE
Provide APK release for fully offline install

### ISSUE THREAD

**Issue by AronVanAmmers** [paritytech/parity-signer#118]
Cool tool! I'm wondering why you don't provide APK download here as GitHub releases so users don't need to go through Google Play? That way one could keep the phone completely offline (wipe phone, put parity-signer APK on an SD card, insert SD card and install).

**Comment by Tbaut** [comment]
Cheers! The APK will be provided (on F-droid for instance) for a later release: https://github.com/paritytech/parity-signer/issues/80

**Comment by AronVanAmmers** [comment]
Sweet, thanks @Tbaut
