### ISSUE TITLE
Allow to edit scanned TX details before signing. Include the transaction data itself into the resulting QR (besides of a signature).

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#119]
Disclaimer: the following proposal doesn't touch the current default interaction (UX) described there https://wiki.parity.io/Parity-Signer-Mobile-App-MyCrypto-tutorial .

Concretely, the idea is to include the transaction itself, but not only signature into the QR on the following screen:
<img src="https://user-images.githubusercontent.com/48677/40312700-de3161fc-5d13-11e8-9600-cb39346a5673.png" width="350">

For today transaction to be signed is maintained by MyCrypto. It means that first the message being composed online and then Signer reads the QR code of the message, signs it and shows the QR with a signature.

<img src="https://user-images.githubusercontent.com/48677/40313010-b3c16b96-5d14-11e8-98a3-9964d4049a7f.png" width="350">

For now it's not possible to "tap on to edit amounts" (see the mockup above), as the resulting QR contains only the signature for the transaction on the MyCrypto side.

Adding transaction itself in the resulting QR will extend the amount of the usage scenarios and applications (which would lead to a better adoption I guess). That allows to create a transaction on the device and only show a result to the online service: MyCrypto or simple PushTx services of various blockchain explorers such as https://etherscan.io/pushTx or https://www.blockchain.com/en/btc/pushtx (if (when) we will support Bitcoin). Currently these services doesn't support QR scanning but it's not a problem to scan QR with something like https://webqr.com and then copy and paste into the form on "pushTx" service and than submit.

**Comment by Tbaut** [comment]
We would like to (medium term) add the functionality to Fether. This could be a nice way to push adoption also.

**Comment by fckt** [comment]
One of the challenges with implementation of the issue is a `nonce` sync (especially if we want to allow user to change the sender of the TX). What I think we can do about is the to introduce the following mechanics:

1. Maintain the nonces for the accounts;
2. In case if signed TX contains nonce which is out of sync (which could be checked easily on the final MyCrypto step), propose to re-sign the transaction with the correct nonce, proposed by the MyCrypto (via QR scanning).

**Comment by Tbaut** [comment]
closing as it won't be done any time soon.
