### ISSUE TITLE
Test builds for iOS devices

### ISSUE THREAD

**Issue by montekki** [paritytech/parity-signer#1207]
It would be nice if CI could offer iOS builds for internal testing purposes

**Comment by krodak** [comment]
@montekki what Parity was using for that until now?
Best practice would be to distribute test builds via TestFlight, [Fastlane](https://fastlane.tools) is currently the best to setup CI / CD pipelines for iOS projects and it can be integrated with GA and other CIs.

That's one of the reason I was asking for Apple Developer Program access, as without that I won't be able to start integration on this one 🙏🏻 
cc @vas3k regarding Apple Developer Program access and maybe info on how process looked so far

**Comment by montekki** [comment]
>  what Parity was using for that until now?

Nothing afaik, I added the android atrifacts to builds some time before

**Comment by krodak** [comment]
Resolved by https://github.com/paritytech/parity-signer/pull/1218
