### ISSUE TITLE
Advanced device capabilities detection

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#121]
For now we detect if device has a network connection.
There is an idea to detect also:
- bluetooth capabilities
- NFC capabilities
- USB connection
- others

If we detect any of these connections/capabilities we consider "the device is not offline wallet".

#### Implementation points
There is a lib for each capability, but I did not find a lib which just device capabilities. So I'd prefer to write such a lib. 

Also there should be an Android service which will be able to make checks even if app is not open.

**Comment by fckt** [comment]
We decided to implement only those capability detections, which are not require additional permissions from user.

**Comment by Tbaut** [comment]
This question is answered if I'm not mistaken. We do not wish to add any additional permission and will therefore not implement any of these.
