### ISSUE TITLE
Localizable baseline setup for Android

### ISSUE THREAD

**Issue by krodak** [paritytech/parity-signer#1210]
## Purpose
We should provide baseline support for localization within Android application.

## Scope 
- remove inline hardcoded strings
- `strings.xml` file to store localizable strings

## Resources
iOS localizable setup: https://github.com/paritytech/parity-signer/pull/1209

**Comment by Dmitry-Borodin** [comment]
General setup is there and all redesigned screens is localizable (strings.xml & plurals.xml)
I'm not sure if we need to keep this issue open, should we @krodak? 

I would create one to actually setup a way for community to be able to provide localized strings for different languages.
Something like https://hosted.weblate.org/projects/osmand/
