### ISSUE TITLE
Intrusive permissions?

### ISSUE THREAD

**Issue by GustavMarwin** [paritytech/parity-signer#122]
What's with the identity permissions, what purpose does it serves?

![signal-attachment-2018-07-10-141100](https://user-images.githubusercontent.com/37633593/42532045-3fee992e-844b-11e8-9f43-18a59836c672.png)

**Comment by fckt** [comment]
@debris 
btw, in the upcoming release we have the "device capabilities check" feature. There is obvious conflict there: how we're going to detect capabilities in the app which doesn't have permissions for?

**Comment by ligi** [comment]
you can use runtime permissions.

**Comment by debris** [comment]
> btw, in the upcoming release we have the "device capabilities check" feature. There is obvious conflict there: how we're going to detect capabilities in the app which doesn't have permissions for?

Is this feature critical? Personally I never give apps an access to the capabilities if I can't see clearly how are they used

**Comment by fckt** [comment]
That's one of the new features in new design.. I'd like to invite @maciejhirsz and @bjornwgnr in conversation

**Comment by bjornwgnr** [comment]
> Personally I never give apps an access to the capabilities if I can't see clearly how are they used

Same here.

>Personally I'd prefer to remove this feature. Among other things we'll have to write our "check capabilities" module if we don't want to bring a lot of foreign code into the build (#121).

IMO the trade offs are not worth the feature.

**Comment by ligi** [comment]
You are discussing something here that is not worth discussing IMHO - you will need to implement runtime permissions anyway (e.g. because of this : https://developer.android.com/distribute/best-practices/develop/target-sdk ) - with runtime permissions the discussion here is not really relevant anymore

**Comment by fckt** [comment]
> you can use runtime permissions.

It's not even discussed, surely, we're going to implement that.

**Comment by ligi** [comment]
If you are doing runtime permissions anyway than the issue exists only for devices with sdk-level 16..22 - if you really want to care for them you could split this feature in a flavor. This might help you decide if you want to care for 16..22 : https://developer.android.com/about/dashboards/

**Comment by fckt** [comment]
yeah, obviously, in the Signer we want to support the widest possible device range. So it might be useful, thanks for the link!

**Comment by Tbaut** [comment]
The new release only requests:
- take picture
- phone's status and identity <-- we need to figure out if this can be avoided.
