### ISSUE TITLE
Older phones freeze for a couple seconds on account creation screen

### ISSUE THREAD

**Issue by debris** [paritytech/parity-signer#125]
Identicon generation takes some time. On slower devices it takes more time than displaying the screen, which causes the entire content of the screen to shift down 0.1 second after the screen is loaded.

Identicon should have a temporary image of the same size as a generated one. It should fill the identicon until the generation is done

**Comment by fckt** [comment]
Good point!
There is another problem. On slow android device, images generation (which should run on native modules thread) seems to freeze the JS thread for some reason..

**Comment by Tbaut** [comment]
Should be better now with BIP39
