### ISSUE TITLE
No recovery words on Backup Account screen

### ISSUE THREAD

**Issue by debris** [paritytech/parity-signer#127]
<img width="503" alt="screen shot 2018-08-06 at 13 23 46" src="https://user-images.githubusercontent.com/2613714/43715673-90aeea8a-9981-11e8-9ef0-4f2a2924eb67.png">

**Comment by debris** [comment]
it happened for me once, when I started the app in a simulator, which had no accounts before

**Comment by fckt** [comment]
Haven't seen this before. Need more info on how to reproduce this..

**Comment by debris** [comment]
Happened once on the new account creation (nothing sophisticated). Hasn't happened since

**Comment by fckt** [comment]
btw, in fact the address (`00a329c0648769A73afAc7F9381E08FB43dBEA72`) itself is corresponding to the empty seed 🙂

**Comment by debris** [comment]
hmm... But i'm pretty sure I was not recovering from an empty account... Or was I? I'm not sure right now. But can we forbid people from recovering from empty seed? It's dangerous :)

**Comment by fckt** [comment]
https://github.com/paritytech/parity-signer/commit/1f814a6da99fba912880e9ee8c324423e529a950
should be fix

**Comment by ltfschoen** [comment]
I've been using the same "Samsung Galaxy 8 Note" with the same Parity Sign v2.0 beta. Everything was working a couple of days ago on the same mobile, until today.

Now when I try to create a new account on any network in Parity Signer it doesn't show any Recovery Words anymore when I get to the page that suggests the user to back them up, the area is blank as shown in the screenshot below. I tried restarting Parity Signer and restarting the mobile phone but the problem still persists. I haven't tried reinstalling Parity Signer yet (as I'd probably have to add all the accounts again).

<img src="https://user-images.githubusercontent.com/6226175/51170815-76308b80-1903-11e9-996a-6ff1a8abd616.jpg" width="300" height="600" />

**Comment by ltfschoen** [comment]
Instead of re-installing Parity Signer on my Samsung Galaxy 8 Note (to avoid having to recover all the accounts that I added), I decided to make a fresh installation of Parity Signer v2.0-beta on a friends iPhone 8 Plus. After installation I clicked "Create New Account", then left the default network "Ethereum", entered a random account name, and clicked "Next Step", and then it showed the same "Recovery Words" section that was blank as shown below

![20190115_234028](https://user-images.githubusercontent.com/6226175/51181620-bbfb4d00-191f-11e9-8eb3-1fd7e7cf1af5.jpg)

**Comment by fckt** [comment]
You're crated an account with an empty seed (read https://github.com/paritytech/parity-signer/issues/127#issuecomment-411050022).. It's possible to create one in Signer, but there will be a `Warning` on a creating process.

**Comment by fckt** [comment]
> After installation I clicked "Create New Account", then left the default network "Ethereum", entered a random account name, and clicked "Next Step", and then it showed the same "Recovery Words" section that was blank as shown below

this is weird indeed. Shouldn't work like that, I'll check

**Comment by Tbaut** [comment]
Nice one @ltfschoen thanks.
No account has been selected by default. We need to fix this as part of https://github.com/paritytech/parity-signer/issues/154

**Comment by ltfschoen** [comment]
when there was no "Warning". whenever i create a new account now on either the Samsung or iPhone, regardless of what network I associate with it, it always has the same address "00a329c0648769A73afAc7F9381E08FB43dBEA72", and there is no "Warning" to ask me if I want to create an account with an empty seed (why would a user want to do that?), and the created account never has any recovery words. After creating the account if I click it's account card, and then click "Manage/Backup Account", and click the input field of the PIN, then on the Samsung the keyboard appears and I can enter my 6-digit pin and click "Next" but nothing happens, or if I do the same thing on my iPhone the keyboard also appears and I can enter my 6-digit pin, but there is no "Next" button

See screenshots below:

![20190116_005748](https://user-images.githubusercontent.com/6226175/51186674-4480ea00-192e-11e9-8670-f468f66447b7.jpg)
![screenshot_20190116-005735_parity signer](https://user-images.githubusercontent.com/6226175/51186675-4480ea00-192e-11e9-9dc4-274364412aad.jpg)
![screenshot_20190116-005740_parity signer](https://user-images.githubusercontent.com/6226175/51186676-45198080-192e-11e9-9aaa-20215e27380a.jpg)

**Comment by fckt** [comment]
@ltfschoen please, can you explain, why you need to unlock an "empty seed" account?

**Comment by ltfschoen** [comment]
> > "00a329c0648769A73afAc7F9381E08FB43dBEA72", and there is no "Warning" to ask me if I want to create an account with an empty seed (why would a user want to do that?), and the created account never has any recovery words. After creating the account if I click it's account card, and then click "Manage/Backup Account", and click the input field of the PIN, then on the Samsung the keyboard appears and I can enter my 6-digit pin and click "Next" but nothing happens, or if I do the same thing on my iPhone the keyboard also appears and I can enter my 6-digit pin, but there is no "Next" button
> 
> @ltfschoen please, can you explain, why you need to unlock an "empty seed" account?

Because I'm a new user who was not warned that I'd been allocated with an "empty seed" account.
 When I tried to remove the account, even though it's an "empty seed" account, it still navigated me to the "Unlock Account" screen and prompted me to enter the PIN that I nominated when I created the account. Why does it navigate the user to the "Unlock Account" page when the user has been allocated with an "empty seed" account?

**Comment by Tbaut** [comment]
You found a pattern that we didn't realize existed back then. As I said it's a totally valid bug that we'll address.

**Comment by ltfschoen** [comment]
Here's a summary of issues I encountered

**Use Case 1: New Parity Signer use on an iPhone**

* I installed Parity Signer v2.0-beta on 15 Jan 2019 that was downloaded from the App Store onto an iPhone 8 Plus.
* When I click "Create New Account" and **I choose ANY network (i.e. if I choose "Ethereum", "Ethereum Classic", "Ropsten", or "Kovan"**, then it only creates the "empty seed" account with address "0x00a329c0648769A73afAc7F9381E08FB43dBEA72" each time I try to create an account. It does not include any Recovery Words, and I cannot delete the account. 
* I tried uninstalling and reinstalling Parity Signer again to try and delete the "empty seed" accounts that I created, but when it restarted and I clicked the "Accounts" tab the "empty seed" accounts were still there.
* If I create an account again on the same network as I created an "empty seed" account before, it generates an "empty seed" account with the same address "0x00a329c0648769A73afAc7F9381E08FB43dBEA72", but I can change the account name and PIN, and it just overwrites the previous account that I created that is shown on the account list page.

**Use Case 2: Existing Parity Signer user on a Samsung**
* I had previously installed Parity Signer v2.0-beta on a Samsung 8 Note when it was first released that I downloaded from the Playstore.
* Previously I was able to create **non-**"Kovan" network accounts that **would not be** "empty seed" accounts (until yesterday 15 Jan 2019), and they came with Recovery Words, and I can still use those accounts on my device normally.
* However if I try to create a new account now, I experience the same behaviour as the iPhone 8 Plus user mentioned above. Only **very rarely** does it create a non-"empty seed" account.
* If after creating an "empty seed" account on the "Kovan" network I try to import it into Fether using its QR code with the "Recover from Parity Signer" option, it prompts me to enter an account name but it does not display the account on the account list.

**Questions**

1) Should we prevent Parity Signer from generating any "empty seed" accounts?

2) How does a user delete an "empty seed" account from Parity Signer on a device? It still displays them after uninstalling and reinstalling Parity Signer. And when you try to access the "Manage / Backup Account" page it doesn't seem to recognise the PIN on the "Unlock Account" page, so the "Delete Account" button cannot be accessed.

3) Should we update Fether to prevent a user from importing an "empty seed" account using "Recover from Parity Signer" or "Recover from Seed Phrase" and show a notification like "Accounts with an empty seed phrase are not permitted"?

**Comment by Tbaut** [comment]
> Should we prevent Parity Signer from generating any "empty seed" accounts?

Yes (that in the description #154)

> How does a user delete an "empty seed" account from Parity Signer on a device?

It's a bug, for some reason the account isn't found, also you can't sign anything with this account. We need to take a look at it (and allow it for older accounts that got created this way), I created https://github.com/paritytech/parity-signer/issues/203

> Should we update Fether to prevent a user from importing an "empty seed"

I don't think it's worth it, this is a Signer problem, updating Fether won't change anything.

**Comment by fckt** [comment]
> Because I'm a new user who was not warned that I'd been allocated with an "empty seed" account.

That's a bug with an account IDENTICON selection on the first step, nothing more. It's a ridiculously easy bug to fix. Seems like it's a React Native bug, I'm sure there is a workaround. 

Thank you for your efforts on the issue description, though!

**Comment by fckt** [comment]
> Should we prevent Parity Signer from generating any "empty seed" accounts?

As @Tbaut rightly said, it's not related to Fether (in any way). Fether knows nothing about seeds, Fether uses an address only (when it uses an account from Parity Signer).

**Comment by ltfschoen** [comment]
> > Because I'm a new user who was not warned that I'd been allocated with an "empty seed" account.
> 
> That's a bug with an account IDENTICON selection on the first step, nothing more. It's a ridiculously easy bug to fix. Seems like it's a React Native bug, I'm sure there is a workaround.
> 
> Thank you for your efforts on the issue description, though!

Yes you're correct. the bug occurred because I didn't follow the instructions in the "CHOOSE AN IDENTICON" section on the first page of "CREATE ACCOUNT, where it explicitly instructs us to "Select an identicon". I was rushing through creating the account each time and just thought it would automatically choose an identicon for me. And there **doesn't appear to be any form validation** on the first page so the user can click the "Next Step" without even having completed any of the form fields at all, which generates a "no name" account with the "0x00a329....." address and no recovery words.

So it does look like it's an easy fix of just adding form validation and user notifications.

**Comment by ltfschoen** [comment]
I just had a look at the code and it looks like Lines 130-131 should be:
```
selected &&
selected.chainId && selected.chainId.length &&
selected.seed && selected.seed.length &&
selected.address && selected.address.length &&
selected.name && selected.name.length &&
...
```
https://github.com/paritytech/parity-signer/blob/master/src/screens/AccountNew.js#L131
