### ISSUE TITLE
Addresses of accounts are not checksummed

### ISSUE THREAD

**Issue by debris** [paritytech/parity-signer#128]
![image](https://user-images.githubusercontent.com/2613714/43715776-f53d34e8-9981-11e8-964d-58d451813e27.png)

it should be `0x006E27B6A72E1f34C626762F3C4761547Aff1421`

**Comment by fckt** [comment]
Addresses for accounts which was created in older versions of Signer 2.0 are saved in lowercase, unfortunately.

**Comment by debris** [comment]
works now
