### ISSUE TITLE
Bad input data. Only substrate transactions are supported.

### ISSUE THREAD

**Issue by GalioColossus** [paritytech/parity-signer#1319]
I been using the parity signer 5.0.1 for a month already then after 3 week I tried to use it again but I got this error when I tried to sign a transaction 
```
Bad input data. Only substrate transactions are supported. Transaction is expected to start with with 0x53, this one start with 0x3c
```
Any idea why?

**Comment by ccfiel** [comment]
Any updates?

**Comment by montekki** [comment]
Hey can you please describe your setup:

1. Network
2. What are you using with signer (polkadot.js extension?)

**Comment by prybalko** [comment]
I'm going to close this one due to inactivity. 
If the problem comes up again, feel free to reopen the issue.
