### ISSUE TITLE
Unable to update metadata

### ISSUE THREAD

**Issue by jonasW3F** [paritytech/parity-signer#1342]
I set up an older phone (Sony Xperia Z5) with Parity Signer. When trying to scan the QR-video, simply nothing is happening. Tried it from various angles for quite some time. I also opened the QR-video in a separate tab that puts the video onto a black background. My guess is that the camera might be incompatible, but on the other hand it is not that bad (23MP).

![IMG_20221008_130039](https://user-images.githubusercontent.com/67730419/194705123-12e01239-020e-401f-bd06-bceca48774a7.jpg)

The QR-video appears to be rather clear on screen and scanning static QR codes work perfectly.

Edit: I used a QR-scanner app in batch mode and it appears that it can read data. But it does not work very good, it takes quite a while to find another image and the app constantly refocuses the lens. So I am thinking that parity signer not using focus is the problem?

**Comment by montekki** [comment]
Thanks for reporting! The app even looks wrong, it should not look like that on Android, Cc @Dmitry-Borodin

**Comment by Dmitry-Borodin** [comment]
I can confirm that view should not stay on a side and I just checked with fresh play store installation - at least on my devices it works.
I would wait a bit with this probably device-specific issue as I will refactor and reimplement scanning screen soon. This will probably fix this problem.

**Comment by Dmitry-Borodin** [comment]
After #1435 it make sense to check it out on master

**Comment by pgolovkin** [comment]
I tried the latest Android build from the `master` branch. The speed of metadata QR scanning for the Westend (275 frames) is extremely slow. It takes about 5 minutes to updated the metadata for the Westend. At the same time the latest Google Play release scans the same metadata in less then 1 minute.

**Comment by pgolovkin** [comment]
> 

I keep QR in the frame.

**Comment by Dmitry-Borodin** [comment]
issue related to #1436

**Comment by Dmitry-Borodin** [comment]
@pgolovkin could you check if #1713 approach improving your experience?

**Comment by Dmitry-Borodin** [comment]
Closing as no response, we will target this issue in general in #1436
