### ISSUE TITLE
Next button out of screen

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#1360]
I noticed this on a build from `master` from yesterday.
This is a on Pixel 3a 

the spacing at the top isn't ideal. The Next button is only partly visible, and I can't scroll to have the button in full.

![image](https://user-images.githubusercontent.com/33178835/195588657-2f459783-a345-478d-be48-323843c0e46d.png)

**Comment by Dmitry-Borodin** [comment]
Thank you. That is recent regression, will fix shortly
