### ISSUE TITLE
Create an About page

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#137]
Right now the About button does nothing. It should show:
- a brief description of what Parity Signer is with security advices (no network)
- talk about the rust code audit
- mention that there is no data gathering at all
- a link to the wiki
- a link to github
- "developped" by Parity Technologies
- the app version

@Tbaut to write it
@fckt to add it :)

- Fix https://github.com/paritytech/parity-signer/issues/124

**Comment by Tbaut** [comment]
# About

Parity Signer mobile application is a secure air-gapped wallet developed by Parity Technologies. It allows users to use a smartphone as a cold storage.

Any data transfer from or to the App will happen using QR code scanning. By doing so, the most sensitive piece of information, the private keys, will never leave the phone. The Parity Signer mobile app can be used to store any Ethereum account, this includes ETH, ETC as well as Ether from various testnets (Kovan, Ropsten…).

This app does not send any data to Parity Technologies or any partner. The app works entirely offline once installed.

The code of this application is available on Github (https://github.com/paritytech/parity-signer) and licenced under GNU General Public License v3.0.

The cryptographic library used by Parity Signer has been audited, the report is available at https://www.trailofbits.com/reports/parity.pdf. Although the most critical part of this app has been audited, bear in mind that the entirety of this application hasn't.

Find on Parity Signer wiki more information about this application as well as some tutorials: https://wiki.parity.io/Parity-Signer-Mobile-App.

-Parity Signer version XXX-

**Comment by rphmeier** [comment]
@Tbaut edited the about for a couple grammar/spelling issues
