### ISSUE TITLE
Authentication System Failure error

### ISSUE THREAD

**Issue by keeganquigley** [paritytech/parity-signer#1370]
A user has reported experiencing an "Authentication System Failure" error on following device:

Cellphone:
Samsung S8 – SM-G950F
Android 9

Airplane mode
security mode encription
Bluetooth, NFC disabled
Parity Signer (Public Beta): v5.0.1

Attempted solutions:
Close/re-open app
Reboot phone
Change PIN
Factory Reset

Here is a [reference](https://github.com/paritytech/parity-signer/blob/4bedb17f748fd8878a30ce394d13ef1d48cc9918/android/src/main/java/io/parity/signer/components/Authentication.kt#L110) to the error. Does anyone know of any compatibility issues or what could be causing this?

**Comment by gsanjaime** [comment]
Today have tried with 3 different android devices and the result the same
Did you test the app on android devices?
I am very frustrated, I don't find documentation, I don't get support. 
It seem thay the project no have interest

**Comment by Dmitry-Borodin** [comment]
Is screen lock enabled on this device? (pin/fingerprint et.c.)
Adding proper explanation that screen lock is required is planned soon as app onboarding flow.

**Comment by gsanjaime** [comment]
Yes I have screen lock with password

**Comment by gsanjaime** [comment]
I would like to work only with PIN.
Is there any way to avoid fingerprint?

**Comment by gsanjaime** [comment]
No, I never used fingerpint.

De: Keegan | W3F ***@***.***>
Enviado el: miércoles, 19 de octubre de 2022 16:50
Para: paritytech/parity-signer ***@***.***>
CC: gsanjaime ***@***.***>; Mention ***@***.***>
Asunto: Re: [paritytech/parity-signer] Authentication System Failure error (Issue #1370)


@gsanjaime<https://github.com/gsanjaime> Great! Thanks for letting us know. If you originally set the authentication with a fingerprint than it would make sense that you need it to unlock it.

**Comment by gsanjaime** [comment]
updating the metadata for each chain is a tedious task.
For each chain I need about 10 minutes.
Is there another way to make it faster?

**Comment by Tbaut** [comment]
Use a more recent device. It's less than a minute on a pixel 3a. It's the cost of security unfortunately. I'm also using a 5+ year old device and it's tedious indeed.

**Comment by gsanjaime** [comment]
Thanks Tbaut

Parity signer is intended only for Polkadot.js? or in the future will it also be integrated into other wallets? (Keplr, safepal, etc...)

**Comment by Tbaut** [comment]
I think we're diverging a lot from the original issue here, I'll answer but please ask any other question in a dedicated issue or on [Element](https://app.element.io/#/room/#watercooler:matrix.parity.io). Also note that I'm a contributor, not part of Parity any more.
Parity Signer supports Polkadot, Kusama and any substrate related chains, some of them very close to Ethereum (EVM based). It does not support any other ecosystem like Cosmos, Solana etc.. 

Any Polkadot related wallet can support Parity Signer. It's the case of Polkadot.js extension, [Subwallet](https://github.com/Koniverse/Subwallet-Extension), [Polkadot.js plus](https://github.com/PolkaGate/polkadot-Js-Plus-extension), and hopefully soon Talisman (they are not open source as of now unfortunately).

**Comment by Originalimoc** [comment]
It should not call the fingerprint sensor IMHO. Call standard Android Keystore/Authentication instead.
