### ISSUE TITLE
Remove the "Security" feature

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#138]
The security feature e.g. "your device is considered as not secure because it is connected to the internet" requires the app to ask for internet access which seems dubious for users.

As this feature isn't critical, we should remove it. A good warning and description are good enough to let users know that the device should not have access to internet once the app has been installed.

Fix: https://github.com/paritytech/parity-signer/issues/122

**Comment by fckt** [comment]
We decided to not remove the "Internet connection" check, because the is no need explicit user permission for the internet connection.
