### ISSUE TITLE
Encrypted seed? Is it? iOS/Android.

### ISSUE THREAD

**Issue by Originalimoc** [paritytech/parity-signer#1388]
It should not simply call the fingerprint/biometric sensor to do authentication IMHO.

Call the Android Keystore to get the ENCRYPTED SEED stored in /data/data which to be decrypted by a key(generated or manually set) stored in TEE and then load into memory only for that session instead. This way even though /data/data is leaked/accessed by another app/backed up by whatever brand Android cloud service, the seed is safe. Same apply to iOS.

Store plain-text seed is dangerous only exception is a device that's dedicated offline forever.

**Comment by krodak** [comment]
@Originalimoc on iOS side, we are storing seed using Keychain, setting access control to:

```
SecAccessControlCreateWithFlags(
            kCFAllocatorDefault,
            kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly,
            .devicePasscode,
            nil
        )
```
Meaning that this item (seed phrase) cannot be moved outside of device and it is additionally protected by `devicePasscode`, as we consider passcode more secure than biometric usage. 
On devices that have Secure Enclave feature on hardware level (which is actually all iOS 15 supported devices beside iPod Touch), `Keychain` storage is especially secure mean of storing data as it lives in dedicated subsystem. You can read more on it [here](https://support.apple.com/en-gb/guide/security/sec59b0b31ff/web). So only way to jeopardize your security model in this case is to use jailbroken device, but you'd be aware of that.

Do you have any more concerns to iOS side or improvements recommendations that you'd like to see?

**Comment by Dmitry-Borodin** [comment]
To be short Android doesn't store plain text seed (it's encrypted with system key) and Signer is meant to use offline forever. 
It is valid point to see if other apps can theoretically decrypt it and if it make sense to use some custom keys instead of system ones. We will think about those tradeoffs once again.
Anyhow it is decrypted in memory. So infected system with root access can find any secrets. That's why offline forver and separate device is always safer option.

**Comment by krodak** [comment]
@Originalimoc is there something more you wanted to inquire about or should we close this one?

**Comment by Originalimoc** [comment]
I'll see if I noticed something can be improved.
