### ISSUE TITLE
Update React Native to v0.59

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#140]
https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#059

**Comment by yjkimjunior** [comment]
Bump to 0.59.8, otherwise have to do this https://github.com/facebook/react-native/issues/23256#issuecomment-477331616 manually for building on iOS with Xcode v^10.2. 🙄

**Comment by Tbaut** [comment]
done https://github.com/paritytech/parity-signer/pull/246
