### ISSUE TITLE
[paritytech/rust-secp256k1] Failing to crosscompile (linux/osx) lax_der_parsing.c  

### ISSUE THREAD

**Issue by tucanae47** [paritytech/parity-signer#141]
Hey guys wondering about how to solve this problem, it seems some flags are not passed to android toolchain and its not able to continue, but i don't know how to solve it. 

After successful setup with

`setup_macos.sh` or `setup_linux.sh`

and then executing 

`make android`

i found this error 
```
cargo:warning=depend/secp256k1/contrib/lax_der_parsing.c:7:20: fatal error: 
string.h: No such file or directory
```
at this compiling stage:
```
aarch64-linux-android-gcc -O3 -ffunction-sections -fdata-sections -fPIC -I 
depend/secp256k1/ -I depend/secp256k1/include -I depend/secp256k1/src -I 
/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include 
-Wall -Wextra -g -DUSE_NUM_NONE=1 -DUSE_FIELD_INV_BUILTIN=1 -DUSE_SCALAR_INV_BUILTIN=1 
-DUSE_FIELD_10X26=1 -DUSE_SCALAR_8X32=1 -DUSE_ENDOMORPHISM=1 -
DENABLE_MODULE_ECDH=1 -DENABLE_MODULE_SCHNORR=1 -DENABLE_MODULE_RECOVERY=1 -
o /parity-signer/rust/rust-secp256k1/target/aarch64-linux-android/release/build/eth-secp256k1-
4180f7882dc6f0aa/out/depend/secp256k1/contrib/lax_der_parsing.o -c 
depend/secp256k1/contrib/lax_der_parsing.c
``` 

Im using: 
`rustup 1.11.0 (e751ff9f8 2018-02-13)`
`cargo 1.28.0 (96a2c7d16 2018-07-13)`
`rustc 1.28.0 (9634041f0 2018-07-30)`
`NDK 17.2`

**Comment by tucanae47** [comment]
It seems for newer ndk versions  you should use another [stl](https://developer.android.com/ndk/guides/standalone_toolchain#c_stl_support) and then [re]link it, but i didnt find how to do it fast. so i decided to use ndk13b as recommended by the authors.

**Comment by Tbaut** [comment]
Do you consider it as solved or is there any question you'd like to get an answer for?

**Comment by tucanae47** [comment]
Well would nice to know how to use newer ndk, but could be solved as well. :-)

**Comment by Tbaut** [comment]
cc @fckt when he'll be back from vacations, you'll have to be patient @tucanae47 :)
I'll close in the mean time.
