### ISSUE TITLE
The back button acts as a rewind and brings to unexpected screens

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#142]
On Android.

If you create an account (select network, name, enter a pin code twice and copy the seed phrase), then go to account to see the QR code for instance. 
Now tap the "back" button a couple times and you'll get back to the PIN configuration of the account etc.. 

The back button should instead get back to the account overview, and if tapped again ask to quick the app (or quit it without asking).

**Comment by fckt** [comment]
have you tested the build for iOS? @Tbaut
