### ISSUE TITLE
Show a loader when creating accounts/identicons

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#143]
On Android.
When creating a new account, the screen is frozen for a couple seconds because the device is busy to create some key pairs and the identicon (I guess).

My device is a couple years old, but it's definitely not a low end one.

A better UX would be to:
- Let the user the name and network type while showing a loader for account computation (in another thread)?
or, if we can't do anything better:
- Show a general loader blocking the user until the accounts are created. At least the user isn't stuck on a screen without being able to do anything

**Comment by debris** [comment]
already mentioned in #125

**Comment by Tbaut** [comment]
Thanks
