### ISSUE TITLE
Word suggestion list doesn't contain the expected word

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#144]
I was given this recovery phrase:
`aviation`, ... , `mangle`, `small`. [Here is a screenshot](https://user-images.githubusercontent.com/33178835/45686540-f65d0500-bb4c-11e8-9aba-34694c41c4c9.png)

But typing `aviat`, `mangl` or `smal` does not suggest "aviation", "mangle" or "small".
Example with `mangl` below:

![image](https://user-images.githubusercontent.com/33178835/45686554-0379f400-bb4d-11e8-924f-8fa2b7e8d351.png)

**Comment by debris** [comment]
what do you mean? I don't quite understand :)

**Comment by Tbaut** [comment]
`mangle` is one word of the seed phrase that was given to me upon account creation.

Now if I want to recover this account and type `mangl` in the field as shown above:
I get as word suggestion: `mango`, `mangy`, `manhangle`... but not `mangle`.

The same happens for `aviation` or `small`, these words (I didn't try them all) are not suggested.

**Comment by Tbaut** [comment]
Interestingly enough, if I type `man`, I can see `mangle` in the word suggestion list. Adding the `l` makes it disappear from the suggestion field.

Testing with `aviation`, it is never suggested whatever I type `avia`, `aviat`, `aviati`..

**Comment by Tbaut** [comment]
Fixed :)
