### ISSUE TITLE
[UX] Words aren't suggested if typed in upper case

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#145]
Android keyboard per default will write the first letter of a textbox with an uppercase.
This prevents the word suggestion from working. Can we:
- force the keyboard to use lowercase
or
- suggest words regardless of the case

Example, using a lower case "q" would have suggestions:
![image](https://user-images.githubusercontent.com/33178835/45687369-e9d9ac00-bb4e-11e8-9563-f12d8ca2bcf1.png)

**Comment by debris** [comment]
imo the first option is the best -> force the keyboard to use lowercase
