### ISSUE TITLE
SVG images support on Android

### ISSUE THREAD

**Issue by montekki** [paritytech/parity-signer#1457]
#1453 introduced identicons in svg format on iOS. There should also be support on Android.

**Comment by Dmitry-Borodin** [comment]
Notes: can try to parse and render into bitmap with old 
androidsvg https://stackoverflow.com/questions/53319678/converting-a-byte-array-to-a-vector-drawable 
or try to use new coil SVG decoder

**Comment by Dmitry-Borodin** [comment]
Check out PathParser inside Compose
