### ISSUE TITLE
How to update network metadata?

### ISSUE THREAD

**Issue by wliyongfeng** [paritytech/parity-signer#1495]
I encounter following problem when I try to sign a kusama extrinsic. It seems I should update the kusama metadata, but I can not find the interface with parity signer. Are there any tutorials about this?

![e590fcea-be7b-4491-92eb-c486e04bfecb](https://user-images.githubusercontent.com/2264908/209457203-b99a5ecd-cddb-4abe-bb61-54b6ebcc7f42.jpeg)

**Comment by montekki** [comment]
You have to go to https://metadata.parity.io/#/kusama and scan the video QR code and load the newer metadata.
