### ISSUE TITLE
unable to run npm run ios

### ISSUE THREAD

**Issue by theone3nu** [paritytech/parity-signer#153]
While i am trying to run this command npm run ios after checking out the project i am getting this error.

cd rust/signer && make ios
cargo build --target i386-apple-ios --release --no-default-features
make: cargo: No such file or directory
make: *** [i386-apple-ios] Error 1
error Command failed with exit code 2.

How to run this code in ios simulator

**Comment by debris** [comment]
did you run [./setup_macos.sh](https://github.com/paritytech/parity-signer/blob/master/setup_macos.sh)? 

> rustup target add i386-apple-ios
rustup target add x86_64-apple-ios
rustup target add armv7-apple-ios
rustup target add armv7s-apple-ios
rustup target add aarch64-apple-ios

**Comment by Tbaut** [comment]
closing as stale.
