### ISSUE TITLE
Use BIP39/BIP44 for new account

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#154]
For historical reasons, Parity products use a non standard logic and words dictionary for account recovery phrases. The Parity recovery phrases are not compatible with wallets such as Metamask, Jaxx or MyCrypto.

We should:
- On account recovery
  - Support legacy parity seed phrase (> 11 words because Signer currently generates 11 words)
  - Do not allow to generate brain wallets (only allow words from the word dictionary)
  - Support BIP39 recovery phrases (> 12 words)

- On account creation
  - Use BIP39 for new account generation (24 words).
  - Select the first account by default even if the user doesn't select an identicon.

Nice to have:
- At recovery, as soon as the app recognizes that the recovery is either BIP39 or Parity, the word suggestion for phrase recovery will only use the matching word dictionary.

**Comment by maciejhirsz** [comment]
I think this can be closed now that #232 has been merged? There is still UI stuff coming, but that might deserve another Issue.
