### ISSUE TITLE
Add ed25519 and sr25519 support for Substrate

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-signer#155]
- Expose rust crypto for sr25519 createAddressFromSeedUri (supporting SURI aka derivation path just like in rust and JS) to create addresses.
- Expose a new hash function to hash Tx data.
- Expose 2 substrateSign functions to sign data blobs (with ed25519 and sr25519).
- Expose a new qrCode function to be able to generate QR code with binary data (UOS support).

**Comment by burdges** [comment]
Any chance we could get a parity signer that works with ed25519 by kusama?  We've folks with dots who should be taught to use air gaped signing, not keys on their computer.  https://github.com/paritytech/parity-signer/issues/113

**Comment by Tbaut** [comment]
100% with you on that, but does it require signing anything with ed25519? I thought the important part was signing with the ethereum key (that participated in the token sale). This Parity Signer can do it already and together with a claiming app (on polkadot.js.org/apps) could do the trick what do you think?

**Comment by burdges** [comment]
Yes, there are many tokens associated to some ethereum key for now, but I'm talking aboutthe polkadot keys themselves.
