### ISSUE TITLE
Add ability to change the network on account edition screen

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-signer#158]
This is necessary for legacy accounts that are all imported as mainnet Ethereum, and some edge cases such as claiming testnet ETH using the same address on different networks.

**Comment by fckt** [comment]
For now user can just create an another account (through "Recover Account") with the same address, but for a different network.. But I'm agree we should add an ability to choose a network for the existing account.

**Comment by Slesarew** [comment]
We need to balance convenience with friction here; this requires proper research

**Comment by Slesarew** [comment]
Ok, looks like it **has** to be difficult.
