### ISSUE TITLE
Legacy accounts with empty PIN.

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-signer#159]
Can't do anything with them :).

Might also think about relaxing the PIN requirements for testnets.

**Comment by Tbaut** [comment]
If you have your recovery phrase, you can restore the account (super easily thanks to the suggestions!) and create a new 6 digits pins.

TBH we might/should not spend too much time dealing with these issues if we have a workaround :)

>Might also think about relaxing the PIN requirements for testnets.

+1
