### ISSUE TITLE
[UX] Remove "Done backup" button on the account recovery overview

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#160]
This button is awkward as the user doesn't really know what it'll do.
We'd better remove it and let the user click on "back" once or twice to go back to the account overview.

**Comment by fckt** [comment]
I'd better just rename it to "Lock and go back" or something like so. Because that is exactly what's being done.

**Comment by Tbaut** [comment]
Why? Why have a button for that differs from the usual actions? Why not simply lock the phrase again when you exit this screen?

What is the value of adding a specific button and change the user's habit?

**Comment by 5chdn** [comment]
Will there ever be a verification that the users actually backed up the phrase?

**Comment by Tbaut** [comment]
I don't think so.
We could add something like: "verify your backup phrase" so that users can double check what they wrote down. This can already be performed using the `recover account` screen.

Status has such a feature with an interesting non intrusive heads-up notification that will not go away until the user has "verified his recovery phrase".

I think for now that the target audience of Parity Signer is aware enough (helped with the warnings) that the recovery phrase is a critical piece of information.

**Comment by fckt** [comment]
> Will there ever be a verification that the users actually backed up the phrase?

I would wish to add it. But at the same time would be nice to make it optional step. If user refused to prove that he has a backup (through verification) then we just flag that account as an account which wasn't pass that verification. For such accounts (in the account details or/and in the account list screen) we'll show a warning which basically says: "Please, verify that your account is backed up. Do not store sensible amounts of funds on not backed-up accounts"

**Comment by Tbaut** [comment]
done
