### ISSUE TITLE
[UX] Remove the tab buttons "Accounts" and "Scanner"

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#161]
The real world user work flows should be the following:

Sign a transaction (Parity UI - deprecated but good as a reminder and possibly similar to Polkadot):
- Scan and sign a transaction

Sign a transaction (MyCrypto):
- Select account > show QR code > scan and sign a transaction

It feels more natural to select an account as the first action, and go from there. It also improves the security as we should not sign a transaction from the scanner if it concerns another account than the one that was selected.

- Remove Account and Scanner buttons. The account overview should be the main menu (the one we land on when launching the app)
- Add a "Scan transaction"  button under the account list on "accounts" screen
- Add a "Scan transaction"  button under the QR code on the "account QR code" screen as this is the next action that will very likely happen. 
- Move "New accounts" to a small button on the `accounts overview` screen
- Add the account verification (with a warning) when scanning a transaction happened from the acount.

![image](https://user-images.githubusercontent.com/33178835/46941273-0f34d980-d06b-11e8-9ed3-4ce7db2fedeb.png)
![image](https://user-images.githubusercontent.com/33178835/46941426-63d85480-d06b-11e8-8a79-0793a03bab23.png)

**Comment by fckt** [comment]
That was not an only scenario initially. From the start, we wanted to support a scenario when user sign a TX which was not created by himself, but by the counter party.

So that means that before removing the "Scanner" tab, first we should decide either we want or don't want to support that scenario.

**Comment by Tbaut** [comment]
>we should decide either we want or don't want to support that scenario.

Can you describe the scenario you are talking about? In what case will you get presented with a transaction that wasn't created by himself?

**Comment by fckt** [comment]
> Can you describe the scenario you are talking about?

> From the start, we wanted to support a scenario when user sign a TX which was not created by himself, but by the counter party.

That scenario is not implemented (I mean, I can't provide the working case) yet, I'm just explaining the current design decisions. To be specific: for example, there is a web store. In that store there is a "buy" button. When user taps on that button, it shows a QR of generated TX (let's say, the store have asked for a customer address before). User just scans that QR and shows the signature.

The only reason why we have the current user scenario in `MyCrypto + Parity Signer` is that *MyCrypto does not maintain the user address*, so user have to show it every time. But if they save it in cookie, user'll have to show the account address once - that means the default scenario should be different: user have to just scan and sign.

**Comment by Tbaut** [comment]
Parity UI did store the user address, and Fether as well as Polkadot UI will also most probably. I still think the design decision is not the best, the user would better select an account and then scan a transaction, for security purpose and because it feels more natural.

The account overview should be the main screen, scanning is one of the actions that can be taken. Adding the security feature that only the selected account can sign a transaction is valuable IMO.

**Comment by fckt** [comment]
I do support to remove tabs, if there will still be a way for user to run the QR scanner from any screen.

**Comment by fckt** [comment]
> The need for scanning transactions from anywhere is not strong enough, it is less secure 

please, elaborate 

> it does not feel natural

from which point of view? Please, explain

**Comment by fckt** [comment]
I just can't take the sentence above. Simply because these arguments it are not strong enough. I see more reasons to just keep the process simpler for user. For user, who used to use Apple Pay, for example it's natural to pay with pre-selected card. Our UX is not that easy as Apple Pay **already**, and user **already** has to confirm 3 times that he is doing is what he is wanted to do by:
1. TX info just after scan
2. PIN code unlock
3. Final view of the TX details and, finally (4) showing QR with a signature to the laptop camera.

So, if I correctly understand this proposal we want to add another fool-proof step, right?

**Comment by fckt** [comment]
Btw, with [this feature implemented](https://github.com/paritytech/parity-signer/issues/119), user would be able to change any property of the scanned TX. That means he would even change the `sender` address. In my first prototype of the Signer app the protocol implied that user can change the TX (choose the `sender` from the vault, for example) on the device and send it, using the QR code ([see video](https://github.com/fckt/eth-signer-app#video)).

That will allow us to really pre-select (set a default one even) the account to sign TX with. Probably it'll satisfy your original sentiment, @Tbaut 

> The need for scanning transactions from anywhere is not strong enough, it is less secure

and

> it does not feel natural

**Comment by Tbaut** [comment]
I updated the first post to have the scanning from "accounts" and a specific "account" screens.
I don't see the need for a scanning button on any other screen.

**Comment by Tbaut** [comment]
Closing as splited in 2 issues: https://github.com/paritytech/parity-signer/issues/224 and https://github.com/paritytech/parity-signer/issues/225
