### ISSUE TITLE
Old derivation paths starting with "8" cannot be imported; "8" needs to be removed

### ISSUE THREAD

**Issue by laboon** [paritytech/parity-signer#1668]
I was using the new version of Parity Signer and I noticed that re-using derivation paths directly from my old Parity Signer did not work. These original derivation paths had a preceding "8", e.g. "8//foo//bar". 

Workaround: Removing the "8" (e.g. "//foo//bar") for the new Parity Signer produces the same account. 

Does anyone know what this "8" means and why the new Parity Signer does not need it? If it is not necessary, perhaps it could be silently ignored if necessary, or a warning given when someone tries to enter it. Right now, it just does not view it as a valid derivation path.

**Comment by burdges** [comment]
Ideally signer could recognize older versions' UX quirks like this 8, and transition the user somehow, via just quietly altering the string, or warnings, or whatever.

**Comment by krodak** [comment]
@laboon @burdges frankly I couldn't find anything related to adding additional values towards entered derivation path nor filtering this value, so that would require some additional input like mentioned `8`.
Could you share what version was your old Parity Signer install was? 
I've also checked with @prybalko to confirm there was no additional logic that could trigger this on Rust side and it seems like it's the same case, so frankly we are not sure from what this issue could arise.
Currently we don't have any firm list of older versions' UX quirks like this, so no logic within new Polkadot Vault to address those 🙏🏻

**Comment by laboon** [comment]
This is on Parity Signer v4.5.2-beta (reading from the About page)

When I click on "+ Derive New Account", it gives me the opportunity to enter a derivation path (with default text of "//hard/soft". At the bottom of the screen, it shows "Kusama root" (or Polkadot root, or whatever) as "8//kusama". If I enter "//foo/bar", the derivation path at the bottom is shown as "8//kusama//foo/bar"

Looking at the list of derived addresses on Kusama for that root, it also shows me "8//kusama//foo/bar" as the derivation path.

Please let me know if you need any more information.

**Comment by laboon** [comment]
I just checked with Parity Signer v4.4.3-beta and it essentially the same behavior.

**Comment by prybalko** [comment]
@laboon I'm unable to replicate the described behaviour on `v4.5.2-beta`. I don't see the `8` prefix.
<img width="329" alt="image" src="https://user-images.githubusercontent.com/7165377/224770816-14586073-a26c-48e8-9473-1e9906e20109.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/7165377/224770885-b995d974-5541-4058-a213-3629c1767ba0.png">

```
subkey inspect "boil yellow release clay observe always float artist picnic rebuild wonder pill//kusama" --network kusama
Secret Key URI `boil yellow release clay observe always float artist picnic rebuild wonder pill//kusama` is account:
  Network ID:        kusama
 Secret seed:       0xc8e8b569b1310deceb681c55353f2eb386667317e6ed09e715c3494e22b28414
  Public key (hex):  0xda28668a089bc4c7cc7dd366446696f33bf528580929073ee0976fe6196d0302
  Account ID:        0xda28668a089bc4c7cc7dd366446696f33bf528580929073ee0976fe6196d0302
  Public key (SS58): HWMxXNEsTK6Wmw42TU83hnSG4qQzp3KcnrxP5cv1jAnHmBS
  SS58 Address:      HWMxXNEsTK6Wmw42TU83hnSG4qQzp3KcnrxP5cv1jAnHmBS
```
Any chance you confused <img width="11" alt="image" src="https://user-images.githubusercontent.com/7165377/224771602-8e56e867-3e23-469d-8d08-f51aad01399d.png"> icon with `8`?

**Comment by laboon** [comment]
Oh my goodness. That is exactly what happened. 

My eyes must be getting old. To be fair, that icon looks an awful lot like a cut-off "8" and is the exact same color and size as the text..

**Comment by Tbaut** [comment]
Very interresting, this icon will as placed here to convey the idea that a derivation path was appended after the mnemonic (it's sometimes useful for users to know, to import the account elsewhere, such as the extension for instance). I'd never have thought about it being confused by an 8. Sorry Bill :)
