### ISSUE TITLE
`backup key set` screen is broken

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#1680]
`Backup key set` screen doesn't have a secret phrase.

![image](https://user-images.githubusercontent.com/7165377/222444924-27d563e7-031d-41ba-b532-62df3215e29f.png)

**Comment by Dmitry-Borodin** [comment]
I cannot reproduce it. Was it clean installation? @prybalko 
Such things may happen if you updated old app or somehow break auth state..

**Comment by prybalko** [comment]
I cannot reproduce it today as well. Anyway.

Btw, I think `Derived keys` section looks odd. It's 3 identical logos with no text. 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/7165377/222667247-3983fdf6-47cd-427a-a882-b9c4dd0e62c5.png">

For ios it looks like this
![IMG_0036](https://user-images.githubusercontent.com/7165377/222667836-b9e7cea4-d91b-4285-941e-a5033a670c20.PNG)

**Comment by Dmitry-Borodin** [comment]
steps to reproduce original issue - open backup bottomsheet and then toggle light/dark mode
