### ISSUE TITLE
ios: unable to delete network

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#1693]
Steps to reproduce:
1. Go to `Settings` -> `networks` -> `westend`
2. press `...` -> `delete network`

Expected result: network is deleted

Actual result: nothing happend. UI is unresponsive

app version: 6.0.1
ipod touch 7th gen, iOS 15.7.3

![IMG_0037](https://user-images.githubusercontent.com/7165377/223965011-e5ac6854-2481-4a1c-ac93-9ba0486b2d87.PNG)

**Comment by krodak** [comment]
Managed to retest, this works fine for iOS 16 but not for iOS 15, fix is on the way
