### ISSUE TITLE
Screen backlight during showing the multiframe QR code on iPhone

### ISSUE THREAD

**Issue by pgolovkin** [paritytech/parity-signer#1703]
When I generate the multiframe QR code for signing on the iPhone the backlight won't be turned off even in 5, 10 minutes.
When I generate the multiframe QR code for pairing my accounts on the iPhone the backlight turns off in a minute.

It will be good to turn off backlight when signing the operation with multiframe QR in order to save battery power. It may be turned off in 2-3 minutes.

**Comment by krodak** [comment]
What do you mean by backlight, you mean flashlight of screen not turning off, let's assume it's the latter. 

So currently logic regarding this is as follow:
- when on QR scanner view
- when there is QR payload that have multiple frames
- when at least 1 frame was captured
- when each new frame from multiframe QR code is captured
- ask system to not count time towards "idle display" that would disable your screen based on settings in `iOS Settings -> Display & Brightness -> Auto-Lock` (but `Low Battery` mode `on` also affects that) by setting `UIApplication.shared.isIdleTimerDisabled` to `true`

What would be formula for updated behaviour? 
Each time user scans at least 1 frame from multiframe QR code (before that we don't know whether QR code is single or multiframe of course), start a timer for 2 minutes and keep `isIdleTimerDisabled` to `true`, right?

This would just mean that we disable **system counter towards auto-lock** for 2 minutes, but when screen turns of depends on `Auto-Lock` settings and `Low Battery` mode on individual Apple device 
@pgolovkin

**Comment by pgolovkin** [comment]
@krodak Thank you for the response!

Sorry, but I can't advise the formula or some technical details. I'm talking as a user. 
I had to charge my iPhone 3 times yesterday because after signing the transaction with multiframe QR code I didn't block the screen. As I mentioned later it has showing the multiframe QR for hours.

**Comment by krodak** [comment]
Sure @pgolovkin but what would be your expectation as end user? Do you rather want to set properly Auto-Lock on your device and app just not trying to override this or expect it to hold that screen for 2-3 minutes plus what you have in your iOS settings?

**Comment by krodak** [comment]
Addressed within: #1705 , currently we won't be affecting Auto-lock functionality, so if user requires to stay on this screen longer without locking screen, they can simply change OS settings for auto-lock or just touch the screen to prevent from locking
