### ISSUE TITLE
android: Key Set menu is confusing

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#1707]
Key Set menu is confusing
<img width="318" alt="image" src="https://user-images.githubusercontent.com/7165377/224796204-b5df43d3-cb1c-4cf8-a7ae-a14540a9b5b5.png">

I think it should be like that:
-  rename`Select keys` to `Export keys`
- remove `Derive from Key` item, becase `+` does the same thing

**Comment by krodak** [comment]
![simulator_screenshot_E30447C1-6377-4096-A851-7558BD637649](https://user-images.githubusercontent.com/1955364/225054278-4724028a-4650-432d-b4af-2244c6faeb17.png)

@Dmitry-Borodin this is example menu for iOS for Key Set Details.
Are we sure about grouping by network as design for this screen? 
@tetekinandrey is this the most current design, should iOS plan to update to it?

**Comment by Dmitry-Borodin** [comment]
Thx, will update to latest Figma shortly

**Comment by tetekinandrey** [comment]
@krodak when we discussed the key set details screen with @Dmitry-Borodin, Dmitriy suggested that it would be complicated to develop filter functionality and grouping keys by the network would be faster in that sense. From the user perspective, both solutions are feasible and I think having slightly different paradigms on two platforms makes sense. We can treat it as an A/B test to pick the best solution.
