### ISSUE TITLE
Cannot copy wallet address

### ISSUE THREAD

**Issue by Buttaa** [paritytech/parity-signer#171]
Feature to copy wallet address in main menu by holding the desired wallet as shown in the picture

<img width="375" alt="parityimage" src="https://user-images.githubusercontent.com/26490734/46921637-18d42800-cffe-11e8-907e-a85b8920b0a3.png">

**Comment by fckt** [comment]
If go the the "Edit" screen and tap on the account card there, it'll copy the address to the buffer. Currently, that "edit" screen will show up if you tap on the "Tap to edit account" button on this screen:

![parityimage](https://user-images.githubusercontent.com/26490734/46921679-ad3e8a80-cffe-11e8-8304-c76d6935d530.png)

**Comment by fckt** [comment]
created a related issue https://github.com/paritytech/parity-signer/issues/173

**Comment by jangorecki** [comment]
it seems to be no longer possible using most recent version from android store, could we reopen this issue?

**Comment by Slesarew** [comment]
The UI from these screenshots is outdated desperately.  What exactly are you trying to do?

**Comment by jangorecki** [comment]
Copy polkadot address

**Comment by Slesarew** [comment]
Fair enough; not sure how useful or safe it is, but let's think about it! The upcoming version does not have this feature yet.

**Comment by jangorecki** [comment]
Without this feature I not really able to send dots to my wallet, unless I just type the address by hand, which is probably not a best practice, and it is definitely discouraging from using the wallet.

**Comment by Slesarew** [comment]
Oh, no, you are not supposed to do that, and certainly not copy-paste the address within the phone! The usage of Signer is based on it being airgapped, it should always be offline, thus you will not be able to do the "paste" part.

Instead, you should be using QR code export. The address is encoded there as plaintext; but it's even simpler - you can use apps on polkadot-js.org or [Signer companion](https://github.com/paritytech/parity-signer-companion) for this purpose.

@goldsteinsveta does this belong to FAQ?

**Comment by jangorecki** [comment]
Then it will be nice if parity releases an android wallet app for more day-to-day usage.

**Comment by Slesarew** [comment]
> Then it will be nice if parity releases an android wallet app for more day-to-day usage.

Can't agree more; there are some mobile wallets for the ecosystem not created by Parity though and a couple WIP projects within Parity right now though (not sure about status of the latter at the moment).

**Comment by Tbaut** [comment]
@jangorecki It'd help a lot just reaching out to your favorite wallet provider and ask them to support QR code based account. Same for extensions such as Talisman or Subwallet, we need to show that users want to see this happening.

**Comment by jangorecki** [comment]
I don't have any favorite ones and usually go with those listed as supported according to official documentation. Parity signer is the only one for android.

**Comment by krodak** [comment]
Closing as UI changed completely and it's no longer relevant 🙏🏻
