### ISSUE TITLE
Metadata QR code not scanned when placed inside frame.

### ISSUE THREAD

**Issue by egor0798** [paritytech/parity-signer#1713]
When scaning metadata update QR scan process seems to working only when QR code placed on the center of the screen instead of provided frame.  Issue reproduced only with metadata update QR, transaction signing QR works well. 

Android version: 12
Device: Xiaomi mi 11 ultra

QR code position which enables scan provided on the sceenshot below
![image](https://user-images.githubusercontent.com/27145216/225371514-11cbd9df-bb5b-4744-9be9-d1fecbb607ec.png)

**Comment by Dmitry-Borodin** [comment]
related to #1436
Thank you for opening an issue.
Did you try to use old app? Any difference?

**Comment by Dmitry-Borodin** [comment]
@egor0798 just to confirm - when you make it in frame full size in frame (qr up to borders of frame) and keep device stable - is it recognizing QRs much slower?

**Comment by egor0798** [comment]
> @egor0798 just to confirm - when you make it in frame full size in frame (qr up to borders of frame) and keep device stable - is it recognizing QRs much slower? Have you used old app? how it is?

It wasn't recognizing it at all.  I tried stable version from google store and it scanner worked better there. 

I installed signer from fresh [build](https://github.com/paritytech/parity-signer/actions/runs/4490066327) and it works better. It scans faster and if you place QR exatly in the frame scanner recognizes it. But it feels a little bit raw still cause you need to be very precise with frame and moving QR couple millimeters any direction stops scanning process
