### ISSUE TITLE
Unable to sign self-generated //...//0 ​​address

### ISSUE THREAD

**Issue by reki-cool** [paritytech/parity-signer#1714]
### problem occurred
I created a wallet with parity signer, and then derived three addresses, one is //stake, one is //stake//0, one is //stake//1, where //stake and //stake//1 can work normally, but //stake//0 cannot be signed, and it will prompt me that the password is wrong "Wrong password!"

### my own test
I was confused, so I used the same seed and the same path to fork in the hot wallet, and found that the address of //stake//0 in the two wallets is completely different

### loss
I personally caused a loss because of this

**Comment by montekki** [comment]
Which platform and which version of the app are you using?

**Comment by reki-cool** [comment]
I consider this question a very high priority. If confirmed to exist, this will be a very high priority BUG. parity-signer generated an unusable derived address. The same PATH is completely different from addresses generated by other Polkadot wallets。

**Comment by Tbaut** [comment]
Hint, the latest build can be obtained in the artefacts from the github actions called "Build unsigned APKs". E.g here, scroll down https://github.com/paritytech/parity-signer/actions/runs/4482127192

**Comment by Dmitry-Borodin** [comment]
I've tested and it works for me on latest version.
@reki-cool please let us know if you have any problems installing last build or if something still doesn't work there.

**Comment by reki-cool** [comment]
@Dmitry-Borodin 
√ After my test, I found that the build version in the link provided by @Tbaut is normal, and the app icon is red. 
× And the version in the Google app store I used before and the latest Parity Signer v5.0.1 Latest are all black icons, and have the problem I described above.

Not complaining, but I'm just curious why there seems to be no update in the app store and release for a long time, and this problem appears, it is likely to cause a lot of losses to some partners who unfortunately encounter the same problem, for me Fortunately, only a small part of the DOT was lost.

Therefore, I suggest updating a more stable release version and Google App Store version in time.

![image](https://user-images.githubusercontent.com/36763837/227583809-5eaec337-71c5-495e-ac9a-1ba8262afaf6.png)

**Comment by Dmitry-Borodin** [comment]
@reki-cool 
Yes, we are planning to update it soon. new release candidate is already in internal testing.
By black icon - you can see a new blue keylock icon, right? So it's no broken.

**Comment by Dmitry-Borodin** [comment]
There was a release since then. Feel free to reopen this issue if something doesn't work.
Btw I expect to release new version soon, but signing new transactions should work in old one as well.
New releases are both in google play store and in github releases page.
