### ISSUE TITLE
Add a confirmation ahead of copying an account address into the OS clipboard

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#173]
On that screen:

![img_4011](https://user-images.githubusercontent.com/547167/46936130-0392e400-d066-11e8-8f69-8356b8a90780.png)

### Rationale

The fact that there is no confirmation for use ahead of putting the address to the OS clipboard must be frustrating and even dangerous for some users. There is a need for a confirmation message ahead of any OS clipboard manipulation, as a general principle.

**Comment by Tbaut** [comment]
This should be on the account overview, not on account edition IMO.

**Comment by fckt** [comment]
> This should be on the account overview, not on account edition IMO.

You're right, but it's a different question. There is no UI/UX solution for this ATM

**Comment by Tbaut** [comment]
Closing as there's no more copying the address ability and use case, the QR code is made for this.
