### ISSUE TITLE
Could not decode, not enough data to fill buffer. Error

### ISSUE THREAD

**Issue by darkfriend77** [paritytech/parity-signer#1732]
A user has been reporting this error to us

<img src="https://user-images.githubusercontent.com/17710198/227140400-0b8d2124-7298-4e08-ab01-ff6d4b6de0b2.PNG" width="320px">

Could someone please help us to resolve this issue?

**Comment by darkfriend77** [comment]
@krodak, here is the user's process to get the error.

_I simply switched to airplane mode, clicked on the app, and that was the screen I got. It gives me the same message for "Networks" and "Verifier Certificate". I have not opened the app since I set up the signer and shared our address with you._

**Comment by prybalko** [comment]
Could it be that the user upgraded the Signer from v5 without wiping all data? Signer doesn't support migrations yet, so it has to be reset after each major upgrade.

**Comment by krodak** [comment]
@darkfriend77 has `Backup Secret Phase` + fresh install solved the issue or there is some update from that user?

**Comment by darkfriend77** [comment]
> @darkfriend77 has `Backup Secret Phase` + fresh install solved the issue or there is some update from that user?

Yes the issue was resolved, Thank you for the support,.


> I followed the suggestion and it looks like it is resolved. Thank you very much for helping with the communication. 
> I wonder how you normally deal with signer app, do you not update the app? Or actually wipe and re-add everytime?

Any suggestion on his question?

**Comment by prybalko** [comment]
> Yes the issue was resolved, Thank you for the support,.

Thank you for getting in touch.

> I wonder how you normally deal with signer app, do you not update the app? Or actually wipe and re-add everytime?

Yes, wipe and re-add every time. No other way at the moment unfortunately.
