### ISSUE TITLE
Show only "Not secure" warning if internet connection is detected. Never show "Secure" in the top right corner.

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#174]
### Motivation

Originally, the idea of the `Secure` message on the right corner was to state that device have no extra capabilities enabled (no internet, no bluetooth, no NFC, no IrDA, no USB cable connected), but only the `touch screen` and the `camera`. As it turns out we check only for an internet connection, as to check for other capabilities would require as to extend permissions for the app and will require to add libraries to work (to check in our case) with these capabilities. 

Showing the `Secure` message in case of checking only for the one type of connection (internet) could (and will) mislead user.

Related issues:
https://github.com/paritytech/parity-signer/issues/121
https://github.com/paritytech/parity-signer/issues/138
https://github.com/paritytech/parity-signer/issues/122

**Comment by Tbaut** [comment]
Hey @fckt you assigned that one to yourself a while back, I'll do it if that's ok.
