### ISSUE TITLE
Restore building for `i386-apple-ios` and `x86_64-apple-ios` targets

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#176]
Had to [disable builds](https://github.com/paritytech/parity-signer/pull/170/commits/6a44e2c3f536bb944d22c7f919764468a5bb6df0) for `i386-apple-ios` and `x86_64-apple-ios` targets due to a Ring issue https://github.com/briansmith/ring/issues/184 . That means that we can't build `libsigner.a` for a simulator (https://github.com/paritytech/parity-signer/pull/170#discussion_r225957634).

**Comment by maciejhirsz** [comment]
This should be fixed now with #232.
