### ISSUE TITLE
Cannot read TX QR in some (unknown) circumstances

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#178]
~~It seems (based on the user report) like the 1st version had a support of a ccall. We have to restore that functionality ASAP.~~

**Comment by Tbaut** [comment]
Can you explain what this exactly means?
I was able to call a contract function (ERC20 transfer) without problem:
![image](https://user-images.githubusercontent.com/33178835/47292024-14af9800-d606-11e8-8b91-acd91ac6143a.png)

**Comment by fckt** [comment]
Yeah, that issue was based on the user feedback (https://twitter.com/JonniHimik/status/1052958934913507328). Had no time to check it myself, just created the issue  as a note for a future processing. Here was my reasoning to crate the issue: due to the fact that I (personally) haven't tested the `ccall` signing process, I came down to the hypothesis that there is a some issue in that direction. **Question**: how the TX details actually looks like (in Signer app) in case of ERC-20 transfer (that should be looking weird, again haven't tested myself so far)?

Returning to the user report. As a result of a conversation with a user, it looks like his issue is related to some custom browser configuration, e.g. custom plugins (image processing proxy or any other page manipulation such as a adblock). Specifically speaking, the Signer isn't able to read the QR in the circumstances, described above. There is a need for a separate investigation to figure out what are these circumstances.

**Comment by Tbaut** [comment]
will be tracked in #180
