### ISSUE TITLE
android: app freezes when scanning QR

### ISSUE THREAD

**Issue by 0xKheops** [paritytech/parity-signer#1782]
Android Polkadot Vault app freezes when scanning this QR : 
![image](https://user-images.githubusercontent.com/26880866/232002349-10c83433-52f8-4d6d-b443-35b5a73b3796.png)

Scanning it works as intended on iOS version.
Also works fine with Parity Signer (previous version) on android.

**Comment by krodak** [comment]
HI @0xKheops are you testing on 6.1.0 or 6.0.0?
@Dmitry-Borodin could you have a look?

**Comment by Dmitry-Borodin** [comment]
I confirm it's freezing, investigating.

**Comment by Dmitry-Borodin** [comment]
@0xKheops Thank you for sharing this.
Fixed on master and hotfix will be released over the weekends.
This was happening because logo field is empty in QR code and android had bug with autosize text for empty letter in icon. 
It would be nice to share the logo in future to show proper network icon.

**Comment by 0xKheops** [comment]
Great news, thanks !
Understood, we'll have a look at how to add the logo in the payload.

For the record, it was with version 6.1.0

**Comment by krodak** [comment]
@0xKheops [here you can find](https://github.com/paritytech/parity-signer/tree/master/ios/PolkadotVault/Resources/ChainIcons.xcassets) our current mapping of values for `logo` payload in QR code to exact icons for given parachains - name of `.imageset` file corresponds to value expected in `logo` payload. It is used in [NetworkIcon](https://github.com/paritytech/parity-signer/blob/master/ios/PolkadotVault/Components/Image/NetworkIdenticon.swift) and if `logo` is not found, we'll use first letter of String value there along with [these colours](https://github.com/paritytech/parity-signer/blob/master/ios/PolkadotVault/Components/Image/UnknownNetworkColorsGenerator.swift) to generate placeholder for icon value.

This is based entirely on chain spec QRs that are hosted by Nova [here](https://metadata.novasama.io/) and although it's not ideal, this is what we are using right now per mapping as main source of chain specs + metadata for most parachain is hosted here.

Let us know if you have any questions or if there is any way we could support QR codes from Talisman in other way

**Comment by 0xKheops** [comment]
Thanks @krodak for the detailed explanation.
We'll make the required changes in Talisman
