### ISSUE TITLE
Setup points the the wrong url

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/parity-signer#1788]
A link is for parity.metadata.io when going through the initial setup 🙈 thats wrong.

**Comment by krodak** [comment]
@NukeManDan could you be more specific, iOS or Android app, what screen? Screenshot would be helpful, appreciate your feedback 🙏🏻

**Comment by krodak** [comment]
Ok, confirmed on iOS, @Dmitry-Borodin could you check Android as well? Designs in Figma featured `parity.metadata.io` instead of `metadata.parity.io`

**Comment by krodak** [comment]
iOS fix: https://github.com/paritytech/parity-signer/pull/1789

**Comment by krodak** [comment]
Let's wait for confirmation that Android features proper links @prybalko  🙏🏻

**Comment by piffle-rack** [comment]
The fix hasn't reached the Apple App Store yet - I downloaded Polkadot Vault today and the setup is still pointing to the wrong URL.

**Comment by krodak** [comment]
@piffle-rack new version with that will be distributed somewhere around mid next week, we are wrapping up some updates to UI navigation and we'll ship it together, stay tuned
