### ISSUE TITLE
Address's end is not displayed

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#179]
The full address isn't visible on a 1080 x 1920 pixels, 16:9 ratio (~401 ppi density) device:
![image](https://user-images.githubusercontent.com/33178835/47228990-e132fa80-d3c6-11e8-9d48-796da41f787c.png)

Low-end and older devices (the targeted phones) have potentially a lower resolution. [Here is a subjective view](https://deviceatlas.com/blog/most-used-smartphone-screen-resolutions#worldwide) of common device resolutions per country. We could make sure the full address is correctly displayed on a 480px wide screen. We should also probably show the 4/6 first and last digits on the main accounts overview screen, while make sure to show the full address on the account screen, something along the line:

![image](https://user-images.githubusercontent.com/33178835/47230811-86e86880-d3cb-11e8-8f29-fa62c3ec4653.png)

**Comment by ltfschoen** [comment]
Agreed, this is a major user annoyance. I just created an account and was going to send ETH to it, but I have to import it into Fether just to be able to see my Ethereum address to send the amount to.

**Comment by Tbaut** [comment]
Should be better now.
