### ISSUE TITLE
"There is a problem parsing the package."

### ISSUE THREAD

**Issue by TomaszWaszczyk** [paritytech/parity-signer#1792]
I have Android `4.3` and while I try to install `parity-signer` I got:

> There is a problem parsing the package.

Any hint how to solve this?

**Comment by krodak** [comment]
@Dmitry-Borodin could you have a look?

**Comment by Dmitry-Borodin** [comment]
Not sure about this specific error, but minimum required android version is **android 6** (api 23), this is probably due to encryption api to provide security we need.
