### ISSUE TITLE
Better support for token transfer

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#180]
Here is how it looks like when transferring an ERC20 token:
![image](https://user-images.githubusercontent.com/33178835/47362670-3b88cf80-d6d5-11e8-85b6-95b5990427d4.png)

The json (from mycrypto) :
```json
{
    "action": "signTransaction",
    "data": {
        "account": "006e27b6a72e1f34c626762f3c4761547aff1421",
        "rlp": "f869018504a817c800828f21944a6e6c3868a279e1d9047b42c3fb356ff468000380b844a9059cbb000000000000000000000000006e27b6a72e1f34c626762f3c4761547aff14210000000000000000000000000000000000000000000000000de0b6b3a76400002a8080"
    }
}
```

Ideas: 
- Show a different icon to mention if the transaction is sent to a contract.
- Add the ability to manage a list of known contracts
- Show the amount of token sent (previous point might be required)

based on https://github.com/paritytech/parity-signer/issues/178

**Comment by Slesarew** [comment]
Removing Eth support
