### ISSUE TITLE
Create a standard derivation path logic for new chains and addresses

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#1839]
Currently, users are forced to create custom arbitrary derivation paths for every new parachain address, and every new address. This is a UX nightmare and it is unnecessary to burden the user with this. I propose:

- that Parity decides on a simple arbitrary derivation path structure that is deterministic (//0001, //0002, //0003,...) so that users can recover all their addresses easily once they have started using the latest version with this logic implemented
- that when parachains are added, they do not require a new derivation path and they themselves also share the aforementioned deterministic logic once addresses are added within each parachain

The cost of this is some sacrifice of privacy, but the benefit of being able for everyday users to easily recover their keys far outweighs this cost.

**Comment by phillux** [comment]
Another thought that makes Polkadot Vault incompatible with parachain auctions is that: since users are forced to create a derivation path for each and every parachain, and they wish to participate in a crowdloan, they will be unable to access those parachain tokens on Polkadot Vault!

**Comment by Tbaut** [comment]
that's linked to a comment I made recently https://github.com/paritytech/parity-signer/issues/1787#issuecomment-1515143560

**Comment by jak-pan** [comment]
I upgraded one of my devices today from the old signer to vault and boy, I was surprised that I couldn't use vault anymore as I used accounts without derivation path... I'm glad I still have backup device otherwise I would be completely screwed.

**Comment by prybalko** [comment]
>  I used accounts without derivation path.

Is there an issue in the new Signer to create an account without a derivation path?

**Comment by jak-pan** [comment]
> > I used accounts without derivation path.
> 
> In the new Signer the default derivation path is `//<network>`, but you can create an account with any path you like (including an empty path).

How? I can't seem to find such option anywhere in the iOS app and I've been panicking there for quite some time.

**Comment by jak-pan** [comment]
> > > I used accounts without derivation path.
> > 
> > 
> > In the new Signer the default derivation path is `//<network>`, but you can create an account with any path you like (including an empty path).
> 
> How? I can't seem to find such option anywhere in the iOS app and I've been panicking there for quite some time.

Ok now that you said to me I was able to find it but it's not intuitive at all.. I would never assume I can customize derivation path if I couldn't before when adding account

**Comment by krodak** [comment]
Mentioned functionality available in current release, closing
