### ISSUE TITLE
iOS. The displayed key-set can lead to details of another one

### ISSUE THREAD

**Issue by stepanLav** [paritytech/parity-signer#1849]
**Environment:**
iOS v16.4.1
Polkadot Vault v6.1.0

**Precondition:**
several key-sets created/imported

**Case:**
1. Go to Key Sets
2. Tap on one of your key-set in order to open details

**Actual result:**
From time to time accounts from different key-set can be displayed
https://github.com/paritytech/parity-signer/assets/40560660/31434fe4-7bff-4c86-944a-692ac1ac68ec

**Expected result:**
Accounts of selected key-set should be displayed

**Comment by 0xthreebody** [comment]
Yes, I also encountered the same problem.

**Comment by krodak** [comment]
Confirmed and fixed within #1862, new TF build with fix triggered
