### ISSUE TITLE
Web3 subprovider?

### ISSUE THREAD

**Issue by digitaldonkey** [paritytech/parity-signer#186]
**Anybody ever thought about a web3 sub/-provider using parity signer?**

Using parity signer for 

      case 'eth_signTransaction':
      case 'eth_sendTransaction':
      case 'eth_sendRawTransaction':
      case 'eth_sign':
      case 'eth_signTypedData':
      case 'eth_signTypedData_v1':
      case 'eth_signTypedData_v3':
      case 'personal_sign':

See [WalletConnect](https://github.com/WalletConnect/walletconnect-monorepo/blob/3e4104577a1f9ee3de7a2fe533ffbd5cf886cca2/packages/walletconnect-web3-subprovider/src/index.js#L72-L79) source.

It might be a great offline alternative to Metamask, WalletConnect, Ledger, Tresor....

**Comment by fckt** [comment]
feels like that should be some additional tool, right?

**Comment by digitaldonkey** [comment]
I think so. We might call it a parity signer web3 provider.

**Comment by Tbaut** [comment]
Closing this as it won't be done in the foreseeable future.
