### ISSUE TITLE
QR code too small

### ISSUE THREAD

**Issue by MinefredVonCryptoven** [paritytech/parity-signer#1868]
OK this is only a "minor" issue, but I have trouble scanning QR codes on my vault app since the QR code polkadot vault generates is rather small and I have no way to "zoom in". This is probably due to not having an expensive webcam, but still.
My current solution is to take a print screen, go to images, zoom in there and scan like that, which works fine, but this is ofcourse a bit of a hassle.
Can this be improved in the nearby future?

**Comment by krodak** [comment]
@MinefredVonCryptoven could you elaborate a bit more, do you use iOS / Android, which device, what's device screen size, etc, so we can evaluate issue better? 🙏🏻

**Comment by MinefredVonCryptoven** [comment]
I have my vault installed on a samsung note 9, screen size is 6.4 inch. My webcam is a logitech c270 which is 3megapixel / 720P.
As mentioned, when polkadot vault generates a QR code, I take screenshot, go to my images, enhance the QR code about 20%, and then the webcam recognizes the code.

**Comment by MinefredVonCryptoven** [comment]
So, got all the info you needed? Will this be looked at?

**Comment by krodak** [comment]
@MinefredVonCryptoven yes, we are discussing how to approach it from UX perspective, will let you know when we have decision and timeline

**Comment by MinefredVonCryptoven** [comment]
Any update on this?

**Comment by krodak** [comment]
@MinefredVonCryptoven feel free to check newest version and let us know if something can be improved
