### ISSUE TITLE
iOS: account recovery not working

### ISSUE THREAD

**Issue by SBalaguer** [paritytech/parity-signer#1897]
I'm facing an issue by which I can't type in a word when I'm trying to use the account recovery feature. I get an input with different words that start with the letter 'a', but I can't type in anything (keyboard doesn't even pop up).

App version is 6.1.0

Thanks for the help!

**Comment by krodak** [comment]
@SBalaguer hi, could you let me know what device are you using and what iOS version? 
Also, if that's not a trouble, could you provide us with screenshot on how this recovery screen looks for you, that would be of much help with debugging 🙏🏻 (of course without any part of your seed phrase, but from what I understand text input doesn't work for you).

For reference it should behave like this (iPhone 14, iOS 16.4):

![2023-06-19 15 30 02](https://github.com/paritytech/parity-signer/assets/1955364/dd4ed841-8895-47d3-bb0e-eb178fcab3f8)

**Comment by krodak** [comment]
@SBalaguer is it like this just for this screen? Could you try tapping in top left corner of "big box" and see whether keyboard will appear? You don't experience this issue in any other screen which has textfield @SBalaguer ? 
I'll debug today / tomorrow and will get back to you

**Comment by SBalaguer** [comment]
So I followed your suggestion and tapped everywhere on the input box and it worked! The keyboard popped up. It was indeed on the top-left corner that I need to tap on, just slightly to the right (as if there were some padding or margin there).

Anyways, thanks a lot for the help! Very much appreciated.

**Comment by krodak** [comment]
No problem, I’ll have a look for possible issues on why keyboard doesn’t present itself on that is and device combination, thanks for opening an issue and sharing your feedback, much appreciated 🙇‍♂️
