### ISSUE TITLE
Add Georli testnet account type

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#190]
We already have support for Kovan and Ropsten testnets. Goerli is the new cross-client PoA testnet that is quickly gaining popularity. Having another category for accounts for this tag will be useful for Goerli users.

https://github.com/goerli

**Comment by Tbaut** [comment]
We need MyCrypto to support it too, otherwise it's worthless in Signer!

**Comment by phillux** [comment]
@Tbaut I'm in the process of finding out if the Goerli team has already reached out to MyCrypto. If not, I will take care of that and keep you posted on the issue here.

**Comment by 5chdn** [comment]
Görli is not launched yet! Please read the notes in the readme at https://github.com/goerli/testnet

**Comment by phillux** [comment]
Goerli option is in the app as of v2.2.1
