### ISSUE TITLE
Remove key / keyset does not respond, crashes on subsequent attempts

### ISSUE THREAD

**Issue by rossbulat** [paritytech/parity-signer#1920]
I had multiple key sets imported in the app, and upon trying to remove either an address within the keyset, or the keyset itself, nothing happened. And upon re-attempting to do this, the app crashes.

My workaround was to delete the app, re-install it, and re-import the keysets.

**Comment by krodak** [comment]
@rossbulat please let me know your device iOS version (i.e. iOS 15 or iOS 16) and iOS build version that should be visible in Settings (just to make sure whether you are on TF or AppStore build) and whether it happened after pincode change (as I've described issues with that setup in your previously reported issue 🙏🏻 ).

Also, can you remember what other actions have you taken before doing so? I'll tackle some test examples tomorrow and will get back to you in this thread 👍🏻

**Comment by krodak** [comment]
@rossbulat is it possible you've encountered this issue: https://github.com/paritytech/parity-signer/issues/1849 on AppStore version that would trigger deletion for key set that you have not expected?

**Comment by rossbulat** [comment]
> @rossbulat is it possible you've encountered this issue: #1849 on AppStore version that would trigger deletion for key set that you have not expected?

Hey @krodak , yes that has happened also. The indices perhaps somehow get mixed up, so tapping the second keyset would open the first, or vice-versa (the exact ordering has escaped my mind).

**Comment by krodak** [comment]
@rossbulat sorry for that experience, I've pushed `6.1.1` that solves this issue to AppStore review, I'll let you know when it passes review and is widely available, let me know then if you can re-trigger this issue 🙏🏻

**Comment by krodak** [comment]
`iOS 6.1.1 (5414272252)` is live in App Store and should resolve this issue 🙏🏻

**Comment by krodak** [comment]
Hi @rossbulat have you had a moment to retest and make sure that `6.1.1` fixes this for you?

**Comment by krodak** [comment]
Fixed deployed as part of `6.1.1` release
