### ISSUE TITLE
Import Ledger Wallet - can not figure out the correct derivation path

### ISSUE THREAD

**Issue by mt-gareth** [paritytech/parity-signer#1939]
I am sorry to post here as I know this is not an issue with your app. But I am trying to get my wallet that made Ledger to be used by Polkadot Vault. I have imported the keys, and now I am just struggling to find the derivation path. In ledger it says 44'/354'/0'/0'/0' but that does not work, I tried //354/0/0/0 and some permutations of hard and soft around that but can not get it. Would anyone be able to point me in the right direction?

**Comment by prybalko** [comment]
Ledger devices follow the de-facto standard BIP39 and BIP44. Substrate unfortunately is not BIP39/BIP44 compatible.  Here is an open issue: https://github.com/paritytech/substrate/issues/7824

**Comment by michalisFr** [comment]
@prybalko Isn't it possible to add the BIP32 derivations to Vault like Polkadot-JS UI does? 
<img width="542" alt="Screenshot 2023-07-12 at 3 54 47 PM" src="https://github.com/paritytech/parity-signer/assets/45905709/71791924-7101-4929-b162-749f24fd3716">

Currently the only alternatives Ledger users have if there's no updated app in Ledger Live is:
1) Wait
2) Build the app themselves (assuming the delay is the security audit)
3) Import their account to PJS-UI

Having the option to import in Vault would give users a valid, secure alternative.

**Comment by prybalko** [comment]
@michalisFr it is possible for sure, we already have a ticket for that https://github.com/paritytech/parity-signer/issues/812
I'll try to prioritise it.
