### ISSUE TITLE
Parity Signer drops seed phrase on authentification failure

### ISSUE THREAD

**Issue by maltekliemann** [paritytech/parity-signer#1988]
When you _Recover seed_, you enter the account name and then the seed phrase. After you're done with that, you click _Next_, and you'll be asked to authenticate yourself biometrically. When this fails, Parity Signer will throw you out of the dialog and drop the seed phrase you just entered. You have to do it all over again and hope that authentification doesn't fail this time.

This is endlessly infuriating, especially with 24 word phrases. Why don't we just get another chance to authenticate?

**Comment by prybalko** [comment]
@maltekliemann is it on Android?

**Comment by maltekliemann** [comment]
Yes, it is, Android 11.

**Comment by Dmitry-Borodin** [comment]
![image](https://github.com/paritytech/parity-signer/assets/11879032/73f2ccdb-23eb-421d-a6c7-b84e7e8f1afc)

@maltekliemann I can't reproduce this issue, but I think I found what may cause it for you.
This callback just never called in my case for some reason.
Could you check if this build fixing the issue on your device? 
https://drive.google.com/file/d/1t1gxHsTL5MGSOIqnA3UkeUNrsqF3w-ok/view?usp=sharing
