### ISSUE TITLE
Word suggestion list is cropped without horizontal scroll

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity-signer#201]
I have Parity Signer v2.0-beta installed on both a Samsung Galaxy 8 Note and an iPhone 8 Plus, and both have this issue.

If I go to "Recover Account" and click on the input field corresponding to the "Enter Recovery Words" label and enter some letters, the amount of suggested words is too wide to fit the width of the input field, and sometimes part of a word is cropped (see screenshot below), so I assume some words aren't shown at all.

Is it possible to add horizontal scroll so the user can just swipe left and right on the list of suggested words to see the ones that are cropped or not shown at all to select them? I haven't looked at the code but I'm thinking style `overflow-x: 'auto'`

![20190115_235009](https://user-images.githubusercontent.com/6226175/51182041-003b1d00-1921-11e9-8f47-3109e7b925fc.jpg)

**Comment by fckt** [comment]
> Is it possible to add horizontal scroll so the user can just swipe left and right on the list of suggested words to see the ones that are cropped or not shown at all to select them?

I don't think it adds any real value for user.

**Comment by mattrutherford** [comment]
IMHO, I don't think a scroll would give much speed advantage and could be more confusing to use - I think it would be quicker to just type another letter or two to narrow down the suggestions.

As a possible improvement, maybe truncate the list of suggested words to make sure that only whole words are shown?

**Comment by ltfschoen** [comment]
If the scroll just adds confusion to most users then let's not add a horizontal scroll.

But based on my experience as a user, even though I didn't need to use the recovery word suggestion feature, I was curious to see the horizontal scroll feature in action (which I assumed would be there since there was only a partly visible word), but it wasn't, so I felt something was missing. 

I think it would be a great idea to tweak it so it only shows whole words (even if only a few are shown)

**Comment by ltfschoen** [comment]
> IMHO, I don't think a scroll would give much speed advantage and could be more confusing to use - I think it would be quicker to just type another letter or two to narrow down the suggestions.
> 
> As a possible improvement, maybe truncate the list of suggested words to make sure that only whole words are shown?

If the scroll just adds confusion to most users then let's not add a horizontal scroll.

But based on my experience as a user, even though I didn't need to use the recovery word suggestion feature, I was curious to see the horizontal scroll feature in action (which I assumed would be there since there was only a partly visible word), but it wasn't, so I felt something was missing. 

I think it would be a great idea to tweak it so it only shows whole words (even if only a few are shown)

**Comment by Tbaut** [comment]
>scroll would give much speed advantage and could be more confusing to use - I think it would be quicker to just type another letter

The suggestion words are not only here to speed up the recovery process,  also they are very important for users to avoid typos. I believe scrolling would help and I see it being useful for someone not being able to read what he wrote on a piece of paper.

**Comment by fckt** [comment]
There is no reason to add any scroll here.

### Explanation:

Keep in mind first, all words from vocabulary are the real english words, not a random sequence of letters. The vocabulary is designed in a way which reduce the probability of mistake (even without any suggestions) to zero. And that's the most important part.

With that in mind, ok, even if that user is bad with English and she/he is misled by his spelling (`i` and `l`, for example), he/she can always try another letter (which is close to the letter he considered at first place).

**Comment by Slesarew** [comment]
There are similar issues that cover this thing; we are using completely native element now, should disable it asap, and will probably switch to something completely different. Anyway, this is not relevant anymore.
