### ISSUE TITLE
Polkavault on pi?

### ISSUE THREAD

**Issue by Luna2141** [paritytech/parity-signer#2019]
Hi, before I attempt to customize a pi board, is it possible to even run the software on a Pi board such as a pi nano to offer a smaller form factor to mimic my ledger nano X's size. Thanks,

**Comment by prybalko** [comment]
It's not officially supported.

Note: If you decide to run Polkadot Vault on a Raspberry Pi, in addition to the board itself, you would need:
- An operating system capable of running Android apps
- Camera
- Display

In essence, you would need to essentially turn your Raspberry Pi into a phone.

Feel free to close this issue, if that asnwers your question

**Comment by Dmitry-Borodin** [comment]
This app build for android and ios, and even if you will install android on Raspberry pi - provide screen and camera - with much smaller form factor you will probably experience layout problems as vault was created with smallest display something like ipad (I don't have exact resolution in mind righ tnow) and with really small screens there there will be problems.

You are welcome to experiment if you like. Recommended way is to find small phone, but experiments can be fun if you like them.

**Comment by Dmitry-Borodin** [comment]
Feel free to reopen if there will be any questions further.
