### ISSUE TITLE
Unable to debug on Samsung Galaxy S III I9300 (GT-I9300T - 4.3)

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity-signer#208]
I tried to run it on an older Samsung Galaxy S III I9300 (GT-I9300T - 4.3).

* On device I enabled "Developer options".
* In "Developer options" I enabled "USB debugging"
* When I ran `adb devices` it said it was unauthorised

```
List of devices attached
4df76dbd6b6ccf5d	unauthorized
988a1644544349575a30	device
```

* So in "Developer Options" I clicked "Revoke USB debugging authorizations"
* Then I reconnected the USB cable to the computer and it prompted "Allow USB debugging" on the mobile device and I clicked "OK"
* Then when I ran `adb devices` it said it was authorized (device) 

```
List of devices attached
4df76dbd6b6ccf5d	device
988a1644544349575a30	device
```

* I then killed the server and disconnected my Samsung Galaxy 8 Note since since you can only debug on one device at a time and I'd previously been debugging on it instead
```
adb kill-server
```

* I then started the server again and launched the app on the device
```
adb start-server
npm run android
```

* I waited until it finished running the following:

<details><p><pre>
scon @ ~/code/src/paritytech/parity-signer - [master] $ npm run android

> NativeSigner@0.0.1 android /Users/scon/code/src/paritytech/parity-signer
> npm run build-rust-android && react-native run-android

> NativeSigner@0.0.1 build-rust-android /Users/scon/code/src/paritytech/parity-signer
> cd rust/signer && make android

PATH=/Users/scon/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/Users/scon/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.nvm/versions/node/v11.7.0/bin:/Users/scon/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/code/src/paritytech/parity-signer/android/tools:~/code/src/paritytech/parity-signer/android/platform-tools:/Users/scon/code/src/paritytech/parity-signer/rust/signer/../../NDK/arm64/bin \
	CC=aarch64-linux-android-gcc \
	CXX=aarch64-linux-android-g++ \
	cargo build --target aarch64-linux-android --release
    Finished release [optimized] target(s) in 0.46s
PATH=/Users/scon/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/Users/scon/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.nvm/versions/node/v11.7.0/bin:/Users/scon/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/code/src/paritytech/parity-signer/android/tools:~/code/src/paritytech/parity-signer/android/platform-tools:/Users/scon/code/src/paritytech/parity-signer/rust/signer/../../NDK/arm/bin \
	CC=arm-linux-androideabi-gcc \
	CXX=arm-linux-androideabi-g++ \
	cargo build --target armv7-linux-androideabi --release
    Finished release [optimized] target(s) in 0.34s
PATH=/Users/scon/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/Users/scon/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.nvm/versions/node/v11.7.0/bin:/Users/scon/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/code/src/paritytech/parity-signer/android/tools:~/code/src/paritytech/parity-signer/android/platform-tools:/Users/scon/code/src/paritytech/parity-signer/rust/signer/../../NDK/x86/bin \
	CC=i686-linux-android-gcc \
	CXX=i686-linux-android-g++ \
	cargo build --target i686-linux-android --release --lib
    Finished release [optimized] target(s) in 0.34s
sh copy_android.sh
Scanning folders for symlinks in /Users/scon/code/src/paritytech/parity-signer/node_modules (23ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
The project name 'Parity Signer' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/4.4/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
        at settings_6nap3khn6d8ewwrmv8lkqea98.run(/Users/scon/code/src/paritytech/parity-signer/android/settings.gradle:1)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :app 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

> Configure project :react-native-camera 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-secure-storage 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-vector-icons 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:installDebug 
Installing APK 'app-debug.apk' on 'GT-I9300T - 4.3' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 16s
88 actionable tasks: 1 executed, 87 up-to-date
Running ~/code/src/paritytech/parity-signer/android/platform-tools/adb -s 4df76dbd6b6ccf5d reverse tcp:8081 tcp:8081
Could not run adb reverse: spawnSync ~/code/src/paritytech/parity-signer/android/platform-tools/adb ENOENT
Starting the app on 4df76dbd6b6ccf5d (~/code/src/paritytech/parity-signer/android/platform-tools/adb -s 4df76dbd6b6ccf5d shell am start -n io.parity.signer/io.parity.signer.MainActivity)...
</pre></p></details>

Since it said `Could not run adb reverse` I ran `adb reverse tcp:8081 tcp:8081`

**But it displayed:**
```
error: closed
```

* Then I found the Parity Signer app icon that had been installed and clicked it

* Then it showed the following, and I clicked "Reload"

![20190121_091522](https://user-images.githubusercontent.com/6226175/51445882-5d3e3500-1d5e-11e9-964a-89eb5033a3a8.jpg)

* Then it showed the following, but it showed the same error after clicking "Dismiss" or "Reload". 

![20190121_091533](https://user-images.githubusercontent.com/6226175/51445887-65967000-1d5e-11e9-9917-fde72289e8d4.jpg)

* I tried shaking the device to enter settings but I hadn't configured it to do that, so
on the computer I just typed `adb shell input keyevent 82` and it displayed the following:

![20190121_091817](https://user-images.githubusercontent.com/6226175/51445890-6deeab00-1d5e-11e9-9acc-0202ee04b962.jpg)

* I then clicked "Dev Settings", then clicked "Debug server host & port for device", then entered "10.0.1.1:8081" and pressed OK.

![20190121_091922](https://user-images.githubusercontent.com/6226175/51445895-7810a980-1d5e-11e9-809d-2cc964af93cc.jpg)

![20190121_091928](https://user-images.githubusercontent.com/6226175/51445896-7ba43080-1d5e-11e9-97af-a29a91ebfb20.jpg)

* I then tried reloading but it still showed the "Could not connect to development server" message

**Comment by ltfschoen** [comment]
Note that it works if I download Parity Signer from the Playstore, however I want to use the device for debugging.

**Comment by ltfschoen** [comment]
Note to self... try installing older Android SDK in Android Studio when find a cable to use the phone again

**Comment by maciejhirsz** [comment]
Just run into this myself. The problem seems to be that `adb reverse` only works on Android 5 onwards. When running a blank project from Android Studio itself it complains about the API Level being below 20 as well, but otherwise it installed the app and run it just fine.

The options are, as far as I can follow:
1) Build a release version instead of debug (obviously not as good for debugging, but something)
2) Upgrade the device to newer Android.

**Comment by maciejhirsz** [comment]
@ltfschoen I managed to get it working without upgrading the Android or changing anything else by running the development server connection over wifi.

Check your local wifi IP, then in the developer settings enter {YOUR_LOCAL_IP}:8081. Restart the app, it should connect and work as intended.
