### ISSUE TITLE
Autoscroll on Recovery seed phrase screen

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#2088]
User's feedback:
`Consider adding autoscrolling there, so users wouldn't have to scroll down after adding every second word, in order to use suggestions`.

**Comment by krodak** [comment]
@Dmitry-Borodin could you confirm this is just iOS issue, so we can close this down when #2095 is merged? 🙏🏻

**Comment by prybalko** [comment]
I wasn't able to reproduce it on Android
