### ISSUE TITLE
Do not crash after app upgrade

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#2092]
Vault doesn't have database migrations, so when the user updates the app, it crashes. 
Instead of a crash, there should be a message saying, `App upgrade is not supported; please re-install the app.`

Tasks:
- [x] fix iOS
- [x] fix Android

**Comment by Dmitry-Borodin** [comment]
@prybalko What error rust will tell us in case of not migrated db?

**Comment by prybalko** [comment]
Added `DbSchemaMismatch` in https://github.com/paritytech/parity-signer/pull/2098

**Comment by Dmitry-Borodin** [comment]
#2164 implemented new screens as per design and manual version check. So this issue is done.
