### ISSUE TITLE
Remove or replace recommended command to install NDK

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity-signer#213]
In https://github.com/paritytech/parity-signer/blob/master/create-ndk-standalone.sh#L23 we recommend that the user installs NDK using Homebrew, however this installs the latest version of NDK that may not work with Parity Signer instead of the version r13b that has been tested to actually work with Parity Signer.

Also it deceptively prints a message that appears to be the users command prompt and the command, rather than differentiating itself as an actually message to the user

**Comment by maciejhirsz** [comment]
Pointing at https://developer.android.com/ndk/downloads/ to download the zip, unpack it, then manually set the `NDK_HOME` is likely the best way to do it on every OS.

I've updated the NDK to latest version in my branch (was required to compile `ring`), but I think we should still recommend locking to the version we've tested it with (`r19` in this case).

**Comment by hanwencheng** [comment]
Closed. Now we are using prebuilt rust library built with latest NDK: https://github.com/paritytech/react-native-substrate-sign
