### ISSUE TITLE
ios: sign specs ui issues

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#2155]
There are 2 issues found for signing specs flow:
1. passcode  screen appears 2 times
2. signature screen says `Sign Transaction`, but should be `Sign Specs`
<details>
<summary>screenshot</summary>

![IMG_0078](https://github.com/paritytech/parity-signer/assets/7165377/f5c686f2-d0ae-4b59-947d-deb7f845b0c1)

</details>

**Comment by prybalko** [comment]
I'm not sure I understand. What do you mean by `copy updates`?

**Comment by krodak** [comment]
> signature screen says Sign Transaction, which is not true

What I understood from this is that we should update title `Sign Transaction` and then probably `Scan QR code to Sign Transaction` or did you mean something else?

**Comment by prybalko** [comment]
Right, instead of `Sign Transaction` it should say `Sign Specs` or `Sign Metadata`

**Comment by krodak** [comment]
Yup, so we'd need to agree on the list of possible values based on transaction type and agree whether we want to adjust screen, rest of copy in any other way, currently we just have single type of title and screen copy, no matter actual content
