### ISSUE TITLE
Feature request: Vanity identicon

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#2167]
One feature that Signer had in the early days, and that ppl really liked, is the ability to see and choose the identicon and address of the account you generated. It would be great to bring this back.

Upon new account creation the app would show several identicons corresponding to several mnemonics. Users could generate more if you didn't like any. This allowed users to actually get an identicon they like. Only then would they be presented with the mnemonic. Here's how it looked like in Stylo for instance: 

![image](https://github.com/paritytech/parity-signer/assets/33178835/486fa3dd-17f3-465f-9652-375a3b33a228)

**Comment by montekki** [comment]
It wouldn't make much sense now since the root keys are not normally used and they do not have identicons (now root keys only have jdenticons) and in your proposal you can only show identicons for root keys. And the derivations will each have a different identicons; but they are always pre-defined for obvious reasons, as in they are deterministically derived from root.

**Comment by Tbaut** [comment]
> It wouldn't make much sense now since the root keys are not normally used

Do you have any data to back this? I'd argue the opposite, just like in every other wallet, Ledger included, ppl use root keys. They were also the source of a **major** annoyance and compains from users when Signer decided to make root keys a second class citizen. Also Vault does not create any derived key per default any more. You are referring to a dark history of signer IMHO that's thankfully just this.. history.

**Comment by montekki** [comment]
You can check the latest releases, but generally work around root keys and jdenticons has been going for some while it looks for example: #2053

**Comment by montekki** [comment]
> Do you have any data to back this?

What I meant is that currently in Vault it is not that straightforward to use root keys for signing and they are treated as a special case; they don't even have an dot-identicon to signal this. All normal signing flows are supposed to be done with derived keys.

**Comment by Tbaut** [comment]
![Screenshot_20231109-212157](https://github.com/paritytech/parity-signer/assets/33178835/c42766f5-1155-436a-a632-98eb14a75e9c)

This is Vault with a fresh account. Root keys are the default, there are identicons :shrug:.

> All normal signing flows are supposed to be done with derived keys.

Idk what's more normal than this. Fact are, many users don't use derivations. The feature request above is for these.

**Comment by prybalko** [comment]
> Root keys are the default, there are identicons 🤷.

Not anymore. Here is the screenshot from the latest `master` Android build with a fresh account
<details>
<summary>screenshot</summary>

![Screenshot_20231110_094118](https://github.com/paritytech/parity-signer/assets/7165377/374e696c-878c-457c-9752-8c2a44134c2a)
</details>

This is how it works on iOS as well. However, it has not been released on Android yet.

**Comment by Tbaut** [comment]
Well this is a mistake. Why has this decision been made? Is this backed by any research?

This kind of design is the exact reason why Stylo, the fork of Signer I made back then, has been so well received. This behavior with default derivation caused confusion to many many users. You know what, I now realised that this is the reason why some ex-Parity ppl contacted me a couple weeks back, because "hey I don't understand why the address is different when I typed the same mnemonic". The mistake was made in the past, then was corrected while Alex slesarev was leading the dev. Then you make it again 🤦

You should not impose derivation paths, and should not make the root key a second class citizen. Go out of the bubble, open your eyes and look at what the wallet ecosystem does.

**Comment by prybalko** [comment]
> Or is this yet again the arbitrary decision of one person?

Exactly. https://hackmd.io/7OPDldkXRhOIBwlHfnwzSw

**Comment by krodak** [comment]
@Tbaut please try out actual newest version and maybe then reassess this discussion:
- currently we don't enforce any default derived keys - when user creates key set, they are free to choose if they want to create default derivations for selected networks, but it's optional
- you can create empty derivation for any network to use 
- I'd be hesitant to call some decisions "a mistake" without insight in decision process, it's easy to pass judgement, it's harder to prove one's point
- I'm sorry, but I also don't see any data quoted on your side that would point towards previous design being optimal, beside "some ppl contacted me", "facts are"

For reference, this is current behaviour regarding key set creation, "default" derived paths and process of adding new ones. 

<img width="320" alt="gif" src="https://github.com/paritytech/parity-signer/assets/1955364/f66478c5-d59e-4eae-aa58-e524d9ceb3e6">

If you find any of those not to your liking, please suggest other solutions with pros / cons if you really feel something is wrong with current approach, but arguments like "back in the days it was better" does not help anyone to make any progress and improve Vault 🙏🏻 🙇🏻‍♂️

**Comment by Tbaut** [comment]
Take me as as normal user. I have Vault on an android device that is online, to test. The version I have here is the one I screenshoted. If things have changed and not been released, I didn't notice.. and didn't test. I take ppl's word and go with it.

Happy to read that it indeed won't be a default. I'll check it out, and open subsequent issues eventually.

> I'd be hesitant to call some decisions "a mistake" without insight in decision process, it's easy to pass judgement, it's harder to prove one's point

> I'm sorry, but I also don't see any data quoted on your side that would point towards previous design being optimal, beside "some ppl contacted me", "facts are"

You're right, I shouldn't be that "trust me" person, and don't feel particularly good at showing off my tract record, but I'll do. I've been involved in Signer [since the beginning](https://github.com/paritytech/parity-signer/graphs/contributors), as a support, PM, and eventually the main maintainer of it. I've been the first line of support for many years and gave countless presentations about it. I saw it change and we made the move from Ethereum to Substrate. More or less when things went south, I had left Parity and kept maintaining a fork of Signer called [Stylo](https://github.com/stylo-app/stylo) for a while. It was the only offline signer to support parachains when they were introduced on Kusama. Signer was out of shape, and Alex was working on it, but it took a lot of time for v5 to be released. Stylo was downloaded more than Signer at some point and was the de-facto product to use instead of Signer. I've followed closely the dev with Alex, Fedor and now you, although I'm less involved these days. With this in mind, you don't have to just trust me, but you can probably agree that I'm not just a random user either. I didn't spend the time searching for all the issues that must be around regarding the derivation. There are countless discussion on Element as well. Things along the line of https://github.com/paritytech/parity-signer/issues/833. Now I won't waste any more time to fight it if it's against the dictated stream.

**Comment by Dmitry-Borodin** [comment]
Thx @Tbaut  for a feedback, we considering improving this communication.
