### ISSUE TITLE
Entering Recovery Words in Recover Account allows capital letters even though letters of recovery words are always lowercase

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity-signer#218]
Due to the settings on my mobile device, when I go to "Recover Account" and enter the first recovery word into the "ENTER RECOVERY WORDS" input field, it makes the first letter of the word a capital letter, so I always have to manually remember to switch off the SHIFT button before entering the first word, or I have to edit the first letter to make it lowercase. Since I recover my accounts quite often this is quite annoying.

As far as I understand, all the letters in recovery words always all lowercase

I think it would be more convenient for users if it automatically converted all valid inputs to lowercase

**Comment by fckt** [comment]
> Did previous versions allow users to customise their recovery phrase so it could contain any value (i.e. capital letters, symbols, and numbers, etc)?

Moreover, the current does.

> There are users still use capital letters in their account recovery phrases even though it's not recommended.

**Comment by ltfschoen** [comment]
> > Did previous versions allow users to customise their recovery phrase so it could contain any value (i.e. capital letters, symbols, and numbers, etc)?
> 
> Moreover, the current does.
> 
> > There are users still use capital letters in their account recovery phrases even though it's not recommended.

Ok, but I'm not yet sure how to do that with the current version.

**Comment by fckt** [comment]
> Ok, but I'm not yet sure how to do that with the current version.

so.. The definition of the issue is not correct "even though letters of recovery words are always lowercase" - it's corresponds to validation. The seed phrase itself could be arbitrary.

**Comment by maciejhirsz** [comment]
Tested this on iOS, Android 9 (emulator) and Android 4.4 (physical device), in all cases when I go to entering the phrase the shift isn't locked (first letter pressed is lower case).

**Comment by ltfschoen** [comment]
I had disable the following configuration on my Android device so it wouldn't capitalise the first letter. Although I'm not sure if this was configured by default:

Settings > General Management > Language & Input > On-screen Keyboard > Samsung Keyboard > Smart typing > Auto capitalise

**Comment by maciejhirsz** [comment]
Weird, I'm sure I didn't change any settings. FWIW, when entering the account name I do get shift locked for the first letter.

**Comment by fckt** [comment]
https://github.com/paritytech/parity-signer/blob/master/src/components/AccountSeed.js#L190

**Comment by Tbaut** [comment]
Late to the party, this should have been solved in https://github.com/paritytech/parity-signer/pull/199. Note that some keyboards will not behave (such as swiftkey) unfortunately.
