### ISSUE TITLE
Enhance menus

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#225]
- Move "New accounts" to a small button on the `accounts list` screen to reach
  - New Account
  - Recover Account

- Move "Edit" to a multi-select menu at the top right and allow to reach:
  - Edit
  - Change Pin
  - Backup
  - Delete

![image](https://user-images.githubusercontent.com/33178835/53350893-6ce20800-3920-11e9-8cbc-6c6222e4b82e.png)
![image](https://user-images.githubusercontent.com/33178835/53351017-b894b180-3920-11e9-88f7-d8f33f46ded4.png)

**Comment by fckt** [comment]
Proposed UI doesn't follow IOS nor Android mobile guidelines.

**Comment by Tbaut** [comment]
I think that's not a big issue, even [gmail](https://1ad20d09099cef6447ca02f7da2adf1f007b9244-m.proxy.startpage.com/npd/mbsuofdejpseob/xxx/ST/mDFUUqLFUmFSkCKuB80Kj980Q//////////SURFLYROOT//////////sites/androidcentral.com/files/styles/xlarge/public/article_images/2016/06/recover-gmail-contacts-android-screens-05.jpeg?SURFLY=R?itok=sczYqX45) does it that way. What I'm interested about is to not surprise users for such behaviors.

**Comment by fckt** [comment]
on iOS it's different, for sure

**Comment by miha999rus777** [comment]
Xz
