### ISSUE TITLE
Unable to import unsigned metadata for signing

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/parity-signer#2252]
Version: Android, from Google Store, Dec 22, 2023

---

I am unable to import unsigned metadata. Network was added via the QR code generated by the metadata portal repository and contains no verifier certificate. 

Still, upon loading the multi-prompt data the app tells me that an error occured and I can not import the metadata. 

Problem: 

I am the one who needs to sign it in the first place in order to publish this latest version. 

NOTE: 
Might be misusage or my inability to use the app, but if not, that is a serious annoyance for chain maintainers.

**Comment by mustermeiszer** [comment]
Possible dublicate of #1908

**Comment by mustermeiszer** [comment]
Any response here?

**Comment by prybalko** [comment]
Thank you for reaching out. 

Try to do the following steps:
1. remove the network and the verifier certificate (if any)
2. scan unsigned network specs
3. scan unsigned metadata

The current set of restrictions does not allow to accept unsigned metadata if network specs QR were signed. There is https://github.com/paritytech/parity-signer/issues/1908 to remove this restriction

**Comment by mustermeiszer** [comment]
I did that. Scanned both the 
* unsigned network specs 
* unsigned metadata

all generated from the metadata portal code. 

Just to confirm, this is not a known issue? I will try to replicate that during the next upgrade which comes in soon anyways.

**Comment by prybalko** [comment]
This is not a known issue.

**Comment by mustermeiszer** [comment]
I am not following. You suggested to 

> 1. remove the network and the verifier certificate (if any)
2. scan unsigned network specs
3. scan unsigned metadata

I did that, but it still would not allow me to import the metadata for signing it. 

Is this a known issue? So there is just no fix at the moment?

**Comment by prybalko** [comment]
What's the name of the chain so i can replicate the issue?

**Comment by mustermeiszer** [comment]
Centrifuge Chain. Repo: https://github.com/centrifuge/metadata-portal/tree/master/public

And thanks a lot

**Comment by prybalko** [comment]
I'm unable to replicate the issue

<details>
<summary> screenshot with unsigned Centrifuge metadata</summary>

![Screenshot_20240111-221316](https://github.com/paritytech/parity-signer/assets/7165377/f35c4c2f-6208-41bb-803d-c80c25c16187)
</details>


Here are QR codes I used

<details>
<summary> unsigned spec QR</summary>

![unsigned_centrifuge_specs](https://github.com/paritytech/parity-signer/assets/7165377/208ed56b-e4b0-48cb-baff-13fef42048ad)
</details>

<details>
<summary> unsigned metadata QR</summary>

![unsigned_centrifuge_metadata_1024](https://github.com/paritytech/parity-signer/assets/7165377/aee58414-fe24-4fec-9d93-d67cc7350f0c)
</details>

What I did:
- install the latest Polkadot Vaule app, create a keyset
- scan unsigned Centrifuge spec QR
- scan unsigned Centrifuge metadata QR

I got no errors.

Note: If you scan _signed_ spec QR for the network first, then Vault won't accept unsigned metadata anymore. That issue will be addressed in https://github.com/paritytech/parity-signer/issues/1908.

Could you provide me steps I can take to reproduce the issue?

**Comment by mustermeiszer** [comment]
> Note: If you scan signed spec QR for the network first, then Vault won't accept unsigned metadata anymore. That issue will be addressed in https://github.com/paritytech/parity-signer/issues/1908.

Do I need to remove the app and restart or is a wipe all data in this case sufficient?

**Comment by mustermeiszer** [comment]
And thanks for your time. Really appreciate it.

**Comment by prybalko** [comment]
> Do I need to remove the app and restart or is a wipe all data in this case sufficient?

I think you'd just need to remove the network, no need to wipe all data

**Comment by prybalko** [comment]
> Are you using android version or ios?

I tried both, got the same result.

**Comment by mustermeiszer** [comment]
Had no time to reproduce but my colleageus had no problem. So was my stupidity probably. Will close and thanks for the effort and time, much appreciated!!
