### ISSUE TITLE
Why do I get different accounts using the same '24 word phrase' recovery on ANDROID and IPHONE?

### ISSUE THREAD

**Issue by gzpywei** [paritytech/parity-signer#2270]
sam phrase:

android(vault 6.1.2) : yes,is my account
tp wallet : yes is my account
android(vault 4.5)no different account
iphone(vault 6.3)no different account

How do I need to restore the correct account on my IPHONE(IPHONE does not allow install older versions APP)

**Comment by krodak** [comment]
@gzpywei thanks for bug report, investigating, will get back to you

**Comment by krodak** [comment]
@gzpywei we've done some tests on our side and it seems that addresses are the same for same seed phrase restored on both iOS and Android.

Please share more information with us - how do you recognize that accounts are different? Do you compare root key, or specific derived path within specific network (i.e. `//polkadot` derivation path under Polkadot network), qr code for export or do you have some issue during transaction signing?

Easy way to confirm that you haven't made a typo and seed phrase is ok on both platform is to go to 3 dots menu in top right corner and tap "Backup Keys" - you can confirm then that seed phrase is indeed one you intended to export

**Comment by gzpywei** [comment]
Hi, I confirm the seed phrase is right
just restore seed. no other operation(compare root key, or specific derived path within specific network )

seed phrase is create in HUAWEI P40(harmony os 3.0) vault 6.1.2

Delete app and reinstall in P40 and restore seed phrase. Account is correct

Restore this seed phrase to TP Wallet(2.2.0) is correct 

restore this seed phrase to iPhone(ios16.6.1 vault6.3)is a different account 

Restore this seed phrase to android(android5.1 vault5.4) is a different account but same the iPhone

**Comment by krodak** [comment]
@gzpywei can you confirm that backup screen that I mentioned presents different seed phrase on iPhone or is it the same? Example of that screen below: 

![2024-01-08 20 16 36](https://github.com/paritytech/parity-signer/assets/1955364/0417806e-8213-4cb5-a595-c1dc9a66c232)

Also, repeating my question above, but what measure can you see it's different account, is root key address different, is derivation path for some network different, do you have problem signing transactions on iPhone?

**Comment by gzpywei** [comment]
> @gzpywei can you confirm that backup screen that I mentioned presents different seed phrase on iPhone or is it the same? Example of that screen below:
> 
> ![gif](https://private-user-images.githubusercontent.com/1955364/294910448-0417806e-8213-4cb5-a595-c1dc9a66c232.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjMxMDIsIm5iZiI6MTcwNDcyMjgwMiwicGF0aCI6Ii8xOTU1MzY0LzI5NDkxMDQ0OC0wNDE3ODA2ZS04MjEzLTRjYjUtYTU5NS1jMWRjOWE2NmMyMzIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTQwNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTcwYmE5MWVlYjdkYTA0YWFmZTIxNjRlMzI0MDdjY2I1ZmIwYjA2MWFkZmFhY2U1YjUwNDQyNzFkYzRhMjJlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VEUoR5wwZ4KSK_Tk03Lwg24F5aA9U9xSvN6xyYObl2E)
> Also, repeating my question above, but what measure can you see it's different account, is root key address different, is derivation path for some network different, do you have problem signing transactions on iPhone?

yes i confirmed same seed phrase

different address and no fund in account

**Comment by gzpywei** [comment]
> we've changed the default derivation paths that are present when you import the key set into Vault, so maybe you just need to add those derivations paths using "+" icon, to align with those you see on 6.1.2 on harmony OS? Probably empty derivations instead of "//polkadot", "//kusama", "//westend"

Is same //poldadot

**Comment by gzpywei** [comment]
Do you have a harmony os to test?

**Comment by krodak** [comment]
> Do you have a harmony os to test?

Not at this moment, but we'll arrange for that. I'd be more interested to see same Vault version on harmony OS vs Android 5.1 comparison, if you have an option, we'll investigate on our side in the meantime

**Comment by gzpywei** [comment]
According to tests, the seed phrase created on either Android / iPhone can be restore the same account on both them . However, seed phrases created on Harmony OS cannot be correctly restored on Android / iPhone. how can I correctly restore my account to an Android or iPhone?

**Comment by gzpywei** [comment]
HELLO, I've found the reason. The default for 6.1.2 doesn't have PATH, while 4.5 / 6.3 default to //polkadot. I assumed the default operations were the same, so I didn't pay attention. I'm not familiar with this software as it's my first time using it.

**Comment by krodak** [comment]
@gzpywei glad you got it resolved, we've changed behaviour a bit hence my questions to check seed phrase and root key address, as most of the changes are around default paths added 🙏🏻 Sorry for any confusion it could cause, hope you won't run into any further issues!
