### ISSUE TITLE
EOS wallet

### ISSUE THREAD

**Issue by TomaszWaszczyk** [paritytech/parity-signer#231]
Is it possible to implement also EOS wallet?

**Comment by Tbaut** [comment]
Thanks for the question. This is not part of our plans but if you would like to contribute and submit a PR please let us know and we'd definitely consider it. I'll close the ticket for now, feel free to answer here, the conversation can keep going.

**Comment by maciejhirsz** [comment]
@TomaszWaszczyk Parity Signer will be implementing [Universal Offline Signatures](https://github.com/maciejhirsz/uos) soon. The first step to add support would be to add EOS protocol extension to that document.

**Comment by TomaszWaszczyk** [comment]
Thanks for response! Very cool idea to transform old smartphones into cold wallet. I think that Parity Signer is the one solution which works great on older smartphone. Funny thing is when wallet describe itself as "Transform your old smartphone into cold wallet." and require the newest hardware and software. Parity Signer works very good!
