### ISSUE TITLE
new networks missing in filter view

### ISSUE THREAD

**Issue by tugytur** [paritytech/parity-signer#2326]
On android version 6.3.1 when adding a new network and trying to filter the network it's not available in the list. 
It appears after restarting the app

**Comment by Dmitry-Borodin** [comment]
@tugytur thank you for reporting. Could you clarify steps - where are you filtering networks after adding one? Like in create derivation screen?

**Comment by Dmitry-Borodin** [comment]
Ok nevermind, I will remove memory cache for all network list - it's not that beneficial.

**Comment by Dmitry-Borodin** [comment]
@tugytur Thx for submitting again.
Will be released with next release
