### ISSUE TITLE
Show a friendly message if an address is scanned

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#247]
from #245 

Users might be used to wallet applications that allow to scan a receiver's address to send funds to. Instead of showing a general error message, we can show a dedicated  message if we detect that the QR code is in the form `0x...` (20 bytes) or `ethereurm:0x..` such as:

> **Ethereum address detected**
You need to create a transaction using a software such as MyCrypto or Fether so that Parity Signer can sign it.

**Comment by hanwencheng** [comment]
After some research with UOS, and talked with YJ. I think the correct place is in the `rawDataToU8A` function in #273 , I will implement it after that one is finished.
