### ISSUE TITLE
Recovery phrase not fully displayed

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity-signer#248]
Downloaded the latest version available on (iOS) App Store. In at least one case, my recovery phrase wasn't fully displayed (the final character of the final (11th) word wasn't shown / didn't fit into the box) - neither during account creation nor in the account backup view.

**Comment by Tbaut** [comment]
I could only test on android. I've been able to reproduce the fact that a full word (or several) aren't shown, and there's no scrollbar. However making the last word just a character too long is wrapped on a new line and is therefore totally hidden.

**Comment by maciejhirsz** [comment]
This should be platform independent. Master branch already has made the box bigger for BIP39 phrases, which are longer, though we should switch it to something that does not cap the height and instead only has `min-height` equivalent.

**Comment by Tbaut** [comment]
Should be solved in v2.2
