### ISSUE TITLE
UOS compliancy for QR code reading

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#253]
The QR code reading needs to be [UOS](https://github.com/maciejhirsz/uos) compliant as this is how substrate transactions will be sent.

It will need to read the first bytes, figure out if it's old way (7B) or not
- using [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder) to get the JSON and handle it the old way (ethereum)
or
- decode the binary, hash it with the appropriate hash function (ed25519 or sr25519) and call the new signingFunction to get the QR code.

**Comment by burdges** [comment]
Are you sure the conciseness requirements are tight enough?  23624 bits is 10 times larger than previous QR code limits I've heard.  Are cameras so much better today?  Or is this using much better erasure coding?

**Comment by Tbaut** [comment]
I think you'll get the best possible answer by asking in the [UOS repo](directly) directly
