### ISSUE TITLE
Text is mixed on Terms and Conditions screen

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#256]
When first open the app, the Parity logo's text is mixed with screen name "Terms and Conditions", see the screenshots below.

<img width="375" alt="Screenshot 2019-07-18 at 17 06 51" src="https://user-images.githubusercontent.com/6014309/61469068-dbcb0680-a97e-11e9-9b43-0c154319a212.png">

**Comment by Tbaut** [comment]
This has been fixed in master https://github.com/paritytech/parity-signer/pull/254, could you double check?

**Comment by hanwencheng** [comment]
@Tbaut Yes, it is fixed, I will close it then.
