### ISSUE TITLE
Tapping on back after a message signing bring back to the scanner...

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#257]
... and it should rather get the user back to the account overview. Note that I'm talking about message signing, as in using https://mycrypto.com/sign-and-verify-message/sign

**Comment by hanwencheng** [comment]
I think that work as expected now.
![out mp4](https://user-images.githubusercontent.com/6014309/62691430-fa954980-b9ce-11e9-879e-4b91ceaebe9c.gif)

**Comment by Tbaut** [comment]
Your screenshare is for transactions. I should have emphasized that it it works as expected for transactions, but not for messages signing using https://mycrypto.com/sign-and-verify-message/sign for instance.

**Comment by hanwencheng** [comment]
Sorry for not reading carefully, now I tried the message, I think it works as expected.

![out mp4](https://user-images.githubusercontent.com/6014309/62692578-316c5f00-b9d1-11e9-9d00-13b81530c624.gif)

**Comment by Tbaut** [comment]
You're right, both message and tx signing are handled the same way https://github.com/paritytech/parity-signer/blob/master/src/screens/AccountUnlock.js#L52

closing :)
