### ISSUE TITLE
Text is out of view when entering new account name (iOS)

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#267]
v2.2.1 / iOS / iPhone X

When entering a name for a new account, the text being entered is below/underneath the keyboard.

**Comment by Tbaut** [comment]
from @jacogr on iphone Xr
![image](https://user-images.githubusercontent.com/33178835/61623578-2f876980-ac77-11e9-9528-186668bf3ce9.png)

**Comment by Tbaut** [comment]
fixed in 2.2.2
