### ISSUE TITLE
Some text fields don't have "done" option for exiting text input (iOS)

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#268]
v2.2.1 / iOS / iPhone X

Some text fields, such as the "Account name" and "Enter recovery words" fields, do not have the typical "done" button normally found on above the keyboard. This forces the user to tap an area of the screen that may cause future input errors. Scrolling is also not often possible, prohibiting the user from going to the next step.

**Comment by Tbaut** [comment]
![image](https://user-images.githubusercontent.com/33178835/61623669-62316200-ac77-11e9-8297-ce0ca6d2cd10.png)

**Comment by Tbaut** [comment]
Closing as this shouldn't be needed anymore. Also #278 will probably improve the keyboard situation a bit more.
