### ISSUE TITLE
Typeface inconsistency

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#270]
v2.2.1 / iOS / iPhone X

There are currently 2 different fonts being used, and about 5 different styles.

- Helvetica/San Francisco (iOS default)
  - Normal, Bold
- Manifold (Parity font)
  - Normal, Bold, All Caps

"Accounts" screen:
- Top menu bar:
  - Logo and brandmark: Looks good, but there is just a bit too much space between the logo and type
  - "Not Secure" is in San Francisco font, I think this should be in Manifold as well
- Account element
  - Account name should be in Manifold, and perhaps bold

Another small copy suggestion:
- Should we put "Scan QR Code" on the button for added clarity?

**Comment by hanwencheng** [comment]
In Android the `Manifold CF` font is not showed at all, I will fix that as well.
