### ISSUE TITLE
Scan/Next step buttons remain greyed out irrespective of they are activated or not (Android)

### ISSUE THREAD

**Issue by adilimroz** [paritytech/parity-signer#276]
Going by an ideal mobile design guideline, the button should be greyed out only if it is not activated i.e clicking on them carries no action. Once they are capable of carrying out an action the color of button should be changed from grey to some solid color (example green).

This has not been followed in Parity-signer, making the user confused if the button is supposed to work or not.

**Comment by Tbaut** [comment]
I've heard this feedback a dozen times "the grey button appears to be disabled."
Also while we're at it, let's change this neon green color there's no reason for this button to have a differen color:
![image](https://user-images.githubusercontent.com/33178835/61697454-92d8d080-ad37-11e9-973d-53c2e6e59872.png)

**Comment by hanwencheng** [comment]
<img width="775" alt="Screenshot 2019-07-29 at 14 25 18" src="https://user-images.githubusercontent.com/6014309/62048275-bf478d80-b20c-11e9-9c74-7498150b35b4.png">

Maybe this green, not so shining? @Tbaut

**Comment by Tbaut** [comment]
Is the left one supposed to be disabled?
hmm not convinced. All those super shiny colors don't go well together IMHO. Green is associated with good/valid (e.g for the seed field it makes sense since it's checksummed), which is not the case for the button here. I would pick something rather neutral. or even a white button.

**Comment by hanwencheng** [comment]
Left and right green are both **Valid** button colors, I was thinking if the right side green is too shining? And disabled button's color is still the same as before.
