### ISSUE TITLE
Use a customized url for testing internet reachability

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#290]
Currently `react-native-netinfo` uses a Google URL by default, which is not available in all locations, They are working on this [issue](https://github.com/react-native-community/react-native-netinfo/pull/149#issue-299686704) .

Once completed, we may use a customized URL for checking the reachability and enhance our Security Header #286

**Comment by Tbaut** [comment]
I wouldn't like to put the hurdle on us for such a feature. I don't want to have to monitor the custom url we would use to make sure it works in 6 months.

Making sure the library is working anywhere is something that should effectively be handled by the library, not the app using it.

**Comment by hanwencheng** [comment]
Closed
