### ISSUE TITLE
Disable instant pin check, and add maximum input time.

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#311]
It would be securer to disable the instant check of the pin code, and add a limit for trying to input the pin. For example, once user click more than 5 times with the wrong pin, then the app will reset the `secure store` with the private keys.

It is convenient without a final click, but I do not think it is secure enough.

![out mp4](https://user-images.githubusercontent.com/6014309/62691902-e4d45400-b9cf-11e9-8bbd-6027d13acd45.gif)

**Comment by Tbaut** [comment]
> For example, once user click more than 5 times with the wrong pin, then the app will reset the secure store with the private keys.

This is a little too much IMO. Parity Signer isn't very well protected against physical attacks ([neither are hardware wallets](https://ledger-donjon.github.io/Unfixable-Key-Extraction-Attack-on-Trezor/)). Brute forcing is something that we can try to prevent, but erasing anything is not advisable. What we could do is have an exponential cool off period. I don't think this relates directly to the "instant pin check" though.

**Comment by hanwencheng** [comment]
An exponential cool off period is also a good idea which gives the user time to transfer the assets from this account out, I would suggest 24 hours for that. But a question is: is it possible to reset the time of the phone and thus remove this limitation? 

Why I connect these two questions together is because:
1. if we have an attempts limitationthen we have to add a `NEXT` button, which will remove this instant validation.
2. This validation actually gives hints on multiple attempts. Because our pincode's digits is not limited. For instance, user may have a pincode of `12345678901`, but it will have the error message when user has inputs of `123456`, `1234567`, `12345678`, `123456789`, `1234567890`. In this situation, an attacker will never click `NEXT` Button and he will get enough message. If we do not have `NEXT` Button, then before we input the last `1`, the limitation will be achieved at this moment (already 5 wrong attempts).

A draft UI could be like followings: 

![pincodeAttempt](https://user-images.githubusercontent.com/6014309/62698794-4f8c8c00-b9de-11e9-8c34-8e95fbadb268.png)

**Comment by Tbaut** [comment]
Per se I have nothing against adding a button instead of the automatic check.

> But a question is: is it possible to reset the time of the phone and thus remove this limitation?

Good point, I forgot about this, I don't think this can be worked around unfortunately. Our best bet  might be to use the secure enclave https://github.com/paritytech/parity-signer/issues/222 with fingerprint. This is definitely an area we should check (both for android and iOs).

**Comment by hanwencheng** [comment]
I will start from that one @Tbaut
