### ISSUE TITLE
switch back to the published react-native-secure-storage

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#312]
We've been using a fork of `react-native-secure-storage`, the main reason seems to have been the downgrade of RN version requirement.
We don't have this problem anymore and should try to switch back to the original library (and archive our fork). 

Good to know, the list of commits on our fork:  https://github.com/paritytech/react-native-secure-storage/commits/master

**Comment by hanwencheng** [comment]
lol, when I am working on #222, I have not noticed our repo is a folk, and I am trying to add documentation for it. Now I will stop and switch back to that one.

**Comment by Tbaut** [comment]
#222 is a much bigger work I think. This issue may be easy to do. However since #222 would replace it, if you are working on #222  and think it's doable in the medium/short term, don't spend time on this issue.

**Comment by hanwencheng** [comment]
Sorry I bring an ambiguous meaning. I mean I will stop write the documentation of `paritytech/react-native-secure-storage`. I will implement this issue together with #222, will send a WIP PR for #222 late today

**Comment by geastwood** [comment]
The repo from [**parity**](https://github.com/paritytech/react-native-secure-storage) actually predate the one currently under npm package name (react-native-secure-storage).

The important fact is, in `parity/react-native-secure-stage`, the one currently used by this repo has a good implementation for iOS, which means it uses keychain to store sensitive data (which is referred also in #222 I guess). However under *Android* it only uses `SharedPreferences` to store data. And this is not safe. 

For this reason, it's better to switch to the npm one, which implements both iOS and Android using a more secure approach.

**Comment by hanwencheng** [comment]
@geastwood Thanks for pointing out clearly the difference between these two repos!

If we need to secure the seed phrases with an application-scope pin code, `oyyq99999/react-native-secure-storage` would be a good practice to do that.

It would be nice if we could also use device-scope TouchId/fingerprint or FaceId to unlock the seed phrase. Then we may use `Secure Enclave` or a [Hardware-backed Keystore](https://source.android.com/security/keystore) to secure these biometric data. `oyyq99999/react-native-secure-storage` uses application-scope `keystore` on Android, and `keychain` without Secure Enclave on iOS, it would have the potential to improve. 

So probably we may offer these TouchId or FaceId seed phrase unlocks function on the supported device:
By support I mean:
- iOS: Secure Enclave and TouchID / FaceId support: iPhone 6
- Android: Trusted Execution Environment / StrongBox Support Devices

And use the keystore part from `oyyq99999/react-native-secure-storage` for backward compatibility.

I have checked some of the react-native Keychain/Keystore libraries,  does not find anyone with `Secure Enclave`. Probably we just start to implement it from `parity/react-native-secure-store`. And also update the current  `SharedPreferences` to `Keychain` for the Android part.

cc @Tbaut @maciejhirsz

**Comment by geastwood** [comment]
It's a good point to bring up TouchID/FaceID/FigurePrint support. 

The implementation from `oyyq99999/react-native-secure-storage` actually has full support for what you mentioned above. Of course on Android devices, the support is limited depend on the capabilities of the hardware. For both iOS and Android it provides methods to query what is supported.

**Comment by Slesarew** [comment]
RN removed
