### ISSUE TITLE
Fix iphone splash screen

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#313]
On iphone, the apps shows a weird splash screen upon launch (the pause button is not from the splash screen, it's from my screenshot):
![image](https://user-images.githubusercontent.com/33178835/62858575-ff256f00-bcfa-11e9-8bd1-0bba69608fdd.png)

We should have a simple image containing the Signer logo:
![app-icon](https://user-images.githubusercontent.com/33178835/62858711-4e6b9f80-bcfb-11e9-9245-3ef9c4e86118.png)

**Comment by hanwencheng** [comment]
Closed with #316 .
