### ISSUE TITLE
Replace StackNavigator with SwitchNavigator

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/parity-signer#315]
### Problem:
It seems before the v2.1 bump that we have been incorrectly using a StackNavigator for navigation, which was fine but with the latest version of `react-navigation` we had to work around it by setting key to undefined when resetting the route.
```
StackActions.reset({
                index: 1,
                key: undefined, // FIXME
                actions: [
                  NavigationActions.navigate({ routeName: 'AccountList' }),
                  NavigationActions.navigate({ routeName: next })
                ]
              });
```

### Solution
The correct solution is to refactor our navigator to use a SwitchNavigator instead. https://github.com/react-navigation/react-navigation/issues/1127#issuecomment-295841343

IIRC I used the workaround as the refactor would be potentially quite hairy and that particular bump PR was already big and hairy enough.

**Comment by Tbaut** [comment]
it's at the following places:

https://github.com/paritytech/parity-signer/blob/e781b8c1647c79773ec0e900ff8a0092f722155c/src/screens/AccountUnlock.js#L54

https://github.com/paritytech/parity-signer/blob/e781b8c1647c79773ec0e900ff8a0092f722155c/src/screens/AccountPin.js#L77

https://github.com/paritytech/parity-signer/blob/e781b8c1647c79773ec0e900ff8a0092f722155c/src/screens/AccountPin.js#L77
