### ISSUE TITLE
"Not Secure" is not shown when the phone again acquires internet

### ISSUE THREAD

**Issue by geastwood** [paritytech/parity-signer#317]
"Not Secure" goes away when the internet is disconnected. However, when the internet is again acquired, nothing is shown.

![Aug-12-2019 23-30-23](https://user-images.githubusercontent.com/1623359/62899984-42162f80-bd59-11e9-8049-c54e354d5add.gif)

Sorry that the gif is not that well size, at the end of the gif you vaguely see the wifi is turned on.

**Comment by Tbaut** [comment]
Thanks for testing this thoroughly. This one is however a known issue in the iphone simulator. we talked about it in the PR that refactored this feature https://github.com/paritytech/parity-signer/pull/286#issuecomment-515087914
