### ISSUE TITLE
Inject Types from Metadata QR

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/parity-signer#318]
Following this: https://github.com/paritytech/parity-signer/pull/273

For users who don't want to ever upgrade their Signer, eventually payload will fall out of sync with latest metadata. The solution we discussed is to host a QR code with the minified metadata to inject the latest types on the fly for decoding.

Upon scanning a "add new metadata" QR code:

- verify that the payload has been signed by a Parity key
- the user should ideally not be asked for anything else than "be careful and double check everything".

The best would be to add the genesis hash of the network in the payload.

**Comment by yjkimjunior** [comment]
ok so just tested this and for call only meta v8 for Kusama this will be about 32 frames so just over a minute of holding your hand steady.

**Comment by yjkimjunior** [comment]
since we use the type registry from @polkadot/api, a better and reasonably implementable UX would be to allow registering specific types as is done in @polkadot/apps

**Comment by hanwencheng** [comment]
A way to do that is maybe we have a similar website as https://react-native-community.github.io/upgrade-helper/ .
