### ISSUE TITLE
Deleted accounts can still sign transactions

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-signer#323]
1. Create a Kovan account ('this is sparta')
2. Delete the account
(Optionally restart app / reboot device)
3. Scan QR
4. Sign transaction using the deleted account

**Comment by Tbaut** [comment]
Accounts are indeed never really deleted, only archived. I guess the reason behind this choice was: if someone accidentally deletes an account, we could still recover it. Now this is not transparent to our users and weakens the security of accounts. I'm for truely deleting accounts and remove the archive mechanism.

**Comment by burdges** [comment]
You might call this "remove & archive account" and have a separate option to "delete all archived accounts", so the use had two buttons and two confirmations to delete an account.

**Comment by Tbaut** [comment]
Right, then we also need a "restore archived accounts". And we should still prevent an archived account to sign IMHO

**Comment by hanwencheng** [comment]
Played a while with our `AccountStore`, the archived system works well except it will still sign the account. 

Here is the workflow:

1. User create an account, it saved into `accountStore` with `archived: false`
![Screenshot 2019-08-26 at 22 44 54](https://user-images.githubusercontent.com/6014309/63723991-15810e00-c857-11e9-9490-b2be9d69e514.png)

2. Then I delete it, the `archived` prop has changed to true.
![Screenshot 2019-08-26 at 22 45 39](https://user-images.githubusercontent.com/6014309/63724044-321d4600-c857-11e9-8e5a-509daf7c7d6d.png)

3. Once I recover it again, with the seed phrase, and with another account name, it appear again
![Screenshot 2019-08-26 at 22 47 20](https://user-images.githubusercontent.com/6014309/63724099-47927000-c857-11e9-8dc4-2d103697204a.png)

I think the system is quite straight forward, thus I have two suggestions:
1.  We probably do need the *restore archived accounts* function. The user could use the current workflow to create it.
2.  The `archived account` are still in the secure store, though they are considered safe as they are all encrypted. But in the view of privacy, the key indicates the wallet address has been used there, I think we probably need to think about to create a *delete all archived accounts* button on the main page.

**Comment by sjeohp** [comment]
Whatever it does, it should be obvious to the user.  If it gets archived it should say "archive", if it says "delete" it should be deleted completely.

**Comment by hanwencheng** [comment]
I think we need to just delete it without archiving any data, which make our workflow more complex.

As we discussed,   
1. `Delete` is more explicit to the user than `Delete & Archive`. @sjeohp
2. We still use the seed phrase to recover the archived account, which is the same as recovering a new account. So it does not make much sense that we offer user one more option but indeed behave the same as the previous one. @Tbaut 
3. I do not think use pin to recover the account is a safe way, plus in the future, we may have faceId or touchId as authentication way instead of a pin code.

If we agree on that, I will discard the PR and create a new one to actually "delete" the account.

**Comment by Tbaut** [comment]
I still believe in what I wrote earlier:
> I'm for truely deleting accounts and removing the archive mechanism.

Signer has been out for years, I never saw any conversation around that, so let's delete, as we pretended to do up to now.

**Comment by burdges** [comment]
Is there a second confirm window now?  If not, then maybe do that.

**Comment by Tbaut** [comment]
> Is there a second confirm window now? If not, then maybe do that.

The current flow is the following:
- From the account list navigate to a specific account details (1 tap on an account)
- click the menu icon on the top right
- select "Delete" (in red)
- you are asked for the pin
- you are asked in an alert if you really want to delete your account

There are many steps where you can just go back and nothing will be deleted. That's the reason I think it's ok to forget about the archival mechanism, plus our users never knew about it.. and never complained.

**Comment by burdges** [comment]
I like asking for the pin right before delete.  Is the pin prompt clear about for what the pin is being requested?

**Comment by Tbaut** [comment]
> Is the pin prompt clear about for what the pin is being requested?

It is not, created this issue to handle that case: https://github.com/paritytech/parity-signer/issues/345
