### ISSUE TITLE
UI tells me pin is wrong before I finish entering it

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-signer#324]
1. Create an account with a more than 6 digit pin
2. Change pin
3. 'Wrong pin, please try again' after 6 digits entered, whether correct or not

The app shouldn't assume a pin length.  Instead there should be a button for the user to press once they have finished entering the pin.

**Comment by Tbaut** [comment]
Discussed here as well: https://github.com/paritytech/parity-signer/issues/311
