### ISSUE TITLE
Add e2e Testing with Cavy to CI

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/parity-signer#326]
We currently have to have separate unit tests for the JS side and iOS/Android native ends of the bridge, which is a barrier to having a properly comprehensive automated QA. 

A bit of research points to https://cavy.app/ being the holy grail of such testing needs.

**Comment by hanwencheng** [comment]
Integration test is important also for testing the bridges and native modules, I am also looking at the Cavy, find it is promising. I will submit a PR for set up soon.

**Comment by yjkimjunior** [comment]
will log smaller issues for each thing that should be e2e tested
