### ISSUE TITLE
Can't sign payload with Substrate

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#339]
How to reproduce

- recover an account for Kusama with the following seed
>melt bleak cruel expect process mistake harbor very program fringe first escape spend convince park nephew phone obvious feel amazing borrow occur disorder clinic

This should generate the account E2Wv...94BT4e
- go to https://uostestqrs.herokuapp.com and copy/paste the address `E2WvmoNEWM8LUKQnw4VKXqbqTJKj2Md8tbpzs7NRt94BT4e` in the address field.

- scan a Substrate payload or blake2hash or oversized payload.
- It shows a black empty screen

**Comment by yjkimjunior** [comment]
the `txRequestData.data` can be null, so `isAddressString` should check for that. More generally we should also add an alert in case anything fails so we don't fall to a black screen again. I will make a PR for that

**Comment by hanwencheng** [comment]
After some check, get some clues here, hope that could help.

Firstly, some undefined error comes from this [line](https://github.com/paritytech/parity-signer/blob/master/src/util/account.js#L8), and throw an error if the `protocol` is not defined. Here we should prove that the target `networkKey` exists in the list `NETWORK_LIST`.

The above function is called by the following method as @yjkimjunior said:
![Screenshot 2019-08-28 at 14 42 28](https://user-images.githubusercontent.com/6014309/63856631-66514d80-c9a2-11e9-9996-a14b185cc8dc.png)
Why the `networkKey` is set to `456`? `456` is not defined in the `constants.js`.

**Comment by yjkimjunior** [comment]
^ yes, also addressing this with the udpated genesis hash, and upating the genesis hash used in the testqr payloads as well.
