### ISSUE TITLE
Mention that the account is being unlocked for deletion

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#345]
When deleting an account, users are asked to "unlock their account", but there's no mention of the deletion of the account.

We should add a text for this specific case, as the consequences can be major.

Something like
> UNLOCK ACCOUNT
to be able to delete it

**Comment by Slesarew** [comment]
Deletion probably should not require any authorisation as
1. It does not really require decoding of secrets
2. It's the least dangerous operation unauthorized user could perform
3. Accounts should be backed up at all times anyway. Of course, I intend to make difficult deletion procedure, but authorization seems unnecessary.
