### ISSUE TITLE
Accounts missing after 3.0

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity-signer#347]
After the 3.0 upgrade my Ethereum accounts disappeared.

On 3.0.1 each time I open the app, it has lost my previously added substrate accounts.

**Comment by Tbaut** [comment]
I can't reproduce on Android, can you check @yjkimjunior or @hanwencheng ?

**Comment by jacogr** [comment]
So just closed down my iOS app with a single account. Re-opened, all gone.

**Comment by sjeohp** [comment]
I have the same issue on iOS

**Comment by hanwencheng** [comment]
Same issue here on iOS, I will check that.

**Comment by Tbaut** [comment]
> And stop all the other executions, we need to catch the errors there.

Good point, I was assuming wrongly that @jacogr and @sjeohp were starting from a fresh install. You need to delete all data from Signer and/or uninstall Signer before testing. Not sure if there is such thing a "delete all data" on iOS).

**Comment by jacogr** [comment]
I have not done anything funny here -

- I had a 2.x version with existing accounts (which I def. don't expect to "lose" as part of an upgrade)
- I installed the latest version so the substrate signing can be made to work

So all-in-all it is just a simple upgrade, nothing "special".

**Comment by Tbaut** [comment]
> and I certainly wouldn't expect anybody that upgrades to actually clear their accounts before upgrading

Then those persons don't care enough about their private keys. If you use Signer, you need to have your phone offline, it's made clear everywhere. An iphone upgrade requires to be online, so the phone must be wiped before, there's no way around that.

> It should just work, and still show my existing accounts.

For testing I'd say why not. For a real usage, I disagree.

Apart from those opinions, I don't see why things would stop working from a v2 to a v3. v3 is a major release, with many changes, we could introduce breaking change, as long as we communicate this clearly.

**Comment by jacogr** [comment]
Ok, let's just agree to disagree. My accounts are backed-up, but I certainly don't expect random wipes, neither does anybody else.

**Comment by Tbaut** [comment]
So what goes wrong is here:
https://github.com/paritytech/parity-signer/blob/master/src/util/account.js#L3-L6

Older accounts don't have any `networkKey`, and rather an ethereum specific `networkType` and `chainId`. I don't think that we'll have a better opportunity than this major upgrade to break things in the near future, and I'm sure other things might break elsewhere if we keep those old accounts around.

We have the luxury to be able to ask our users to do things right by making a paper backup of their accounts, wiping their phone, upgrade then recover their accounts, let's do it. Sorry testers, I'll ask you to wipe the app as well before installing the new one.

**Comment by jacogr** [comment]
Ok, then use the “opportunity” correctly -

- detect the accounts
- remove them
- tell the user why it was done 
- allow them to recover

Randomly failing or working until they restart or asking them to uninstall and reinstall via some documentation is really not the right UX here.

**Comment by Tbaut** [comment]
As much as I find it wrong to use Signer this way, users loosing their private keys is worse.

**Comment by burdges** [comment]
In android, you might conceivably upgrade by downloading the .apk onto a memory card, inserting the memory card, and then destroying the memory card.  ;)

I donno if it's worth somehow marking keys that go online.
