### ISSUE TITLE
Address not found on 3.0

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity-signer#348]
After requesting a signature on a "Polkadot Dev" account, the . following appears -

![ima_0d1527f](https://user-images.githubusercontent.com/1424473/64075741-7b88ed80-ccbc-11e9-9d13-8fe7bc046096.png)

- the displayed account is not encoded with prefix 42 (the address shows in 42 on the UI)
- when actually decoding the address displayed and re-coding it with the correct prefix, the 2 matches - so it would seem the lookup is incorrect

**Comment by Tbaut** [comment]
Indeed, the decoding is done with Kusama per default, not taking into account the `genesisHash`.
https://github.com/paritytech/parity-signer/blob/a225c4604b82f6ed3300516b850592da28b5c720/src/util/decoders.js#L148
