### ISSUE TITLE
Ethereum Tx doesn't show receiver

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#360]
Try to scan the following with the `this is sparta` ethereum account. It's supposed to send funds to 
![image](https://user-images.githubusercontent.com/33178835/64440731-c8a9fc80-d0cc-11e9-89a2-830dd5768061.png) (this is a local account on my pc, not known to Signer) but it selects a Kusama account with noname.

![image](https://user-images.githubusercontent.com/33178835/64440643-9e583f00-d0cc-11e9-8cc8-08169edfe538.png)

**Comment by yjkimjunior** [comment]
agh, I didn't catch this from the migration PR, `getById()` will return `empty()` if nothing is found. the networkKey default for `empty()` is...Kusama
