### ISSUE TITLE
Missing Parity logo on iphone

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#364]
I just realized from a screenshot given by @hanwencheng that there's no Parity Signer logo on iphone (at the top left of the account list), and no back arrow on any other screen:
![image](https://user-images.githubusercontent.com/33178835/64476406-74ffe780-d18e-11e9-9878-70e9a79b1c83.png)
![image](https://user-images.githubusercontent.com/33178835/64476413-81844000-d18e-11e9-9f37-1f1fac34ccde.png)

whereas on Android (it's normal to have no title on Android):
![image](https://user-images.githubusercontent.com/33178835/64476425-9660d380-d18e-11e9-9797-6981d6f46b5d.png)

On iphone, the v2 used to have both the arrow and the title:
![image](https://user-images.githubusercontent.com/33178835/64476439-c3ad8180-d18e-11e9-8ef4-12f49db0aafc.png)

**Comment by hanwencheng** [comment]
Logo is shown on iOS simulator, in my case it is probably because of my react-native server connection issue, I am trying to figure that problem out, at the same @yjkimjunior could you please verify that if it is the same on your device?

**Comment by Tbaut** [comment]
You can also probably check with the Testflight version 3.0.3

**Comment by yjkimjunior** [comment]
hmm it was showing here: https://github.com/paritytech/parity-signer/pull/362

**Comment by Tbaut** [comment]
Awesome then it's most probably an isolated case :)

**Comment by Tbaut** [comment]
Bug confirmed in our live test with users, any iphone user I saw did not have the logo nor the arrow.

**Comment by Tbaut** [comment]
I might have broken that here somewhere: https://github.com/paritytech/parity-signer/pull/352/files#diff-cccffd041a575531688c60f22ff442f8R35

**Comment by hanwencheng** [comment]
I am thinking whether it related to the bundling process on iOS. With some codebase unrelated configuration, on my device I can see the logo, but pretty not sure which part make the differences here.

**Comment by Tbaut** [comment]
I had a deeper look at my changes and it seems not related indeed. I mentioned to @yjkimjunior  an error that I saw recently, that I thought was because of me, but it has to do with `MenuProvider` and seems harmless https://github.com/instea/react-native-popup-menu/issues/144

So.. I'm clueless.
