### ISSUE TITLE
Format Balance & Number on TxDetails for Kusama Payloads

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/parity-signer#371]
should be able to just iter over the params, if param type is Balance then format as such, if param type is BN, number, uint, ..., etc. format as number.

**Comment by Tbaut** [comment]
If possible, to make it international friendly we should choose to use spaces for the 1000 separator and point `.` for the unit to decimal separator. so that 2000 KSM should be displayed something like: `2 000` or `2 000.000 000 000` KSM if we want to have the full precision.
