### ISSUE TITLE
Prevent user use decimal in Pincode

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#374]
Current we use `numeric` prop for TextInput, but the display on Android and iOS devices are [different](https://lefkowitz.me/visual-guide-to-react-native-textinput-keyboardtype-options/)

Standard comparison is as following, but user may also use custom input application, though on my Xiaomi there is no decimal, I think we still need to use regular expression to dismiss the non-number input.

<img width="748" alt="Screenshot 2019-09-09 at 16 27 29" src="https://user-images.githubusercontent.com/6014309/64573071-c0e19680-d31e-11e9-9e0f-03a82fa84926.png">
 
![out mp4](https://user-images.githubusercontent.com/6014309/64573016-8546cc80-d31e-11e9-94f0-a9d1f3dfa334.gif)

**Comment by Tbaut** [comment]
All in all I wouldn't call it an annoyance of even an issue. Users are free to have complex passwords, this could even be a feature! But yeah on the other hand it's not really intended.
