### ISSUE TITLE
Ethereum signing is wrong

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#382]
How to reproduce:

- on Signer recover "this is sparta" account on Kovan 
- from my crypto this account has 0.2ETH right now send whatever amount to 0x006E27B6A72E1f34C626762F3C4761547Aff1421 (this is sparta account)
- Sign with the signer
- scan the signed Tx with MyCrypto
- the sender address is **not** sparta
- doing the same with the app before commit e41ad3f6b1996ba516b26c153d155db23fa59e69 was showing the correct 
![image](https://user-images.githubusercontent.com/33178835/64655782-9af6e780-d42d-11e9-81fc-df60fd7aa0a4.png)

**Comment by hanwencheng** [comment]
On my android device I can not reproduce the problem, it behavior correct.

But find another problem, if I sign a data, the data will displayed incorrectly, but it seems to be a problem of MyCrypto:

![out mp4](https://user-images.githubusercontent.com/6014309/64668642-2f078580-d413-11e9-86a2-2c678caf7f1c.gif)

**Comment by Tbaut** [comment]
Both problems closed by https://github.com/paritytech/parity-signer/pull/383
