### ISSUE TITLE
Destination address is encoded with prefix 42 although I'm on Kusama

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#398]
How to reproduce:

Send some funds from any address on Kusama CC2
- the `dest` address in the transaction details is always encoded with 42 prefix (starting with 5..) although it's on Kusama.

![image](https://user-images.githubusercontent.com/33178835/66043816-79ff4f00-e520-11e9-9815-bc73f974f940.png)

I suspect that it's not on Signer side, (couldn't find anything when trying to debug quickly). @yjkimjunior can you confirm? I'd send that to apps and the extension, I tested on both using Kusama encoding.

**Comment by yjkimjunior** [comment]
that shouldn't be possible, we only have the Kusama prefix visible... Even if apps were specifying a teh wrong genesis hash (which I doubt), it would not fallback to the default but rather alert the user. 

Alert: https://github.com/paritytech/parity-signer/blob/75bab33550b22d505f25dd3462e818b8f04490e0/src/util/decoders.js#L172

Default Prefix: https://github.com/paritytech/parity-signer/blob/75bab33550b22d505f25dd3462e818b8f04490e0/src/util/decoders.js#L155

Available prefixes: https://github.com/paritytech/parity-signer/blob/75bab33550b22d505f25dd3462e818b8f04490e0/src/constants.js#L29

**Comment by Tbaut** [comment]
yeah, that's what I quicly checked, maybe you missed my comment below the image:
>I suspect that it's not on Signer side, (couldn't find anything when trying to debug quickly). @yjkimjunior can you confirm? I'd send that to apps and the extension, I tested on both using Kusama encoding.
