### ISSUE TITLE
Manage network screen

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#406]
This page should be available from the top level of the app.
It should:
- show the default networks available (Ethereum, Kovan, Kusama...) without delete button
- show the added networks with the ability to delete them (no edit for now)
- show the genesis hash (`0xe53787...ad87689`) or chaid id for Etereum based network
- show a "add network" button similar to the Scan button (bringing to the scanner)

**Comment by yjkimjunior** [comment]
Now I've spent some time tinkering with this and #407, I think it makes sense to merge #406 and #407. This will be aligned with the `networkSpecs` portion outlined in Gav's whiteboarding session too. 

While the screens will be shared, the metadata will be stored separately, indexable by the networkKey.

```
type NetworkSpec = {
  chainName?: string,
  derivationPath?: string, // for the network
  identiconFn: () => void,
  networkKey: string, // genesisHash
  prefix: number
};
```
