### ISSUE TITLE
'use strict' everywhere

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/parity-signer#432]
minor annoyance, it may require a tiny bit of refactoring. Same with using `flow` everywhere. If we're going to have it we should use it everywhere or nowhere, IMHO (personal preference to using it everywhere).

Of course, all these can be addressed broadly by migrating to Typescript #418.

**Comment by yjkimjunior** [comment]
for example, neither es-lint nor flow caught this trivial brainfart error. What is the point of defining the ScannerState type if nothing checks it?

<img width="514" alt="Screenshot 2019-10-24 at 12 26 14" src="https://user-images.githubusercontent.com/10432070/67477076-a0189a80-f659-11e9-998b-2ca2fb1187b5.png">

**Comment by Tbaut** [comment]
> personal preference to using it everywhere

+1, I like `'use strict'` :)
