### ISSUE TITLE
Update Signer for Kusama upgrade

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity-signer#433]
For the Kusama upgrade, the signature is now a `MultiSignature` indicating the actual signature type as an enum. (Additionally the extrinsic format is now v4, just based on the extra indicator byte in the signature)

**Comment by yjkimjunior** [comment]
So we'll need the ECDSA function in Rust as well now then, @maciejhirsz?

**Comment by yjkimjunior** [comment]
I'd still leave this open, we're supporting sr25519 by default, but to fully support the MultiSignature we'll need to add support for ed25519 and ecdsa as well.

**Comment by hanwencheng** [comment]
Closed as duplicated with #614 .
