### ISSUE TITLE
Staking.bond instead of balance.transfer on Substrate

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#438]
How to reproduce
- connect to `wss://dev-node.substrate.dev`
- create a substrate dev Signer account and add it to `apps` accounts
- send some KSM to the account and click on `transfer` or do a `balance.transfer` extrinsic from the Signer account
- the Tx details on Signer shows `transfer.bond` although I'm doing a transfer

Note that this does not happen on Kusama.
The metadata are correct afaics..

**Comment by yjkimjunior** [comment]
when you actually sign and send the extrinsic, does it bond or does it transfer?

**Comment by Tbaut** [comment]
It does a `balances.transfer`
![image](https://user-images.githubusercontent.com/33178835/67816116-3e1cc280-faa9-11e9-8e0d-d474b3a2673f.png)

**Comment by hanwencheng** [comment]
It should be fixed by updating the metadata.
