### ISSUE TITLE
E2E - UOS

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/parity-signer#444]
This one requires mocking the React Native Camera. 

This suite would start by prepopulating the db with some accounts, feed the mock qr data, and then follow it till the Scan Signature page.

Main thing here is to verify the signature. We can add in the sr25519, ed25519, ecdsa verification Rust native binding functions as well.

**Comment by hanwencheng** [comment]
Implement a E2E mock in #431 for the camera data for extrinsic signing.
