### ISSUE TITLE
Fix Lint warnings

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#448]
At the time of writing:
- parity-signer/src/components/PayloadDetailsCard.js
  159:39  warning  'methodArgs' is already declared in the upper scope  no-shadow

- parity-signer/src/screens/AccountNew.js
  151:22  warning  'name' is already declared in the upper scope                   no-shadow
  158:10  warning  'derivationPassword' is already declared in the upper scope     no-shadow
  159:10  warning  'derivationPath' is already declared in the upper scope         no-shadow
  160:10  warning  'isDerivationPathValid' is already declared in the upper scope  no-shadow

- parity-signer/src/screens/AccountRecover.js
  214:21  warning  'name' is already declared in the upper scope                   no-shadow
  232:21  warning  'seedPhrase' is already declared in the upper scope             no-shadow
  245:9   warning  'derivationPassword' is already declared in the upper scope     no-shadow
  246:9   warning  'derivationPath' is already declared in the upper scope         no-shadow
  247:9   warning  'isDerivationPathValid' is already declared in the upper scope  no-shadow

- parity-signer/src/stores/ScannerStore.js
  260:11  warning  'missedFrames' is already declared in the upper scope  no-shadow

- parity-signer/src/util/decoders.js
  297:25  warning  Unexpected use of '>>'  no-bitwise
  297:37  warning  Unexpected use of '&'   no-bitwise

- parity-signer/src/util/decoders.spec.js
  100:1  warning  Skipped test suite  jest/no-disabled-tests

- parity-signer/src/util/strings.js
  23:9  warning  Unexpected control character(s) in regular expression: \x00  no-control-regex

**Comment by hanwencheng** [comment]
Partly addressed in #431
