### ISSUE TITLE
MyCrypto need to have chainID with its address

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#458]
Currently, the transaction or data signing request from MyCrypto is created without ChainID.

it is like: 

#### Sign Data
```
{"action": "signData", "data": {
  "account": "06fc...25d7",
  "data": "sad13uii4243"
}}
```

#### Sign Transaction
```
{"action": "signTransaction", "data": {
  "account": "06fc...25d7",
  "rlp": "sad13uii4243"
}}
```

But with current HDKD data structure, user will have same address with different chainID.

Currently we just get the first one find in phone data.

Solution: 

1. In the signing request from MyCrypto we need add ChainID.
2. refactor `getByAddress()` function in ScannerStore.

**Comment by Tbaut** [comment]
I wonder what's the biggest threat though. Message signing isn't widely used unless for proving account ownership eventually, but even this doesn't inherently needs replay protection.
