### ISSUE TITLE
refactor: GenericCall cleanup

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/parity-signer#466]
https://github.com/polkadot-js/api/pull/1592/files#diff-8f9c1338eaf62f816d813b24392771cbR77

TLDR;
`const { meta, method, section } = GenericCall.findFunction(extrinsic.callIndex);`
becomes
```
import { TypeRegistry } from '@polkadot/types`;
const registry = new TypeRegistry();
const { meta, method, section } = registry.findMetaCall(extrinsic.callIndex);
```

**Comment by yjkimjunior** [comment]
related: https://github.com/paritytech/parity-signer/issues/438

**Comment by hanwencheng** [comment]
checked the codebase, but did not find where we use this `GenericCall.findFunction`.
