### ISSUE TITLE
Unresponsive network account displayed after deleting `currentIdentity`

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-signer#482]
If I have more than one Identity and delete the current one, `currentIdentity` gets set to `null`.  If I then dismiss the identity modal I end up on the landing page with an unresponsive network account displayed.

Instead we should either set `currentIdentity` to one of the remaining ones, or not display network accounts when `currentIdentity` is `null`, or force the user to select an Identity if there are any remaining.

**Comment by hanwencheng** [comment]
> Instead we should either set currentIdentity to one of the remaining ones,

Currently it is behave like this,  could you please check it again?

**Comment by sjeohp** [comment]
Do you mean it has been fixed since I posted the issue?  I was able to recreate it several times on iOS yesterday.  I may have misidentified the cause but the bug is there.

> On 2/12/2019, at 10:53 PM, Hanwen Cheng <notifications@github.com> wrote:
> 
> ﻿
> Instead we should either set currentIdentity to one of the remaining ones,
> 
> Currently it is behave like this, could you please check it again?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 


IMPORTANT NOTICE
This communication is from Parity Technologies Limited, 
a limited company registered in England and Wales with company number 
09760015. Its registered office is Ignition Law, Moray House Floor 1, 23-31 
Great Titchfield Street, London, United Kingdom, WC1W 7PA. 


This 
communication contains information which is confidential and may also be 
privileged. It is for the exclusive use of the intended recipient(s). If 
you are not the intended recipient(s), please notify admin@parity.io 
<mailto:admin@parity.io> and delete this message immediately.


For our 
privacy policy, including the types of personal information we collect, how 
we collect and process that information, who we may share it with in 
relation to the services we provide and certain rights and options that you 
have in this respect, see https://www.parity.io/privacy/ 
<https://www.parity.io/privacy/>

-- 
This communication and any attachments are confidential.

**Comment by hanwencheng** [comment]
yeah, I think last night it is fixed.
