### ISSUE TITLE
Enable v3 user to recover their legacy substrate account

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#488]
If user have created substrate account before v4 version. Now user could still use it in legacy accounts list, but if they lose their phone/reset it, they are not being able to recover a legacy account. Since all the substrate account need to couple with a network path like `//kusama`.

So it would be useful to make backward compatible with v3 substrate root accounts. The function could existed without affect the main UI. For example: in the recover identity page, the confirm button could has a dropdown, the second option is that to create a legacy account, and when user clicks it, we prompt a warning that this is only for such v3 user lost recovering case.

**Comment by hanwencheng** [comment]
Some possible solutions:
1.  With the custom path support of #497 , would be like following, problem is that it is not intuitive, super hard for the v3 user to find solution for that, they will definitely need instruction to do that. Good point is that we do not introduce any new UI component into the app.
![out mp4](https://user-images.githubusercontent.com/6014309/70724279-97a81c00-1cfa-11ea-9bdf-0ff50b3a8bb9.gif)

2. Add "Recover Legacy Account" in the Identities Switch, which will be super clear for v3 user to find ways for recover legacy accounts. But the not good things is we want to keep switch as lean as possible, since in small screen devices it will compress the spaces for identitties, the most frequent usage of the switch is still to pick an identity. Another point is for user who need to do that, they may only need to do it once.

3.  Make a dropdown button for "Recover Identity" button in IdenttityRecover screen. It is a compromise of the above two, a> compare with first solution,  it still need to do refactoring on the button, b> it is not implicit as second solution, for the user they still need instruction on how to do that.

**Comment by goldsteinsveta** [comment]
Here're fast sketches https://www.figma.com/file/4odbGhaJ3OTN2ZQb52uvIy/Signer?node-id=5006%3A633, see UI_latest

I would interact with legacy as little as possible. HDKD is cool, let's make it usable.

From the user perspective the **root of the root** should be accessible from the AccountNetworkChooser screen, it should be accessible without choosing network (even the Unknown Network).

This works just fine if we display identity name in the same manner as we do with network name/derivation. I also like to repeat derivation subtitles and the person icon. I think it helps understanding what's up.

![screenshot](https://i.imgur.com/wdLifrZ.png)

I'll come back tomorrow with case where we do not display identity name and let's think together whether this public address should be generated automatically or whether this happens in the same way as with network root

**Comment by hanwencheng** [comment]
I think the first sketch make sense. It is clear to the user taht they could use the root idenity as an account / keypairs. 

About the second sketch, I think we should fall back all the other identities to Substrate format for now. 
1. First Substrate is our main focus, and all the networks on Substrate use the same address encoding format. Assigning a network path to the identity is enough to distinguish different networks. 
2. For ethereum users that is also clear, for example they just click Kovan then the account will be seen, it is a complex flow.
3. As we support custom path, for example `//kusama_c1000//funding` could also be created by the user, and user may want to use it on Substrate network (otherwise why create it), we need a way to show the address in Substrate format, and let these accounts under `Unknown Network` also usable with Any hot machine.

In the future if we have multiple address encoding ways, we may enable this feature to let user select the format they prefer.

**Comment by goldsteinsveta** [comment]
Ok, I am not sure I understand correctly.

The _root of the root_ – keypair generated from mnemonic. It is now in the Manage Identity screen and in the Identity popup

On Signer v3 this keypair was tied to the network. On Signer v4 it is not. For users to be able to see public address and QR for the right network it is necessary to pick the right formatting. This formatting doesn't define anything else except the rendering of the public address and QR code of the _root of the root_

![screenshot](https://i.imgur.com/JjbFAdW.png)

The only sensible alternative I'm able to see is to **not** have the _network root_, but to display _root of the root_ in current network formatting.

**Comment by goldsteinsveta** [comment]
![screenshot](https://i.imgur.com/l8hyPNi.png)

1 and 2 – Ok, got it. If the encoding options are not necessary, just get rid of the option and overlay. FYI After this one https://github.com/polkadot-js/extension/pull/203 Polkadot.js Extension will have encoding options.
3 – Sure, I am not offering to get rid of the Unknown Networks. Just to have the ability to access  "Root of the roots" without thinking about network at all
