### ISSUE TITLE
Scan button unresponsive (ios)

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#490]
Sometimes, the "scan" button doesn't work on iOs.
We found it happens when the identity modal is open, when closing it by clicking on an identity, then the scan button doesn't work for the first click.

How to reproduce:
- tap the identity icon
- tap any identity you have (it will close the modal)
- tab the scan button, it doesn't bring you to the scanner

Is this due to a layer below the modal that doesn't get dismissed correctly?

**Comment by hanwencheng** [comment]
It is because the [animationType](https://facebook.github.io/react-native/docs/modal#animationtype) of Modal is set to `fade`, the first click does not work is because the fading out process is not done yet.

Should be changed to `none`.
