### ISSUE TITLE
Document the use of derivation path in the parity wiki

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#493]
HDKD workflow isn't straightforward, we need to document that better.
linked to https://github.com/paritytech/wiki/issues/349 for visibility.

**Comment by hanwencheng** [comment]
Working on it now with this [PR](https://github.com/paritytech/wiki/pull/351#issue-358812139)

**Comment by hanwencheng** [comment]
closed by [PR](https://github.com/paritytech/wiki/pull/351#issue-358812139)
