### ISSUE TITLE
UI problem on v4

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#509]
### 1. blue link icon on the right side of root account is not align in vertical center
<img width="333" alt="Screen Shot 2019-12-27 at 18 06 44" src="https://user-images.githubusercontent.com/6014309/71544015-3dee5580-297a-11ea-8750-8d19863bdecd.png">

### 2. incorrect rendered nested list item within markdown renderer.

|Disordered text | format been cleared| all top-lever list number is 1|
|---|---|---|
|<img width="319" alt="Screen Shot 2019-12-27 at 18 53 16" src="https://user-images.githubusercontent.com/6014309/71544031-8148c400-297a-11ea-9673-5052946f1636.png">|<img width="365" alt="Screen Shot 2019-12-27 at 12 53 59" src="https://user-images.githubusercontent.com/6014309/71544043-958cc100-297a-11ea-87d8-7a3bdf105274.png">|<img width="361" alt="Screen Shot 2019-12-28 at 14 07 16" src="https://user-images.githubusercontent.com/6014309/71544156-c1f50d00-297b-11ea-9de2-60a8d23af9f3.png">|

### 3. Security page only display one line
<img width="376" alt="Screen Shot 2019-12-27 at 12 53 40" src="https://user-images.githubusercontent.com/6014309/71544087-f4ead100-297a-11ea-9b99-faf287b566b7.png">

**Comment by bjornwgnr** [comment]
I noticed point 3 ("...only display one line") also on at least one other page (i.e. "recovery phrase" page).

**Comment by hanwencheng** [comment]
@bjornwgnr true, fixed in the PR.
