### ISSUE TITLE
T&Cs have display bugs

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#513]
I totally missed that sorry. On android:
- some headers have the wrong number 1
- some paragraphs have a white background
- those paragraph's MD isn't interpreted

![image](https://user-images.githubusercontent.com/33178835/71678792-513c5f00-2d86-11ea-8981-b0b147f6e57d.png)
![image](https://user-images.githubusercontent.com/33178835/71678798-54374f80-2d86-11ea-8d7e-01aabe9c1f2d.png)

**Comment by hanwencheng** [comment]
fixed in #510
