### ISSUE TITLE
Feature request: order hard derivation sections

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#517]
Feedback from an active user :)
> I'm currently operating 20 soft-derived addresses, and another 20 hard+soft derived addresses (Stash and Controller accounts for our Kusama stake)
When I've added my 20 soft derivations, everything was as expected — the accounts are ordered in the list in the creation order, so it's 1, 2, 3, … 10, 11, 12, … 19, 20
And then my hard-derived addresses are grouped in a separate section — nice feature!

> I would like to have a same sorting order in different hard-derivation sections. I really like the "creation order" one better, since it's more meaningful in my case. But any single rule is better than no rule at all

**Comment by hanwencheng** [comment]
Now a possible solution is offer a order button, but how to present that need to be discussed, should it be a toggle or have more "orders" in the identity settings menu?

**Comment by hanwencheng** [comment]
Let me explain about the current ordering rules:

1. For the inner part inside the group, we use simply alphabetic ordering which is the default behaviour of Javascript

this part code is [here](https://github.com/paritytech/parity-signer/blob/master/src/utils/identitiesUtils.ts#L351-L352)

2. For ordering different groups, we first get the ungrouped account (without group header) in the first, and get the group with most children to the second, and so on.

See code [here](https://github.com/paritytech/parity-signer/blob/master/src/utils/identitiesUtils.ts#L392-L398)
