### ISSUE TITLE
Android - The submit key on the keyboard doesn't do anything

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#519]
From the same active user, on Android with a stock keyboard:
> in the PIN entry dialog somehow only the on-screen button "Done" allows for submitting the pin. The "Submit" button on my digit keyboard (the one with a checkbox) does nothing — and this is confusing. I would pretty much prefer that button to actually submit the PIN, since I don't see any reason not to

**Comment by hanwencheng** [comment]
closed by #520.
