### ISSUE TITLE
Kusama --dev can't be decoded correctly

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#525]
Metadata for Kusama are outdated, and this results in unwanted behaviors:
How to reproduce:

- connect to kusama --dev (v0.7.17 iirc) on `wss://dev-node.substrate.dev` and update the genesisHash for kusama dev to `0x5e9679182f658e148f33d3f760f11179977398bb3da8d1f0bf7b267fe6b3ebb0`
- submit a pre-image (democracy) with system.setRemarks 0x01 (and copy the hash)
- signing the pre-image says it can't decode it (shouldn't be the case). Sign it still
- submit a proposal and paste the pre-image previously copied

this results in a wrongly decoded extrinsic (setCouncilMember ?):
![image](https://user-images.githubusercontent.com/33178835/72521602-09c0d300-385c-11ea-9309-5f7f657c02ec.png)

edit: this only happens to --dev, the real Kusama is actually able to decode the `democracy.notePreimage`

**Comment by Tbaut** [comment]
pretty sure it's linked to https://github.com/paritytech/parity-signer/issues/438

**Comment by yjkimjunior** [comment]
that's really really really weird that it only happens on --dev (even before with your Substrate node).

It's a longshot but Is it possible that the dev node is the one giving back the wrong metadata?

**Comment by jacogr** [comment]
`--dev` runs the Polkadot chainspec, not Kusama.

**Comment by Tbaut** [comment]
Thanks for the heads-up, I wasn't aware :(. Closing
