### ISSUE TITLE
How to create account without "//kusama"?

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/parity-signer#550]
When I use the Parity-signer to recover identity. The Kusama account auto add the "//kusama" Derive prefix. How to recover my default account without "//kusama"?

**Comment by Tbaut** [comment]
You can see your older account by selecting
Add network account > create custom path

Then make sure to leave the path empty. This will show the account linked to the seed, without any path.

**Comment by jiangfuyao** [comment]
Dose Parity-signer plan to support the passphrase(///passphrase)? It's very useful. 
Because the Ledger support the passphrase, user maybe want to backup this account in parity-signer.
