### ISSUE TITLE
Dose Parity-signer plan to support the passphrase(///passphrase)? 

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/parity-signer#551]
Dose Parity-signer plan to support the passphrase(///passphrase)? It's very useful.
Because the Ledger support the passphrase, user maybe want to backup this account in parity-signer.

**Comment by jiangfuyao** [comment]
Find it, It will support: <https://github.com/paritytech/parity-signer/issues/535#issue-552869139>

**Comment by hanwencheng** [comment]
FYI: the passworded account is now supported with Parity Signer v4.2
