### ISSUE TITLE
Replace PNG logos file with SVG files

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#559]
In order to get lossless presentation, and reduce the package size. (With PNG, normally multiple file is needed for different screen resolutions).

We would better to change the logos in SVG format.

Some of SVG logos could be find here: https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/ui/logos/nodes

Link for downloading Kusama SVG: https://kusama.network/assets/kusama-brand-assets.zip

A promising library for adopting SVG: https://github.com/kristerkari/react-native-svg-transformer

**Comment by Slesarew** [comment]
PNGs are sent from rust backend into frontend. This is already the case for identicons; maybe we should store logos as svg indeed and convert them on demand?

**Comment by Slesarew** [comment]
Web3 font used for logos: https://github.com/goldsteinsveta/web3-regular
