### ISSUE TITLE
Parity Signer crashes when generating QR code

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#566]
iPhone X, iOS 13.3.1
Parity Signer 4.1.0 (Testflight)

Any time a QR code is generated from my Kusama accounts, the app crashes. I've submitted crash reports via Testflight.

**Comment by phillux** [comment]
In version 4.1.1, a blank white screen appears. The app does not crash, but no QR code for the signature is generated visibly.

**Comment by hanwencheng** [comment]
Though I tested on iPhone X simulator, and we just use plain Image item to populate QR code. I still have some following questions to reason the problem.

* Is it only for Kusama relared accounts? 
* Is it a crash with account QR code? or a tx QR code? 
* is the problem still existed with update to latest iOS 13.4?

**Comment by phillux** [comment]
- Is it only for Kusama relared accounts?
  - Maybe. I was able to successfully generate a QR code on an Ethereum account.
- Is it a crash with account QR code? or a tx QR code?
  - Tx QR code. All my accounts show their account QR code without any problem.
- Is all screen white or just QR code picture is white?
  - The entire screen is white. 
- Is the problem still existed with update to latest iOS 13.4?
  - I am updating right now. Will test again and report back asap.

**Comment by hanwencheng** [comment]
4.2 refactored the signing process and tx generating, adding error handler, please check if the problem is solved, as I cannot produce it with simulator.

**Comment by phillux** [comment]
Will test when #613 is closed.

**Comment by phillux** [comment]
Was able to test on another account. This issue is fixed.
