### ISSUE TITLE
Support enter/import accounts not generated by the app

### ISSUE THREAD

**Issue by lwshang** [paritytech/parity-signer#579]
Currently, the accounts can only be created by the app. However, users like me may generate accounts/addresses via browser extension, JS UI or subkey. Those addresses can't be protected by current parity-signer.

So I'm requesting a feature that make user be able to manually enter/import their existed accounts.

**Comment by hanwencheng** [comment]
Signer is suppose to be used as an alternative way to any hot wallet, basically it should not share the privatekey with any hot wallet, which increases the exposure risk of the account on Signer.

If you want to protect an account from e.g. extension with Signer,  my suggestion would be create you fund account here on signer, transfer some amount of money to the browser extension account. And use extension with small amount transfer. You may think of signer as the bank account and extension as your daily wallet.

**Comment by lwshang** [comment]
Thanks for this clear explanation.
