### ISSUE TITLE
Generate signer.h at build time

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-signer#581]
`rust/signer/signer.h` should be generated by a build script instead of manually updated, for the sake of maintainability.

`cbindgen` on its own will not work, since it cannot resolve associated types.

**Comment by hanwencheng** [comment]
I think we can use `RCT_EXPORT_METHOD()` macro for doing that like in this example: https://reactnative.dev/docs/native-modules-ios#ios-calendar-module-example

**Comment by Slesarew** [comment]
It's small and meaningful now, even has comments I find surprisingly useful.
