### ISSUE TITLE
Support importing and using derived independent accounts.

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#588]
There is a use scenario that user may derive accounts and distibute them to other parties.

For other parties it would be useful to import it in Signer and use it for signing.

This feature would include following parts:

1. refactor data structure to include independent dervived accounts. 
2. ~export the seed of derived account into a QR code~.
3. enable import QR code as an derived account
4. add a list for display these indenpendent derived account.
5. refacotr signing function for support independe derived accounts.

**Comment by Slesarew** [comment]
@kirushik do we need this or is it redundant with proxies?

**Comment by kirushik** [comment]
No, I don't think _importing_ (and even less — exporting) of raw keys should be supported.
This makes backups significantly more complicated, violates quite a few of our newly-found UI/UX assumptions, while not bringing any concrete benefits over just using a completely separate key with its own seed. (Or re-using the existing seed and adding a designated derivation path. Or, as @Slesarew correctly suggests, using some proxy-based setup.)
