### ISSUE TITLE
Legacy accounts page is broken on 4.2.2

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#613]
When navigating to the "Legacy accounts" page via the top-right menu. A blank white screen appears.

iOS 13.4
Signer 4.2.2

**Comment by phillux** [comment]
I have a legacy account, that also shows a white screen when trying to sign a transaction via signer on Kusama.

**Comment by hanwencheng** [comment]
that is very stranger, on my iphone 6 do not have this problem. Some times when switching back from legacy accounts to identities, there is a white screen transition, but just in one blick, I will check on [React Navigation](https://github.com/react-navigation/react-navigation) about this problem.

**Comment by phillux** [comment]
Not only does attempting to sign a transaction give me a white screen, but just selecting the "Legacy Accounts" gives me the white screen. Hopefully this makes it easier to test and diagnose.

**Comment by hanwencheng** [comment]
@phillux  Thanks for the report, on my device:

![out mp4](https://user-images.githubusercontent.com/6014309/82443900-939ada00-9aa2-11ea-8fbb-ddef6fa8c7d0.gif)

On your white screen, is there any header on top of it?

**Comment by hanwencheng** [comment]
Is there any other actions leads to the white screen? e.g. create Identity?

**Comment by phillux** [comment]
No header, a pure white screen.

This happens only for legacy accounts.

**Comment by phillux** [comment]
still present on 4.2.6 
![ezgif-1-2a594cd32497](https://user-images.githubusercontent.com/6450379/82749774-d19e4380-9dab-11ea-9843-5b037dc8eb26.gif)

**Comment by phillux** [comment]
The entire app crashes when trying to access the legacy accounts screen.

**Comment by phillux** [comment]
Trying to sign a transaction with such an account shows a PIN entry, and when I enter a PIN successfully, there is a completely white/blank screen.

**Comment by hanwencheng** [comment]
closed by #660
