### ISSUE TITLE
Delete accounts in keychain when uninstall ios App

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#616]
Currently when user uninstall the Android app, the accounts are cleared.

But on iOS app they remain in keychain.

We want to keep a consistent behavior,  which need clear the keychain when uninstall ios app by some [objective C cod](https://stackoverflow.com/a/6203301/3060739)

**Comment by phillux** [comment]
Is there further reasoning beyond consistency here? Having the accounts stored in the keychain actually saved me one time. I would personally prefer to keep them there unless there is a possible security risk.

**Comment by hanwencheng** [comment]
Consistence is an issue, it also an security issue since any devices with same apple ID will have the keychain data and can be used here according to our [dependency](https://github.com/paritytech/react-native-secure-storage). This is definitely a case we want to avoid. This security issue could be fixed by saving keychain data only on this device with [kSecAttrAccessibleWhenUnlockedThisDeviceOnly](https://developer.apple.com/documentation/security/ksecattraccessiblewhenunlockedthisdeviceonly?language=objc) this flag.

But I still wonder why do you want to keep the data when uninstalling the app? Why I ask because ideally reinstall the app won't clear the data, only uninstall the app clears the data, and I think unsinstall means you do not want to use it any more.

**Comment by phillux** [comment]
It's true that uninstalling the app shows the intention to not revisit the app, and we try our best to make sure the user backs up all accounts before using the account. Thanks for clearing that up.

**Comment by Slesarew** [comment]
I'm not sure this is possible to fix completely - now only seeds are stored in secure enclave, but normal ways of handling it do not allow to do that:

https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06d-testing-data-storage

There might be a way to simultaneously use original keyring service and clean it up, but most probably it will kick the app from appstore.

**Comment by krodak** [comment]
Due to app sandboxing and Secure Enclave / Keychain nature, there is no technical possibility to attach any action on application install that would be reliable and consistent with App Store Review Guildelines. 

We currently do what is standard procedure and recommended approach here - we clear Keychain record for our app sandbox on first app run after install and after `Wipe All` functionality in Settings`
