### ISSUE TITLE
Dockerfile or Vagrantfile for development environment

### ISSUE THREAD

**Issue by gww-parity** [paritytech/parity-signer#623]
Let's create Dockerfile or Vagrantfile allowing effortless setup of Development environment.

(Of course based on some clean trusted image)

**Comment by gww-parity** [comment]
AFAIUnderstood currently it would need to cover:

* Xcode (looks like runs on linux: https://stackoverflow.com/a/2406839 )

**Comment by Slesarew** [comment]
Do you guys need it? Does the dockerfile we have cover typical needs? @s3krit @vas3k @TriplEight

**Comment by s3krit** [comment]
Vagrantfiles and getting MacOS working in virtualbox is a royal pain in the arse from what I remember. We've got a MacOS CI runner (and currently still bitrise), so I think efforts would be better spent getting a CI job running on that for building.

**Comment by Slesarew** [comment]
> MacOS

what about android?

**Comment by Slesarew** [comment]
done I suppose?
