### ISSUE TITLE
Improve UX/docs for restoring non-derived Polkadot account

### ISSUE THREAD

**Issue by ascjones** [paritytech/parity-signer#632]
When recovering a Polkadot account from a seed phrase (in my case generated by `subkey`), the default path (`recover` -> `Add Network Account` -> `Polkadot`) will create a `Polkadot root` account for key derivation.

This is confusing because the public address for this root keypair is different from the one generated by `subkey`.

The way to recover the non-derived key is to select `Add Network Account` > `Create Custom Path` and leave the derivation path empty. 

This is a non obvious path, and anyone restoring their Polkadot key from the seed phrase for the first time may run into this. @0x7CFE also had a similar experience so I don't feel as dumb here. At least it should be documented.

**Comment by hanwencheng** [comment]
thanks for the report, we need to make it explicit.
