### ISSUE TITLE
Export derived account to hot machine

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#640]
It would be good to export the derived account to hot machine like polkadot.js web app.

As for sr25519 the key derivation process works like:
Seed Phrase -> entropy -> Mini secret key -> hard / soft derivation -> SecretKey -> Keypairs.

We could export [SecretKey](https://github.com/w3f/schnorrkel/blob/master/src/keys.rs#L404) for the hot machine to generate the keypairs.

So that in the account screen we can generate a QR code to show the SecretKey, which will also need Polkadot.js app to add the support for it.

**Comment by burdges** [comment]
You can only export hard derived accounts since parent account could be "reverse derived" from their soft derived children under many situations.

**Comment by hanwencheng** [comment]
> At least hard_derive_mini_secret_key returns a MiniSecretKey, which might correspond to the entropy and permit export as words, depending upon what other processing the words go through.

That we we could get miniSecretKey from `hard_derive_mini_secret_key`, but It seems that it is not possible to get mnemonic from a MiniSecretKey. 

As polkadot.js api has [addFromSeed](https://github.com/polkadot-js/common/blob/master/packages/keyring/src/keyring.ts#L121-L135) function. So what I do now is generating the QR of this miniSecretKey for exporting.
