### ISSUE TITLE
React native version mismatch while building android studio

### ISSUE THREAD

**Issue by vedhavyas** [paritytech/parity-signer#657]
``` 
    io.parity.signer E/ReactNativeJS: React Native version mismatch.
    JavaScript version: 0.60.3
    Native version: 0.62.2
    
    Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with `watchman watch-del-all && react-native start --reset-cache`.
```

Any idea how I can resolve this ?

**Comment by hanwencheng** [comment]
The reason could be varaint.

It seems you are using another React Native package (could be a global one or from other projects) override the one in the current folder.

Try `yarn start --reset-cache` in the current folder.

**Comment by vedhavyas** [comment]
Seems like clearing the cache `yarn cache clean` solved it for me
