### ISSUE TITLE
The new position of the QR Code button requires an additional tap to sign another transaction right away

### ISSUE THREAD

**Issue by lucasvo** [paritytech/parity-signer#664]
In the old signer I could jump from the screen that shows the signature QR code straight back to the QR code scanner by clicking the button in the top right. The new version moved that button to the bottom of the screen and hides it completely when displaying the signature QR code. That requires an additional tap which is a bit annoying when signing several transactions at a time (something I almost always do).

It would be great to add the TX Scan button back to the screen that shows the signature QR code. There seems to be plenty of space on that screen.

**Comment by hanwencheng** [comment]
With #662 , now the back button on the Signature QR page will lead user to the QR page, which is just one click :)

**Comment by hanwencheng** [comment]
thanks for pointing that out.
