### ISSUE TITLE
Can't add polkadot network when restored from an old mnemonic phrase

### ISSUE THREAD

**Issue by VanHoutte** [paritytech/parity-signer#677]
Hi

I wanted to move my dots and use the parity signer to do so. When I add my old mnemonic phrase it generates the correct address but when I click on "Polkadot" it shows me an error: "Can't derive account from the seed: substrate address cannot be generated, please check suri and prefix".

Not sure what to do now. Any ideas?

Thanks

**Comment by hanwencheng** [comment]
Please check if the seed is a valid bip39 mnemonic phrase, if not, it can only generate Ethereum accounts, but not Substrate based accounts.
