### ISSUE TITLE
iOS App doesn't display any info about what you are signing (e.g. Extrinsics)

### ISSUE THREAD

**Issue by blockchainunchained** [paritytech/parity-signer#680]
Hello,

Not sure if this is already fixed and awaiting Apple App Store review but in the screenshots on the [sign a transaction tutorial](https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/Kusama-tutorial.md#4-sign-a-transaction) which were taken on Android this information is displayed.

On the iOS version it is not displayed. Is there a reason for this?

Thanks

**Comment by hanwencheng** [comment]
This is a known behavior in both iOS and Android version.

The reason is ChainSpecs for different networks are in active development, and we have to sync frequently to get the app not crash when signing transactions. As a matter of fact, we do not have enough resources to work on that update part or adding fallback functions, So we remove the feature temporarily.

As now the major part is almost finished, I will add this feature soon in comming release.

I will keep the issue open until we add it back.

**Comment by blockchainunchained** [comment]
Thanks for the response, it feels like a massive security issue waiting to happen. If someone accidentally uses a modified client (e.g. by mistyping polkadot.js.org) is putting all the funds in that account at risk. I understand you guys are busy and things need to be prioritised but this should be extremely high priority in my opinion.

**Comment by programmerTim** [comment]
Perhaps an online version of the app (without private keys) could be used to independently verify what is being signed?

**Comment by blockchainunchained** [comment]
@Tbaut how is it possible to safely use this app without this feature? This is an accident waiting to happen. Either Parity Signer should be entirely deprecated, a work around developed (e.g. how does someone even check the transaction says what they think it says?) or a fix implemented for this. It's not fair or acceptable to provide an insecure crypto wallet.

**Comment by Tbaut** [comment]
I agree, this is not acceptable and Parity Signer should not be used right now. The main developer and maintainer is not working at Parity any more, and other developers have step up recently to help make it happen. I am myself blocked by https://github.com/paritytech/parity-signer/issues/713 and can't build master. I have a workaround in my fork... We should move on this in the next days I hope.

**Comment by blockchainunchained** [comment]
Well done for stepping up, I fear that both the website and the Polkadot wiki point to this wallet as acceptable to use and this is clearly not the case. A warning needs to be put up before someone gets hurt.

**Comment by blockchainunchained** [comment]
I've created a seperate but linked issue regarding the current lack of any warnings and some potential work arounds:

https://github.com/paritytech/parity-signer/issues/724
