### ISSUE TITLE
Have User confirm that he backed up recovery phrase

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity-signer#69]
E.g.: After pin is set up, show recovery phrase again w/ a note urging user to write it down and maybe a checkbox?

**Comment by 5chdn** [comment]
Ok, pretty much this ^.

https://ethereum.stackexchange.com/questions/25476/parity-signer-qr-code-not-working-stuck-on-parity-signer-pending

**Comment by fckt** [comment]
I'm planning to add a skippable seed verification step to the account creation process, based on the same idea as https://github.com/paritytech/fether/issues/100#issuecomment-406869879
