### ISSUE TITLE
Adding non-ETH Chain support like XinFin[XDC] 

### ISSUE THREAD

**Issue by hckhunk** [paritytech/parity-signer#702]
We have developers looking at this code base. Have a few questions.

   1.  Is this solution used by polkadot users self custody wallets currently? Is it still in beta?
   2.  Is there a readme to add non-ETH but eth compatible chain like XinFin[XDC]
  3.   Are the devs active? if we are to add support?

The only changes that are required are RPC Endpoint :
https://rpc.xinfin.network/

And addresses on XDC network have prefix of "xdc" instead of "0x"

txhash is same obviously

**Comment by hckhunk** [comment]
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-50.json

**Comment by Slesarew** [comment]
Support for all ethereum-based networks will be dropped for the time being. No new features for non-Substrate networks will be added.
