### ISSUE TITLE
User Interface -- clarify first time account creation

### ISSUE THREAD

**Issue by toholdaquill** [paritytech/parity-signer#704]
A first-time Parity Signer user reports the following confusion when setting up Parity Signer for the first time:

---
Once you have the identity done with parity signer and proceed to make an account you see the message "Create your first Key Pair" at the top but it is presented visually in the same way as the network names so it is easy to miss.

Then if you do the mistake as I did to go faster than the training document and click polkadot network and then, follow the document and realise there was a step where it says "Create your first Key Pair" you don't see it anymore and as there is only Add Network Account.

together with the fact that I don't know what is "Key Pair" concept, can create insecurity of following the process correctly.

**Comment by hanwencheng** [comment]
Maybe could change "first Key Pair" to "first account".

**Comment by Slesarew** [comment]
This is related to #777
