### ISSUE TITLE
Can't build on linux

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#707]
```
yarn build  
yarn run v1.22.10
$ yarn install && npx pod-install
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
npx: installed 1 in 1.099s
Scanning for pods...
CocoaPods is only supported on darwin machines
```

**Comment by geastwood** [comment]
Developing iOS target requires OSX, which is logical given this error message.

It's possible to run Android target, where running `npx pod-install` is not necessary.

**Comment by Tbaut** [comment]
I guess `build` should be changed to `build:ios` or something similar, and it should be removed from the `Setup` here https://github.com/paritytech/parity-signer/blob/master/docs/wiki/Development.md#setup because this is only for iOs too.

**Comment by geastwood** [comment]
Yeh, it makes sense. I could prepare a PR.

**Comment by Tbaut** [comment]
Thanks @geastwood, just did it with other small things I found: https://github.com/paritytech/parity-signer/pull/708
