### ISSUE TITLE
App crashes on old iPhone 5S

### ISSUE THREAD

**Issue by michalisFr** [paritytech/parity-signer#728]
The app fails to start on a freshly restored iPhone 5S. It starts to load (show the white screen) but then simply crashes.

Since Signer is supposed to be used on old, decommissioned phones, so that it's offline, this needs to be looked into I think.

**Comment by TarikGul** [comment]
Hey @michalisFr, could you provide a little more info on this. 

Are you downloading from the App store or are you running it remotely from a local repo? If from the App store what version of iOS are you running on your current iPhone 5S device?

**Comment by michalisFr** [comment]
Yeah, sorry for not providing this info.

I had downloaded the app from the App Store and was running it on 11.2.2. Once I upgraded to 12.5.1 the app worked. Sorry, for the false alarm.

**Comment by TarikGul** [comment]
No Worries, that is still good to know. Thanks again for the follow up. Glad it worked out.
