### ISSUE TITLE
Detox test crashing in CI tests, but passes locally with no error

### ISSUE THREAD

**Issue by TarikGul** [paritytech/parity-signer#729]
There is a weird characteristic happening when e2e testing locally versus in the CI pipeline. 

```
RCTFatalException: Unhandled JS Exception: Error: Maximum update depth exceeded. This can happen when a component
repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to
prevent infinite loops.
```

Since the tests are passing locally I have decided to comment out the the two specific tests in this [PR#682](https://github.com/paritytech/parity-signer/pull/682)

After some digging around I believe the setState error is happening inside of the `QrScanner` Component, through a callback called `processBarCode`.

**Comment by Slesarew** [comment]
@TarikGul could you please just double-check if this bug is still encountered? I think we've eliminated it in PR#682

**Comment by TarikGul** [comment]
Yes, in the process of checking it right now, seems to be all good. Got one error with `✕ should sign message (7316 ms)` but i need to re clean my test enviornment and double check, but overall it looks great.

**Comment by TarikGul** [comment]
Everything Passes and is now working. We can close this issue with [#682](https://github.com/paritytech/parity-signer/pull/682)
