### ISSUE TITLE
How do I access my Ethereum stored on a parity signer ios app in 2021?

### ISSUE THREAD

**Issue by vessenes** [paritytech/parity-signer#731]
Hi,

Parity Signer lists MyCrypto and Fether as wallets that use ETH and can target the signer.

MyCrypto has upgraded and I can't find an option to target Parity Signer anymore. Fether is liberally festooned with warnings that it's abandoned. 

So, I love Polkadot and I am long DOT, but I also have a few old trashy ETH and I want to use them. What is the way that I can get Parity Signer to sign an ETH transaction today in 2021?

**Comment by Tbaut** [comment]
I had opened an issue long ago for MyCrypto to consider keeping Signer, feel free to comment and add a +1 here https://github.com/MyCryptoHQ/MyCrypto-Beta/issues/24

MyCrypto desktop app is the last way you can use your ETH with right now https://download.mycrypto.com

**Comment by vessenes** [comment]
Thanks. Is there a long-term plan here? It seems like you guys could add wallet connect support to the signer - it's fully in your control to do so, and would let your customers use more modern web wallets.

**Comment by Tbaut** [comment]
Walletconnect will have trouble working offline though :)

There are many many secure ways to recover an ETH address, if modern connected wallets don't want to support Signer, there's not much we can do. The community is the best at being vocal about it, at the end of the day, the connected wallets are the ones who decide.

**Comment by Slesarew** [comment]
ethereum not supported anymore
