### ISSUE TITLE
Parity Signer Transactions

### ISSUE THREAD

**Issue by ghost** [paritytech/parity-signer#744]
Hi,
i am trying to do transactions with my offline parity signer account in rococo network but when i try to use the transaction's validate qr code the parity signer app returns the error message "Unable to parse QR data we cannot handle the payload: 0,0.....".
Anyone knows why this is happening? i thought it should be easy...

**Comment by Slesarew** [comment]
> Hi,
> i am trying to do transactions with my offline parity signer account in rococo network but when i try to use the transaction's validate qr code the parity signer app returns the error message "Unable to parse QR data we cannot handle the payload: 0,0.....".
> Anyone knows why this is happening? i thought it should be easy...

could you please provide a bit more details on this? What kind of transaction did you attempt? Which interface did you use to generate the QR code? What is your version of signer?

Unfortunately, the rococo network doesn't get as much testing as others now, so your input would be really helpful.

**Comment by Slesarew** [comment]
Anyway, this was typical behavior when the network is not added to Signer.
