### ISSUE TITLE
use parity signer to sign transaction offline in a custom substrate chain

### ISSUE THREAD

**Issue by sergeibadass** [paritytech/parity-signer#752]
The QR code of tx generated from polkadot js app can not be read on the parity signer for custom chains. It prompts can not process the payload. The same process however works on polkadot mainnet

Is there a way to add support to a custom chain without writing codes? Are there solutions available for my problem? Many thanks.

**Comment by Slesarew** [comment]
The custom network should be first added to the app's known networks for this to work. All of this is highly experimental at the moment and might fail to work, but you should expect this to be included into one of the nearest releases.

Meanwhile, could you please tell me the error message text and the network you've encountered this error with?

**Comment by sergeibadass** [comment]
> The custom network should be first added to the app's known networks for this to work. All of this is highly experimental at the moment and might fail to work, but you should expect this to be included into one of the nearest releases.
> 
> Meanwhile, could you please tell me the error message text and the network you've encountered this error with?

thanks i managed to add a custom network and test it extensively with many extrinsics calls. thanks.
