### ISSUE TITLE
couldn't find DSO to load: libhermes.so

### ISSUE THREAD

**Issue by ramast** [paritytech/parity-signer#771]
D/SoLoader( 3239): About to load: libhermes.so
    D/SoLoader( 3239): libhermes.so not found on /data/data/io.parity.signer/lib-main
    D/SoLoader( 3239): libhermes.so not found on /data/app-lib/io.parity.signer-1
    D/SoLoader( 3239): libhermes.so not found on /system/vendor/lib
    D/SoLoader( 3239): libhermes.so not found on /system/lib
    E/SoLoader( 3239): couldn't find DSO to load: libhermes.so
    Could not find method android.view.View.isNestedScrollingEnabled, referenced from method androidx.core.h.u.A
    Could not find method android.view.View.stopNestedScroll, referenced from method androidx.core.h.u.B

Running Android KitKat 4.4 and Parity-Signer-v4.5.3-beta

**Comment by Slesarew** [comment]
This is really weird, we were building it without Hermes. I've double checked the code and we are changing the whole build process now, hopefully this will go away in the next beta build. Please let me know if you see it again!
