### ISSUE TITLE
feat: add ability to add network support for to-be-launched parachains

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity-signer#778]
Rationale: Currently Parity Signer can't be used to generate keys for not-yet-launched parachains, i.e. for https://wiki.acala.network/acala/acala-account

See also [related polkadot.js-apps issue](https://github.com/polkadot-js/apps/issues/5500)

**Comment by bjornwgnr** [comment]
Please see https://github.com/polkadot-js/apps/issues/5500#issuecomment-856705611 - it doesn't cover the need of folks to be able to create accounts in Signer for new networks that have not yet submitted the genesis-hash to Kusama/Polkadot.

**Comment by Slesarew** [comment]
Can someone test if the new network import message could be generated with this?

https://github.com/paritytech/parity-signer/tree/ios-native-port/rust/generate_message

The network pretty much needs _some_ genesis hash as it is an ID for the network; I suppose it is OK to delete the network and import it again when/if that genhash changes?

**Comment by Slesarew** [comment]
This is clearly implemented and somewhat tested but needs more testing; please open new issues when things break.
