### ISSUE TITLE
Signer causes Parity.exe to use 100% CPU endlessly

### ISSUE THREAD

**Issue by dev-dan** [paritytech/parity-signer#78]
Windows 10, 64bit
Parity 1.7

Anytime I open the signer extension, my parity.exe CPU usage shoots to 100%.
As soon as I close the signer extension, CPU drops back to 1-5% for parity.... 

Have noticed multiple bugs in parity issues described doing that, some with but most without mention of the signer and made comments there as well.

**Comment by debris** [comment]
Hey! The issue is actually not related to this repo at all. This is a mobile app for iOS and Android ;)
