### ISSUE TITLE
Automate UI/UX test releases

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#799]
We need automated releasing for testers; it does not have to be properly signed and cleanroom-built, just UI/UX testers should be able to test new features as soon as they are available. This should be tested on live subjects often as it is the central piece now.

Example of automated ios build flow is here:
https://github.com/paritytech/parity-signer/blob/ios-native-port/.github/workflows/actions.yml
We need to be able to release it in testflight with minimal effort; there should be release candidate versions built cleanly as well, but that's another story. We need some system to differentiate those.

Android build script will be ready when code itself will be ready.

**Comment by denisp-gh-admin** [comment]
please do not assign this account anywhere, it's a service one.

**Comment by Slesarew** [comment]
One way or another, this is done!
