### ISSUE TITLE
Filter history for a key

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#806]
Some screen that shows all signings with a given key.

**Comment by goldsteinsveta** [comment]
It would be super useful to have it in the key screen!
<img width="614" alt="Screenshot 2022-05-12 at 13 49 26" src="https://user-images.githubusercontent.com/8782596/168068469-7f266e95-f44a-4e1d-acdf-9340e5e4d750.png">

**Comment by krodak** [comment]
No feature planned in current roadmap, not aware of any update by @tetekinandrey to support this, closing for now, as also not requested by users.
