### ISSUE TITLE
`Unable to parse QR data` while signing the transaction through parity signer app

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/parity-signer#809]
I created some accounts on my parity signer app and imported in https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ffullnode-relay.chachacha.centrifuge.io#/accounts

I was trying to transfer some fund. But when I am scanning the QR code presented by the Polkadot-js apps website, I am getting below error

![WhatsApp Image 2021-09-04 at 8 31 18 AM](https://user-images.githubusercontent.com/1575561/132084545-cc6f55e0-bcc8-4ecf-97ff-61984c0e11ea.jpeg)

Please let me know if I am missing anything. I am following these instructions https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/Kusama-tutorial.md#4-sign-a-transaction

**Comment by Slesarew** [comment]
This usually happens if you failed to add network. Please try this. https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/New-Network.md

This will not happen in the next version, it will provide clearer instructions on the nature of error.

**Comment by ayushmishra2005** [comment]
it worked @Slesarew Thanks

**Comment by Dgetsylver** [comment]
Hi, it seems that the tutorials are unaccessible for the moment (error 404). Could you please share the procedure ?
@ayushmishra2005 @Slesarew
