### ISSUE TITLE
Automate prepopulated database generation

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#825]
The prepackaged network information database (reflecting state of device upon fresh installation or wipe) is an important piece of security and general functionality; it should be controllably and reproducibly generated for development builds, tests and releases.

Furthermore, it is possible that the Signer will be distributed in stores with (user eraseable and replaceable) pre-set key (public asymmetric) of trusted party for convenient secure updates, while default build from github will not have any keys. This calls for different scripts that should respect the corresponding workflow.

At the same time, database contents and structure change with time (due to Substrate and its networks evolving) and Signer's development.

Currently the Signer's database ("cold db") is generated from stored larger database ("hot db") used also for generating update videos. It has to be manually moved to os-specific folders before build - I do it before committing, in future I will gitignore those folders and rely on script to do this.

We need some policy on what should be in cold database for each use case.

Thus:

~- [ ] Database generation example script~
~- [ ] Database generation script for development - recommend same one for users building directly from repo~
~- [ ] Database generation script for tests - could be same as development maybe?~
- [x] Database generation script(s) for release
- [x] Automatically copy cold db to both os assets
- [x] Bundle with build script

**Comment by kirushik** [comment]
@vas3k please note how this feature might rely on our planned metadata dashboard project.

**Comment by Slesarew** [comment]
> @vas3k please note how this feature might rely on our planned metadata dashboard project.

It might be the other way around, please see my db's capabilities. The dashboard will require manual control for signing probably though, just to properly airgap keys or something like that.
