### ISSUE TITLE
Do not require unnecessary permissions

### ISSUE THREAD

**Issue by debris** [paritytech/parity-signer#83]
discussion: https://github.com/paritytech/parity/issues/7487#issuecomment-356014748

**Comment by zumbatan** [comment]
@debris   , hi thanks greatly appreciated taking up this topic!  i am sure you know the opportunities (good or bad) with some permissions. actually preferably such a "2fa code" generator should have not ANY permission.

**Comment by debris** [comment]
@fckt I believe this can be closed, right?
