### ISSUE TITLE
Support for more networks and parachains

### ISSUE THREAD

**Issue by michalisFr** [paritytech/parity-signer#848]
As the substrate ecosystem grows there is increased need for support for other chains and especially parachains. There is currently no cold storage solution for any other chains besides Polkadot, Kusama (Ledger and Parity Singer)  Centrifuge and Kulupu (only Parity Signer).

Perhaps a change in the way things are done in Signer is the best approach. Instead of using specific derivation paths (`//polkadot`, `//kusama` etc) that require the addition of each chain separately by the development team, the app should adopt standard sr25519 and ss58 formatting so the same account can be used on all chains as it happens on the Polkadot-JS UI or the extension.

**Comment by ImdioR** [comment]
Good day. 
I need help with import/export account from parity, I would like to import my existing account from Parity to Polkadot.js, but after importing i see that my wallet address is different. So i just make deep research and found that i should to use the derivation path. I have also checked manual/docs, but didn't find anything. Somebody could help me, please?
Thank you.

**Comment by Slesarew** [comment]
@ImdioR The default derivation path is `//networkname` where "networkname" is name of your network. Please see https://github.com/paritytech/parity-signer/issues/833
