### ISSUE TITLE
Allow import of wallets

### ISSUE THREAD

**Issue by fr34kyn01535** [paritytech/parity-signer#85]
I'd love to see a way to import my existing private keys into this application.

**Comment by Tbaut** [comment]
We will support BIP39 (MEW, Metamask, MyCrypto, Jaxx..) for the v3, hopefully (tight schedule).
Closing in favour of https://github.com/paritytech/parity-signer/issues/154

We do not plan to implement any other sort of importing (JSON etc) as this would potentially increase the attack surface. Seed phrase import is considered good enough.. for now at least.

Let me know if this is not what you meant.
