### ISSUE TITLE
Add phrase validation/warnings

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-signer#86]
We should:
- validate that phrase contains 12 words coming from parity dictionary (see https://github.com/paritytech/wordlist)
- Display a warning otherwise. Warn especially about weak phrases with not enough entropy.

Consider allowing custom phrases only as advanced feature:
1. i.e. first enable custom phrases in options
2. Allow custom phrase only after double-confirming the security implications

**Comment by fckt** [comment]
Implemented https://github.com/paritytech/parity-signer/commit/1f814a6da99fba912880e9ee8c324423e529a950
