### ISSUE TITLE
Android Build from master, run crash

### ISSUE THREAD

**Issue by wojiaopaidaxing** [paritytech/parity-signer#865]
![image](https://user-images.githubusercontent.com/9145559/139659961-3402732d-ad87-414a-95c8-1620c5524cf6.png)

I compile according to the document, but there is an error when I run it

**Comment by Slesarew** [comment]
Which document? I've moved all building manuals for the master branch to docs that are not available from github home page, readme describes building of older branches.

Master branch does not support Android yet. Statement about it was accidentally removed from the manual. Android support is work in progress, you can see a snapshot of it in https://github.com/paritytech/parity-signer/tree/backend-atomize-db-and-certificates-policy and it should be ready soon. Please see the pinned issue above (I'm closing this one as duplicate).

Meanwhile, your error is unusual; please make sure you've run `scripts/build.sh android` before building android version.
