### ISSUE TITLE
Sort accounts by networks

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-signer#87]
For the functionality it doesn't matter very much, but users ([even very technical users](https://github.com/MyCryptoHQ/MyCrypto/pull/1349#issuecomment-375041320)) can be unaware that all accounts work with any Ethereum-like network. Having a dropdown of networks that an account can be assigned to would go a long way here.

**Comment by tomusdrw** [comment]
We could probably detect a mismatched `chain_id` in case non-replay protected transaction is being signed or a transaction for different chain.

**Comment by fckt** [comment]
I think it's implemented in the 2.0
