### ISSUE TITLE
Banana split

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#872]
Signer should be able to add seed by scanning bananasplit-generated sequence of QRs.

**Comment by Slesarew** [comment]
Blocked by https://github.com/RustCrypto/AEADs/issues/377

**Comment by Slesarew** [comment]
WIP link so that it's easy to find

https://github.com/paritytech/banana-recovery-rust

**Comment by montekki** [comment]
Implemented in #1550 and #1506
