### ISSUE TITLE
Long payloads signing

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/parity-signer#874]
Hi,

trying to use the Offline Signer in a real world scenario, I attempted to participate in the [acala crowdload](https://acala.network/acala/join-acala) (with the offline signer we've set up during the BCN retreat). After first failing because it had outdated metadata - leaving me with a screen with a minor error message in between but no real path what I could do about anything. After updating the metadata, I was finally able to see the metadata and click sign. However, the resulting signature was rejected (twice) by polkadot:

![image](https://user-images.githubusercontent.com/40496/140768508-2fd2b76e-b304-47fd-a263-34b055b2c047.png)

I noticed that on the signed screen it says: "signed as", but then doesn't show anything. I tried to use the `/polkadot`-derived key, but the UI never asked me which key to sign with. I suspect it might has signed with the wrong key. But I have no further evidence to back this up. Let me know if I can help with anything else.

**Comment by Slesarew** [comment]
Blank "signed as" is a bug.

Trying this myself on Westend, I got error 1010 but it states that signature is OK but transaction is invalid. Similar transaction performed with non-external account on polkadot.js works properly. This is weird. Similar (same or not?) bug is apparently observed in different versions of Signer, with and without companion.

**Comment by Slesarew** [comment]
Metadata generated by me and by Martin result in similar behavior, qr-downloaded and preinstalled.

**Comment by Slesarew** [comment]
Started working again; pretty sure what I observed was not related to Signer.

Please note existential accounts change that happened recently, I've mistakenly took failure due to that change in limitation for this error couple of times while testing.

**Comment by Slesarew** [comment]
Fixed in "4.6.6" version (sorry for improper versioning protocol, things are pretty broken on that front)
