### ISSUE TITLE
Help page / wiki (needed for MyCrypto)

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-signer#88]
A short page describing the workflow with the app step by step with screenshots / pictures that we can link around.

**Comment by 5chdn** [comment]
Maybe @Tbaut can help out :)

**Comment by maciejhirsz** [comment]
Also, by request, we should have a Privacy Policy for the signer. Should be pretty easy since we don't collect any data :).

**Comment by Tbaut** [comment]
eventually add :
How to recover an account with Parity signer

**Comment by Tbaut** [comment]
I'll eventually add :
How to recover an account with Parity signer
