### ISSUE TITLE
Removing keys from extension

### ISSUE THREAD

**Issue by wirednkod** [paritytech/parity-signer#880]
When trying to remove a key from extension a countdown begins (10 seconds).
If the user closes the popup window of the extension (apparently) the countdown stops and the account is never removed.

If that is the correct functionality, I think there should be a note saying: "Do not close popup until key is removed"

**Comment by Slesarew** [comment]
Why did you move this here? This is too hot side for Signer; the app shouldn't even have slightest idea what happens in the extension.

**Comment by wirednkod** [comment]
@Slesarew my mistake. I should have left that in the extension side. Will revert
