### ISSUE TITLE
Exporting Parity Signer account 

### ISSUE THREAD

**Issue by ssfking** [paritytech/parity-signer#887]
Is there any way to fully export my Parity Signer via the seed phrase into Polkadot.js account so that I don't have to use parity Signer to sign my transactions anymore? I tried doing that but the seed phrase from Parity Signer generates a different address on Polkadot.js. Thanks.

**Comment by Slesarew** [comment]
Add `//kusama` derivation path to polkadot.js generation flow, polkadot.js uses blank derivations by default while last published Signer version uses `//networkname` by default. Feel free to comment here if you have further problems.
