### ISSUE TITLE
Feature request: Import/export derivations

### ISSUE THREAD

**Issue by pepyakin** [paritytech/parity-signer#896]
Upgrading of the app involves removing all the seeds added. That's fine and expected: this is a security feature. However, besides removing the seeds all the derivations are removed too.

I can imagine a heavy user who has dozens of identities derived from the same seed would be really disappointed when have to upgrade the signer or change the device, because they will have to put all the derivations again. At the same time derivations do not seem to be sensitive information.

So I am wondering, is to worth it to add a feature to import/export derivations, just like Ledger does?

**Comment by Slesarew** [comment]
Yes, this is being discussed. This should go well with #872 and #871; we can have "derivation templates", create them on hot side or in Signer. This would be quite useful flow indeed.

**Comment by Slesarew** [comment]
import of derivations was deployed in #885 - use generate_message to prepare a QR with derivations template. These imports are network-specific but not seed-specific so they could be used as templates indeed.

Export will have to wait for a while; android version, bananasplit and polishing are more urgent

**Comment by montekki** [comment]
device-to-device migration was implemented in #1429 and #1569, for single-device upgrades a support from frontent (for example Nova wallet) is needed that can "store" the info and "show" the QR codes to the newly upgraded device to perform the import.
