### ISSUE TITLE
Key combination is not supported for Karura or rococo ?

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#948]
When trying to generate metadata apng for Rococo or Westend, I got the following error. Any clue why?

```bash
cargo run load_metadata -u wss://rococo-rpc.polkadot.io
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `/home/parity-signer/rust/target/debug/generate_message load_metadata -u 'wss://rococo-rpc.polkadot.io'`
Error: "Key combination is not supported. Please file a ticket if you need it."
```
```bash
cargo run load_metadata -u wss://karura-rpc-0.aca-api.network                            
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `/home/parity-signer/rust/target/debug/generate_message load_metadata -u 'wss://karura-rpc-0.aca-api.network'`
Error: "Key combination is not supported. Please file a ticket if you need it."
```

I also tried with the key `-sr25519` or `-ed25519` without success
```bash
cargo run load_metadata -u wss://karura-rpc-0.aca-api.network -sr25519      
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `/home/parity-signer/rust/target/debug/generate_message load_metadata -u 'wss://karura-rpc-0.aca-api.network' -sr25519`
Error: "Unexpected key and argument sequence."
```

**Comment by Tbaut** [comment]
ok, I saw in the examples that it's running with `-d`, which worked. But I don't really understand the concept of database. I guess I can generate apng without updating the database :man_shrugging: ?

**Comment by Slesarew** [comment]
To add network to db, you need to input network specs (including things like color - not used anywhere yet, but kept just in case - and default derivations, that can't be found anywhere). Indeed you don't need db for generating updates - it's just convenience tool for version control, safety and such, not much sense really using it if you are just rolling your own updates as opposed to maintaining centralized distribution channel.

**Comment by Tbaut** [comment]
Thanks for the prompt answer, I've some other questions, but somewhat unrelated, I'll create dedicated issues :)
