### ISSUE TITLE
Several token and decimals - can we default to the first?

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#949]
When adding the specs for Karura, I got the following answer:
```
Network supports several tokens. An array of tokenDecimals [12,12,12,12,12,12,12,12,8,12] and an array of tokenSymbol ["KAR","KUSD","KSM","LKSM","BNC","VSKSM","PHA","KINT","KBTC","TAI"] were fetched. By default, decimals value will be set to 0, and unit value will be set to UNIT. To override, use -token <value_decimals> <value_unit>. To improve this behavior, please file a ticket.
```
Indeed when scanning the QR I had decimal 0, and UNIT as token name. Any way you actually change this behavior to use the first set (in this case KAR and 12) ?

as if I was running
```
cargo run add_specs -u wss://karura-rpc-0.aca-api.network -sr25519 -token 12 KAR
```

As far as I understood from my tests, this will mostly be used for Tip and balance transfer, so there should only by 1 that is set anyway.

**Comment by Slesarew** [comment]
This should be fixed manually every time. I will not default to anything in this tricky ambiguous case unless there is ecosystem-wide convention. Token order is not specified anywhere and Signer will just follow the system - now you should be adding units manually.

This is within spirit of design - network addition is a serious step for now and should require attention and deliberate decisions.

To do something automatic here, we would need to parse metadata and find which unit is really used for basic network operations; unfortunately, according to my research, existing networks are not uniform about this and ordering of token parameter arrays.

**Comment by Tbaut** [comment]
Understood, thanks
