### ISSUE TITLE
Android - Bug - Scanner thinks anything is a multiframe QR

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#951]
### What happened:
- I'm scanning a normal (single frame) QR code, but the scanner thinks it's a mutli-frame (shows the bar and absurd numbers like 7/282 )

### How to reproduce
- scan a multiframe QR code successfully (in my case Karura metadata, whether or not you have the network spec doesn't matter)
- then scan an extrinsic QR code, for instance.
- I had the bug twice that while scanning a single frame QR, after having added some network metadata, the scanner showed the multi-frame progress bar. I had to click on "start over" for the scan to work again.

**Comment by Slesarew** [comment]
This is likely caused by improper clearing of frame collector upon transaction parse. Should get fixed once it submerges into rust as well.

**Comment by Slesarew** [comment]
I think it got temporary fix in #986

**Comment by Tbaut** [comment]
As an update, this annoyance is still present in the latest master unfortunately.

**Comment by Tbaut** [comment]
Here's a concrete example where this happened to me. I'm on android:
- I update a metadata, say Polkadot, with say 322 parts. it works well.
- Then I want to sign a 1 part transaction.
- The QR reader will show 1/322 as if my Tx was 322 parts, although it's not, it's 1 QR.
- I need to click "Start over" button for the Tx to be scanned correctly

**Comment by Dmitry-Borodin** [comment]
I can't reproduce it, maybe this was fixed during banana split implementation.
@Tbaut could you check again?

What I see is that after successful transaction Usually camera starting next transaction. For example after importing metadata I usually don't move phone from QR code rightaway, so I starting scanning metadata again and getting few frames.
@tetekinandrey do you think it make sense to pause camera recognition for while some bottom sheet overlays are shown?

**Comment by Tbaut** [comment]
I've tried the latest build, and realized that the version I was building was very old compared to master. I can't reproduce the issue either. Thank you so much, and sorry for keeping this open in the backlog for so long.
