### ISSUE TITLE
Forbid screenshots on secrets display

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#963]
- [ ] Forbid secret screenshots in iOS
- [ ] Forbid secret screenshots in Android

This includes at least seed display, seed entry screen and all password forms (including plain key derivation screen)

**Comment by krodak** [comment]
There is no technical possibility to prevent any application from taking screenshot, as this functionality is on the system level, not limited to application's sandbox. There is only possibility to inform user afterwards that screenshot was taken.

Currently we are informing user of this risk during onboarding
