### ISSUE TITLE
Parity Signer

### ISSUE THREAD

**Issue by ccris02** [paritytech/parity-signer#965]
Had few question:
Does Parity Signer use [https://polkadot.js.org/phishing/#](https://polkadot.js.org/phishing/#) to block the addresses involved in the scam?
Based on the polkadot{.js}/phishing addresses are only blocked by polkadot{.js} apps and Fearless Wallet.
"The addresses are blocked in wallets such as [polkadot{.js} apps](https://polkadot.js.org/apps) and [Fearless Wallet](https://fearlesswallet.io/)."

**Comment by Slesarew** [comment]
Signer is an airgapped app and does not interact with network. Everything related to safety should be handled through hot-side apps. If Signer is used with signer companion, which is based on polkadot.js, you get features inherent for polkadot.js; however, there are no limitations on use of Signer with other tools.

**Comment by Slesarew** [comment]
@goldsteinsveta please see if this belongs to FAQ. I haven't seen this question before (I think?) but it is reasonable question and we can't overemphasize the importance of phishing prevention.
