### ISSUE TITLE
[new ui] new account details screen

### ISSUE THREAD

**Issue by debris** [paritytech/parity-signer#97]
for now, without 'signed transactions', as this is a new, separate feature

<img src="https://user-images.githubusercontent.com/2613714/38880237-82785a32-4265-11e8-8d4b-973aaf297834.png" width="350">

**Comment by fckt** [comment]
How we are going to handle cases when user use single account on the different networks (forks)?

**Comment by fckt** [comment]
> @debris @fckt have an update to this screen based on some feedback with @maciejhirsz and others
> 
> <img src="https://user-images.githubusercontent.com/48677/39826759-06723176-53b6-11e8-97c0-62be296917ed.png" width="350">

On the first mockup there is a hint "tap to edit account". In the current it's not obvious..

Also when user taps on "Account card" (which is on accounts list, transaction details screens) it typically leads to the "account details", not to the "account edit".

**Comment by fckt** [comment]
> How we are going to handle cases when user use single account on the different networks (forks)?

From Riot:

> on the UI it should show as separate accounts, even if they have the same address / private key
> we should go with the ERC-681 for the QR codes (that will need an update for the Parity Wallet UI and MyCrypto, but that's easy)
> if I unlock a kovan account but have mainnet selected in MyCrypto because I didn't bother to change it, it can prompt "hey, this account is for Kovan, do you want to change to that network?" or some such
> anyway, that's on their side so ignore it for now, if the info is in the QR code they can use it
