### ISSUE TITLE
upgrading parity signer app to v5.0

### ISSUE THREAD

**Issue by HmB4** [paritytech/parity-signer#984]
So disappointed that I have updated parity signer app to version 5.0 then the previous key is not automatically integrated to new feature, please show me how to get it back. Help Dev team!

**Comment by Slesarew** [comment]
The app is not designed for updating without full device wipe as this breaches the airgap ans effectively makes the app useless. Upgrading is not supported and should not be possible if the app is used correctly. Without the airgap, storing the keys in browser extension is generally safer than on Signer. Please read the documentation.

All previous keys could be easily recovered through "recover seed" button using the backed up seed phrase and derivation paths. The seed phrase must be backed up at all times, you should not rely solely on the phone not to break down at any moment.

If you for some reason do not have the seed phrase backed up, there is slim chance that it could be recovered by downgrading the app (I don't know how, but I've heard it is possible), but newer versions should make even this impossible.

Please let me know if you need more detailed directions here. Sorry for inconvenience.
