### ISSUE TITLE
UX: seed phrase generation

### ISSUE THREAD

**Issue by montekki** [paritytech/parity-signer#985]
Whenever the user checks "I have written down my seed phrase" it would probably be a good idea to make sure that he did by asking to re-enter the phrase in the next fragment. Ledger does it upon device init, signer should probably do it too.

**Comment by Tbaut** [comment]
This is the most annoying thing ever. If user do not care about their seed phrase, they'll write it on paper and trash that paper. Please don't do this.

**Comment by Slesarew** [comment]
Right, we've been discussing this feature for a long time with UX experts. However, feel free to throw ideas on how exactly that should work here, maybe there is some balance.

IMHO, the safest and sanest approach would be to forbid saving random seeds altogether, but require users to roll them and then recover. On the other hand, users can do it now (I know some who do this, gosh, I'm doing this myself!) and forbidding other flows while this one is easily available just has to be optional.

**Comment by montekki** [comment]
ok
