### ISSUE TITLE
UI: rename seed

### ISSUE THREAD

**Issue by goldsteinsveta** [paritytech/parity-signer#988]
Related to https://github.com/paritytech/parity-signer/issues/856
[_Design doc_](https://www.figma.com/file/jkVxsKUahgJpGOxrrfOI9H/?node-id=1619%3A12469)
[_Video prototype_](https://drive.google.com/file/d/1TLcC7872Q5R1BWIEEs5mcmxmqCKT6uwz/view?usp=sharing)
<img width="969" alt="Screenshot 2022-04-05 at 10 43 18" src="https://user-images.githubusercontent.com/8782596/161714662-26de4f05-026b-45c6-9db7-ad4bbc291b92.png">

**Comment by prybalko** [comment]
Renamed to `Key sets`
