### ISSUE TITLE
error handling and panic policy

### ISSUE THREAD

**Issue by montekki** [paritytech/parity-signer#996]
Error handling by hand can be improved by tools such as `anyhow`.

code contains a great deal of `unwrap`-ing although these situations in most cases look like they can be handled gracefully: 

```
rg unwrap | wc
    617    1954   53729

```

**Comment by varovainen** [comment]
Most of these are parts of the tests. The rest are directly test-related helpers, as far as I remember.
Helpers use known data, so they are `.expect()` really. This is easy lint, I can add it real quick.
What do you suggest doing with tests?
I suppose the idea is not to trigger automatic checking for obvious things.
Real errors are in `definitions::error`, `definitions::error_active`, `definitions::error_signer` ("active" and "signer" list, respectively, all hot and cold side errors that could be encountered; if there will be anything to add, it has to go there).

**Comment by Slesarew** [comment]
`rg` search does not make sense here as it plows tests as well. This issue is too vague.
