### ISSUE TITLE
scanning multiple multipart QRs displays wrong part count

### ISSUE THREAD

**Issue by coderobe** [paritytech/parity-signer#998]
Scanning a multipart QR right after another will display the total number of multipart fragments from the *previous* QR, leading to UI inconsistencies like "330/240" where the amount of parts scanned is correct but the total is wrong

**Comment by Tbaut** [comment]
This is most probably a duplicate of https://github.com/paritytech/parity-signer/issues/951

**Comment by coderobe** [comment]
Ah, sounds like it - same bug, different manifestation
